#!/bin/bash
source /etc/opt/board.txt
source /etc/default/dynamic-motd

if [[ "$BRANDING" == "true" ]]; then
	echo "";
	toilet -f ${T_FONT} --filter ${T_FILTER} $DEFAULT_MOTD;
	echo "";
else
	if [[ -f "/proc/device-tree/model" ]]; then
		COL="\033[1m"
		FIN="\033[0m"
		MODEL=$(tr -d '\0' </proc/device-tree/model)
		echo "";
		echo -e "${COL}== BOARD${FIN}"
		echo -en "${COL}Model:${FIN}       "
		toilet -f term $MODEL;
		echo "";
	fi
fi
