#!/bin/bash
source /etc/opt/board.txt
source /etc/default/dynamic-motd

if [[ "$BRANDING" == "true" ]]; then
	echo ""
	toilet -f ${T_FONT} --filter ${T_FILTER} ${DEFAULT_MOTD}
	echo ""
else
	if [[ -f "/proc/device-tree/model" ]]; then
		MODEL=$(tr -d '\0' </proc/device-tree/model)
		FIN="\033[0m"
		echo -e "${B_FONT_STYLE=}"
		figlet ${B_POS} -f ${B_FONT} ${MODEL}
		echo -e "${FIN}"
	fi
fi
