#!/bin/bash

# variables
COL="\033[1m"
FIN="\033[0m"
CPU0=`lscpu | grep "Model name" | sed -n 1p | sed 's/Model name://g' | sed -r '1s/\s+//g'`
CPU0M=`lscpu | grep "CPU max MHz" | sed -n 1p | sed 's/CPU max MHz://g' | sed -r '1s/\s+//g' | sed 's/.0000//g'`
CPU0T=$(cat /sys/class/thermal/thermal_zone0/temp|cut -c1-2)
CPU1=`lscpu | grep "Model name" | sed -n 2p | sed 's/Model name://g' | sed -r '1s/\s+//g'`
CPU1M=`lscpu | grep "CPU max MHz" | sed -n 2p | sed 's/CPU max MHz://g' | sed -r '1s/\s+//g' | sed 's/.0000//g'`
CPU1T=$(cat /sys/class/thermal/thermal_zone1/temp|cut -c1-2)
NETWORK=$(ip -o -4 -br a | grep -v '^lo'| sed 's/^/ /' | sed 's/\/..//' | sed -r '1s/\s+/ /g' | sed -r '2s/\s+/ /g')
ETH0=`echo -e ${COL}Wired:${FIN}`
WLAN0=`echo -e ${COL}Wireless:${FIN}`
USB0=`echo -e ${COL}Tether:${FIN}`

# functions
cpu_hwinfo(){
if [[ `grep -w "0-5" "/sys/devices/system/cpu/present"` ]]; then
	echo -en "${COL}Processors${FIN}: " $CPU0; echo -en " @ $CPU0M"; echo -en "MHz $CPU0T°C";
	echo -en "," $CPU1; echo -en " @ $CPU1M"; echo -e "MHz $CPU1T°C";
else
	echo -en "${COL}Processor${FIN}:  " $CPU0; echo -en " @ $CPU0M"; echo -e "MHz $CPU0T°C";
fi
}

mem_hwinfo(){
meminfo=$(awk '$3=="kB"{if ($2>1024^2){$2=$2/1024^2;$3="GB";} else if ($2>1024){$2=$2/1024;$3="MB";}} 1' /proc/meminfo)
echo "$meminfo" | column -t;
unset meminfo;
}

# display
echo -e "${COL}== DISK${FIN}"
df -h | egrep '(Filesystem)|(/dev/mmc)|(/dev/root)|(/dev/sd)|(/dev/nvme)'
echo ""
echo -e "${COL}== NETWORK${FIN}"
echo -e "${COL}Hostname:${FIN}    $(hostname)"
echo -e "$NETWORK" | sed "s/^[ \t]*//" | sed "s/eth0/$ETH0       eth0/g" | sed "s/wlan0/$WLAN0    wlan0/g" | sed "s/usb0/$USB0      usb0/g"
echo ""
echo -e "${COL}== SYSTEM${FIN}"
if [[ -f "/sys/devices/system/cpu/present" ]]; then
	cpu_hwinfo;
else
	if [[ -f "/sys/class/thermal/thermal_zone0/temp" ]] && [[ -f "/sys/class/thermal/thermal_zone1/temp" ]]; then
		echo -e "${COL}Temperature:${FIN}" $CPU0T°C $CPU1T°C
	else
		echo -e "${COL}Temperature:${FIN}" $CPU0T°C
	fi
	echo -e "${COL}Cores:${FIN}      " $(sudo cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq);
fi
echo -e "${COL}Governor:${FIN}   " $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
if [[ -f "/proc/meminfo" ]]; then
	MEMTOTAL=$(mem_hwinfo | awk '/MemTotal/ {printf "%.2f", $2; print $3}')
	echo -e "${COL}Memory:${FIN}     " $MEMTOTAL
fi
echo -e "${COL}Entropy:${FIN}    " $(cat /proc/sys/kernel/random/entropy_avail)
echo -e "${COL}Uptime:${FIN}     " $(uptime)
