#!/bin/bash
COL="\033[1m"
FIN="\033[0m"
echo -e "${COL}== DISK USAGE${FIN}"
df -h | egrep '(Filesystem)|(/dev/mmc)|(/dev/sd)'
echo ""
echo -e "${COL}== SYSTEM STATUS${FIN}"
echo -e "${COL}CPU Temp:${FIN} " $(cat /sys/class/thermal/thermal_zone0/temp|cut -c1-2)°C
echo -e "${COL}Cores:${FIN}    " $(sudo cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq)
echo -e "${COL}Governor:${FIN} " $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
echo -e "${COL}Uptime:${FIN}   " $(uptime)
