#!/bin/bash

if [ -f /etc/default/dynamic-motd ]; then
	source /etc/default/dynamic-motd;
	if [[ "$MENUCONFIG" == "true" ]]; then
		# menu-config
		source /etc/opt/board.txt
		CBOARD=`echo "$BOARD"| sed -e 's/\(.*\)/\U\1/'`
		echo "";
		echo -e "To configure your $CBOARD run 'menu-config'";
		# run once and disable
		sed -i 's/MENUCONFIG="true"/MENUCONFIG="false"/g' /etc/default/dynamic-motd;
	fi
fi
