#!/bin/bash

if [[ -f "/etc/default/dynamic-motd" ]]; then
	. /etc/default/dynamic-motd
	if [[ "$MENUCONFIG" == "true" ]]; then
		# menu-config
		. /etc/opt/board.txt
		echo ""
		echo -e "To configure ${DEFAULT_MOTD} run 'menu-config'"
		# run once and disable
		sed -i 's/MENUCONFIG="true"/MENUCONFIG="false"/g' /etc/default/dynamic-motd
	fi
fi
