#!/bin/bash

UINITRD="/boot/uInitrd"
INITRD="/boot/initrd.gz"
BCM_INITRD="/boot/broadcom/initrd.gz"

failed (){
echo >&2 "Error: $@"
echo >&2 "uInitrd generation failed - exiting."
exit 1
}

if [[ -f "${UINITRD}" ]]; then rm -f ${UINITRD}; fi

echo "Generating uInitrd for U-Boot:"
if [ "$#" -eq 2 ]; then
	if [ ! -z "$1" ] && [ -f "$2" ]; then
		name="initramfs-$1"
		file="$2"
		mkimage -A arm -O linux -T ramdisk -C gzip -a 0x00000000 -e 0x00000000 -n ${name} -d ${file} ${UINITRD}
	else
		failed
	fi
else
	failed
fi

if [[ -d "/boot" ]]; then
	if [[ `ls  /boot/initrd.img-*` ]] > /dev/null 2>&1; then
		echo "Generating ${INITRD}"
		rm -fr /boot/{initrd.gz,initrd.img-*-bak}
		cp -f /boot/initrd.img-* ${INITRD}
		if [[ -d "/boot/broadcom" ]]; then
			rm -fr /boot/broadcom/{initrd.gz,initrd.img-*-bak}
			cp -f /boot/initrd.img-* ${BCM_INITRD}
		fi
	fi
fi
