#!/bin/bash
# Place file in /etc/initramfs/post-update.d/ and make it executable

# variables
uInitrd="/boot/uInitrd"
initrd="/boot/initrd.gz"
brcmdir="/boot/broadcom"

# functions
failed(){
echo >&2 "Error: $@"
echo >&2 "uInitrd generation failed - exiting."
exit 1
}

# uinitrd
if [ -f ${uInitrd} ]; then
	rm -f ${uInitrd};
fi

echo "Generating uInitrd for U-Boot:"
if [ "$#" -eq 2 ]; then
	if [ ! -z "$1" ] && [ -f "$2" ]; then
		name="initramfs-$1"
		file="$2"
		mkimage -A arm -O linux -T ramdisk -C gzip -a 0x00000000 -e 0x00000000 -n ${name} -d ${file} ${uInitrd};
	else
		failed;
	fi
else
	failed;
fi

# initrd.gz
echo "Creating initrd.gz."
rm -f /boot/{initrd.gz,initrd.img-*-bak}
cp -f /boot/initrd.img-* ${initrd}

# raspberry pi
if [ -d ${brcmdir} ]; then
	cp -f ${initrd} ${brcmdir}/;
fi
