#!/bin/bash
# UEFI/GRUB post update file management

DISTRO=`cat /etc/os-release | grep -w NAME | sed 's/NAME=//g' | sed 's/"//g' | sed 's/ GNU\/Linux//g'`
ROOTFS_LABEL=`echo "${DISTRO}" | sed -e 's/.*/\U&/'`
EFI_BOOT="BOOTAA64"
if [[ -f "/etc/opt/board.txt" ]]; then . /etc/opt/board.txt; else exit 0; fi
if [[ "$FSTYPE" == "ext4" ]]; then
	FSMOD="ext2"
	ROOT_FSTYPE="rootfstype=ext4"
	CMDLINE="linux (hd0,2)/boot/Image ${CONSOLE} rw root=LABEL=${ROOTFS_LABEL} rootwait ${ROOT_FSTYPE} fsck.repair=yes ${LOGLEVEL} ${EXTRA}"
	INITRD="initrd (hd0,2)/boot/initrd.gz"
elif [[ "$FSTYPE" == "btrfs" ]]; then
	FSMOD="btrfs"
	ROOT_FSTYPE="rootfstype=btrfs rootflags=subvol=@"
	CMDLINE="linux (hd0,2)/@/boot/Image ${CONSOLE} rw root=LABEL=${ROOTFS_LABEL} rootwait ${ROOT_FSTYPE} fsck.repair=yes ${LOGLEVEL} ${EXTRA}"
	INITRD="initrd (hd0,2)/@/boot/initrd.gz"
elif [[ "$FSTYPE" == "xfs" ]]; then
	FSMOD="xfs"
	ROOT_FSTYPE="rootfstype=xfs"
	CMDLINE="linux (hd0,2)/boot/Image ${CONSOLE} rw root=LABEL=${ROOTFS_LABEL} rootwait ${ROOT_FSTYPE} fsck.repair=yes ${LOGLEVEL} ${EXTRA}"
	INITRD="initrd (hd0,2)/boot/initrd.gz"
fi

default_cfg(){
if [[ "$GPT" == "true" ]]; then PTYPE="gpt"; else PTYPE="msdos"; fi
cat <<EOF > /etc/opt/grub.cfg
set timeout=0
set default=0
menuentry "${DEFAULT_MOTD}" {
	insmod gzio
	insmod part_${PTYPE}
	insmod ${FSMOD}
	set root=hd0,${PTYPE}1
	echo "Loading kernel ..."
	${CMDLINE}
	echo "Loading ramdisk ..."
	${INITRD}
}
EOF
}

if [[ ! -f "/etc/opt/grub.cfg" ]]; then default_cfg; fi
if [[ -d "/boot/efi" ]]; then
	mkdir -p /boot/efi/EFI/BOOT
	if [[ -f "/boot/efi/EFI/BOOT/${EFI_BOOT}.EFI" ]]; then
		rm -f /boot/efi/EFI/BOOT/${EFI_BOOT}.BAK
		mv -f /boot/efi/EFI/BOOT/${EFI_BOOT}.EFI /boot/efi/EFI/BOOT/${EFI_BOOT}.BAK
	fi
	grub-mkstandalone -O ${ARCH}-efi -o /boot/efi/EFI/BOOT/${EFI_BOOT}.EFI "/boot/grub/grub.cfg=/etc/opt/grub.cfg"
fi

exit 0
