#!/bin/bash

if [[ -f "/etc/opt/board.txt" ]]; then
	source /etc/opt/board.txt
else
	exit 0
fi

grub_cfg(){
CBOARD=`echo "$BOARD" | sed -e 's/\(.*\)/\U\1/'`
cat <<EOF > /etc/opt/grub.cfg
set timeout=0
set default=0
menuentry $CBOARD {
	insmod gzio
	insmod part_msdos
	insmod ext2
	set root=hd0,msdos1
	echo Loading kernel ...
	linux /Image root=LABEL=ROOTFS ${CONSOLE} rw rootwait rootfstype=ext4 fsck.repair=yes loglevel=1 ${EXTRA}
	echo Loading ramdisk ...
	initrd /initrd.gz
}
EOF
}

if [[ -f "/etc/opt/grub.cfg" ]]; then
	:;
else
	grub_cfg > /dev/null 2>&1;
fi

if [[ -d "/boot/efi" ]]; then
	mkdir -p /boot/efi/dtb/${FAMILY}
	mkdir -p /boot/efi/EFI/BOOT
	if [[ -f "/boot/efi/Image" ]]; then
		rm -f /boot/efi/Image;
	fi
	if [[ -f "/boot/efi/initrd.gz" ]]; then
		rm -f /boot/efi/initrd.gz;
	fi
	cp -fr /boot/{Image,initrd.gz} /boot/efi/
	rm -f /boot/efi/dtb/${FAMILY}/*.dtb
	cp -fr /boot/${FAMILY}/*.dtb /boot/efi/dtb/${FAMILY}/
	grub-mkstandalone -O arm64-efi -o /boot/efi/EFI/BOOT/BOOTAA64.EFI "/boot/grub/grub.cfg=/etc/opt/grub.cfg"
fi
