#!/bin/bash

#set -x

reset_bt (){
sleep .50
killall hciattach
sleep .50
hciattach -s 1500000 /dev/ttyS1 any 1500000 flow nosleep > /dev/null 2>&1
rfkill unblock all
}

sleep 10
if [[ `hciconfig | grep -w "DOWN"` ]]; then reset_bt; fi

exit 0
