#!/bin/bash
# Description: Amlogic Mixer Settings
# Destination: /usr/local/bin/amlmixer

if [[ "$USER" == "root" ]]; then
	:;
else
	if [[ `command -v sudo` ]]; then
		export LANG=$LANG:C
		if [[ $EUID -ne 0 ]]; then
			sudo "$0" "$@" 
			exit
		fi
	else
		echo "Please run this as root or with sudo privileges."
		exit 0
	fi
fi
if [[ `command -v amixer` ]]; then
	:;
else
	if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
		apt update
		apt install alsa-utils -y
	else
		echo -e "Missing depends: alsa-utils"
		exit 0
	fi
fi

warning (){
WARNING_MSG="Argument is not supported."
echo -e "$WARNING_MSG"
exit 0
}

if [[ -f "/etc/opt/board.txt" ]]; then
	. /etc/opt/board.txt
else
	warning
fi
if [[ "$SERIES" == "meson-g12a" || "$SERIES" == "meson-g12b" || "$SERIES" == "meson-sm1" ]]; then
	:;
else
	warning
fi

if [[ "$FAMILY_EXT" == "bananapi" || "$FAMILY_EXT" == "odroid" || "$BOARD" == "radxazero" || "$BOARD" == "x96air" ]]; then
	HDMI_AUDIO=1
else
	HDMI_AUDIO=0
fi
if [[ "$BOARD" == "odroidn2" || "$BOARD" == "odroidn2plus" || "$BOARD" == "bananapim5" || "$BOARD" == "x96air" ]]; then
	JACK_AUDIO=1
else
	JACK_AUDIO=0
fi
if [[ "$BOARD" == "x96air" ]]; then
	SPDIF_AUDIO=1
else
	SPDIF_AUDIO=0
fi

analog(){
if [ $JACK_AUDIO -eq 1 ]; then
	amixer -c 0 set 'TOACODEC OUT EN' 'on'
	amixer -c 0 set 'TOACODEC SRC' 'I2S B'
	amixer -c 0 set 'TDMOUT_B SRC SEL' 'IN 0'
	amixer -c 0 set 'FRDDR_A SRC 2 EN' 'on'
	amixer -c 0 set 'FRDDR_A SINK 1 SEL' 'OUT 0'
	amixer -c 0 set 'FRDDR_A SINK 2 SEL' 'OUT 1'
	amixer -c 0 set 'FRDDR_A SINK 3 SEL' 'OUT 2'
	amixer -c 0 set 'ACODEC' '85%'
	alsactl store
else
	warning
fi
}

hdmi(){
if [ $HDMI_AUDIO -eq 1 ]; then
	amixer -c 0 set 'TOHDMITX' 'on'
	amixer -c 0 set 'TOHDMITX I2S SRC' 'I2S B'
	amixer -c 0 set 'TDMOUT_B SRC SEL' 'IN 0'
	amixer -c 0 set 'FRDDR_A SRC 2 EN' 'on'
	amixer -c 0 set 'FRDDR_A SINK 1 SEL' 'OUT 0'
	amixer -c 0 set 'FRDDR_A SINK 2 SEL' 'OUT 1'
	amixer -c 0 set 'FRDDR_A SINK 3 SEL' 'OUT 2'
	if [[ "$BOARD" == "odroidn2" || "$BOARD" == "odroidn2l" || "$BOARD" == "odroidn2plus" || \
		"$BOARD" == "bananapim5" || "$BOARD" == "x96air" ]]; then
		amixer -c 0 set 'ACODEC' '85%'
	fi
	alsactl store
else
	warning
fi
}

spdif(){
if [ $SPDIF_AUDIO -eq 1 ]; then
	amixer -c 0 set 'TOHDMITX' 'on'
	amixer -c 0 set 'TOHDMITX I2S SRC' 'I2S B'
	amixer -c 0 set 'TDMOUT_B SRC SEL' 'IN 0'
	amixer -c 0 set 'FRDDR_A SRC 2 EN' 'on'
	amixer -c 0 set 'FRDDR_A SRC 3 EN' 'on'
	amixer -c 0 set 'FRDDR_A SINK 1 SEL' 'OUT 0'
	amixer -c 0 set 'FRDDR_A SINK 2 SEL' 'OUT 1'
	amixer -c 0 set 'FRDDR_A SINK 3 SEL' 'OUT 3'
	amixer -c 0 set 'SPDIFOUT_A SRC SEL' 'IN 0'
	amixer -c 0 set 'ACODEC' '85%'
	alsactl store
else
	warning
fi
}

if [ $# -eq 0 ]; then
	>&2 echo -e "Arguments: hdmi analog spdif"
	exit 1
fi
case $1 in
	hdmi|analog|spdif)
	;;
	*)
	echo -e "Arguments: hdmi analog spdif" >&2
	exit 1
esac
AMLMIXER=`echo $1`
$AMLMIXER

exit 0
