#!/bin/bash
# Description: BananaPi CM4 Waveshare Fan Control
# Destination: /usr/local/bin/bpi-fanctrl
# Source: https://gist.github.com/geerlingguy/9c9c78463c0e3d9f4a23152912930821

if [[ -f "/etc/default/bpi-fanctrl" ]]; then
	. /etc/default/bpi-fanctrl
else
	echo 'ENABLE="false"' > /etc/default/bpi-fanctrl
	echo 'TRIP_POINT="55"' >> /etc/default/bpi-fanctrl
	sleep 1
	. /etc/default/bpi-fanctrl
fi

fan_control (){
# trip point (celcius) 
TEMP_THRESHOLD="${TRIP_POINT}"
TEMP_COMPARE=$(($TEMP_THRESHOLD * 1000))
# minimum speed (0-255) 
MIN_FAN_SPEED="0"
MIN_FAN_SPEED_HEX=$(printf "0x%02x" "$MIN_FAN_SPEED")
# maximum speed (0-255) 
MAX_FAN_SPEED="255"
MAX_FAN_SPEED_HEX=$(printf "0x%02x" "$MAX_FAN_SPEED")
while true; do
	# current temperature 
	CURRENT_TEMP=$(cat /sys/class/thermal/thermal_zone1/temp)
	if [ $CURRENT_TEMP -ge $TEMP_COMPARE ]; then
		# set fan to maximum speed
		i2cset -y 0 0x2f 0x30 $MAX_FAN_SPEED_HEX
	else
		# set fan to minimum speed 
		i2cset -y 0 0x2f 0x30 $MIN_FAN_SPEED_HEX
	fi
	sleep 10
done
}

if [[ "$ENABLE" == "true" ]]; then fan_control; else exit 0; fi
