#!/bin/bash

# Functions
rtl88x2bu () {
mkdir -p ~/.build
cd ~/.build
echo
echo Checking for dkms.
sudo apt update
sudo apt install dkms -y
echo
echo Fetching . . . rtl88x2bu.
git clone https://github.com/cilynx/rtl88x2bu.git
cd rtl88x2bu
VER=$(sed -n 's/\PACKAGE_VERSION="\(.*\)"/\1/p' dkms.conf)
sudo rsync -rvhP ./ /usr/src/rtl88x2bu-${VER}
sudo dkms add -m rtl88x2bu -v ${VER}
sudo dkms build -m rtl88x2bu -v ${VER}
sudo dkms install -m rtl88x2bu -v ${VER}
sudo modprobe 88x2bu
sudo rm -fdr ~/.build/*
echo Done.
}

rtl8812au () {
mkdir -p ~/.build
cd ~/.build
echo
echo Checking for dkms.
sudo apt update
sudo apt install dkms -y
echo
echo Fetching . . . rtl8812au.
git clone https://github.com/aircrack-ng/rtl8812au.git
cd rtl8812au
sudo ./dkms-install.sh
sudo rm -fdr ~/.build/*
echo Done.
}

# Commands
if [ $# -eq 0 ]
then
        echo "Missing options!"
        echo "(run $0 -h for help)"
        echo ""
        exit 0
fi

ECHO="false"

while getopts "he12" OPTION; do
        case $OPTION in

                1)
                        ECHO="rtl88x2bu"
                        ;;
                2)
                        ECHO="rtl8812au"
                        ;;

                h)
                        echo "Usage: Build Wifi Drivers"
                        echo ""
                        echo "   1) rtl88x2bu"
                        echo "   2) rtl8812au"
                        echo ""
                        exit 0
                        ;;

        esac
done

if [ $ECHO = "rtl88x2bu" ]
then
        rtl88x2bu;
fi
if [ $ECHO = "rtl8812au" ]
then
        rtl8812au;
fi
