#!/bin/bash
# Frequencies: 144000 312000 528000 720000 864000 912000 960000 overclock: 1008000 1056000 1104000 1152000 1200000
if [[ -f "/etc/opt/overclock.txt" ]]; then
	. /etc/opt/overclock.txt
else
	echo "overclock=0" > /etc/opt/overclock.txt
	. /etc/opt/overclock.txt
fi

DF="1008000"
OC="1152000"

if [[ -f "/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq" ]] && [[ -f "/sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq" ]]; then
	if [ $overclock -eq 1 ]; then
		echo "$OC" | tee /sys/devices/system/cpu/cpu{0,1}/cpufreq/scaling_max_freq;
	else
		echo "$DF" | tee /sys/devices/system/cpu/cpu{0,1}/cpufreq/scaling_max_freq;
	fi
fi

exit 0
