#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

BOOT=`findmnt -v -n -o SOURCE /boot`
ROOTFS=`findmnt -v -n -o SOURCE /`
GROW_SD=`findmnt -v -n -o SOURCE / | sed 's/./& /8'`
GROW_MMC=`findmnt -v -n -o SOURCE / | sed 's/p/ /'`

# Functions
partition_uuid(){
echo 'ROOT_PARTUUID="' > root1
blkid -o export -- $ROOTFS | sed -ne 's/^PARTUUID=//p' > root2
echo '"' > root3
paste -d '\0' root1 root2 root3  > /etc/opt/root-pid.txt
rm -f root1 root2 root3
}

extlinux(){
source /etc/opt/root-pid.txt > /dev/null 2>&1
source /etc/opt/board.txt > /dev/null 2>&1
FDT="../${FAMILY}/${DTB}.dtb"
FDTDIR="../${FAMILY}/"
CMDLINE="append earlyprintk ${CONSOLE} rw root=PARTUUID=${ROOT_PARTUUID} rootwait rootfstype=ext4 fsck.repair=yes ${EXTRA} loglevel=1 init=/sbin/init"
rm -f /boot/extlinux/extlinux.conf
tee /boot/extlinux/extlinux.conf <<EOF
label default
	kernel ../Image
	initrd ../uInitrd
	fdtdir ${FDTDIR}
	fdt ${FDT}
	#fdtoverlays
	${CMDLINE}
EOF
rm -f /etc/opt/root-pid.txt
}

# Expand root filesystem
if [[ `grep -w "Devuan" "/etc/os-release"` ]]; then
	echo "";
	echo -e " \e[0;31mExpanding root filesystem\e[0m ...";
fi
if [[ `findmnt -v -n -o SOURCE / | grep "mmc"` ]]; then
	bash growpart $GROW_MMC > /dev/null 2>&1;
fi
if [[ `findmnt -v -n -o SOURCE / | grep "sd"` ]]; then
	bash growpart $GROW_SD > /dev/null 2>&1;
fi
sleep 1s
resize2fs $ROOTFS > /dev/null 2>&1

# Fix PARTUUID
if [[ `grep -w 'ARCH="arm"' "/etc/opt/board.txt"` ]]; then
	partition_uuid > /dev/null 2>&1;
	extlinux > /dev/null 2>&1;
fi

# Fsck boot partition
if [[ `findmnt -v -n /boot | grep -w "vfat"` ]]; then
	umount /boot;
	sleep 1s;
	bash fsck.fat -trawl $BOOT > /dev/null 2>&1;
	sleep 1s;
	mount /boot;
fi

### Clean up
if [[ `grep -w "Devuan" "/etc/os-release"` ]]; then
	update-rc.d firstboot remove;
	rm -f /etc/init.d/firstboot;
else
	systemctl disable firstboot;
fi
rm -f /var/cache/debconf/*
rm -f /usr/local/sbin/firstboot

exit 0
