#!/bin/bash
# Need to restart auto-negotiation on ethernet

sleep 20s

eth_reset(){
ifconfig eth0 down
sleep 2s
ifconfig eth0 up
sleep 10s
ethtool -r eth0
}

if grep "1" /sys/class/net/eth0/carrier > /dev/null 2>&1;
        then eth_reset;
fi
