#!/bin/bash

get_device_irq(){
	local device="$1"
	local line=$(grep -m 1 "${device}\$" /proc/interrupts)
	echo ${line} | sed 's/:.*//'
}

set_interface_core(){
	local core_mask="$1"
	local interface="$2"
	local device="$3"

	[ -z "${device}" ] && device="$interface"

	local irq=$(get_device_irq "$device")
	[ -z "$irq" ] && return 0

	echo -n "${core_mask}" > /proc/irq/${irq}/smp_affinity
}

MACADDR=$(echo $FQDN|md5sum|sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/02:\1:\2:\3:\4:\5/')
if [[ -e "/sys/class/net/eth0" ]]; then
	ip link set dev eth0 address $MACADDR
fi
if [[ -e "/sys/class/net/eth1" ]]; then
	ip link set dev eth1 address $MACADDR
fi
if [[ -e "/sys/class/net/eth2" ]]; then
	ip link set dev eth2 address $MACADDR
fi

set_interface_core 8 "eth0"
echo f > /sys/class/net/eth0/queues/rx-0/rps_cpus
set_interface_core 4 "eth1-0"
set_interface_core 4 "eth1-16"
set_interface_core 4 "eth1-18"
echo b > /sys/class/net/eth1/queues/rx-0/rps_cpus
set_interface_core 2 "eth2-0"
set_interface_core 2 "eth2-16"
set_interface_core 2 "eth2-18"
echo d > /sys/class/net/eth2/queues/rx-0/rps_cpus

exit 0
