#!/bin/bash

turbo-mode(){
if [[ `grep -w "overclock=1" "/etc/opt/overclock.txt"` ]]; then
	echo "1" > /sys/devices/system/cpu/cpufreq/boost;
else
	:;
fi
}

if [ -e /sys/devices/system/cpu/cpufreq/boost ]; then
	turbo-mode;
fi
