#!/bin/bash

USB3_IRQ=`cat /proc/interrupts | grep "xhci-hcd:usb1" | awk -F : '{print $1}' | sed s/" "//g`
echo 4 > /proc/irq/${USB3_IRQ}/smp_affinity_list

sleep 20
ETHER=`cat /proc/interrupts | grep "eth0" | awk -F : '{print $1}' | sed s/" "//g`
echo 5 > /proc/irq/${ETHER}/smp_affinity_list

if [ -f /sys/class/net/eth0/queues/rx-0/rps_cpus ]; then
	echo f > /sys/class/net/eth0/queues/rx-0/rps_cpus
fi
