#!/bin/bash

source /etc/opt/overclock.txt

if [ $overclock -eq 1 ]; then
	if [[ -f "/sys/devices/system/cpu/cpufreq/boost" ]]; then
		echo "1" > /sys/devices/system/cpu/cpufreq/boost;
		governor -r;
	else
		echo "0" > /sys/devices/system/cpu/cpufreq/boost;
	fi
fi
