#!/bin/bash

turbo-mode(){
if [[ `grep -w "overclock=1" "/etc/opt/overclock.txt"` ]]; then
	echo "1" > /sys/devices/system/cpu/cpufreq/boost;
else
	echo "0" > /sys/devices/system/cpu/cpufreq/boost;
fi
}

if [ -e /sys/devices/system/cpu/cpufreq/boost ]; then
	turbo-mode;
	governor -r > /dev/null 2>&1;
fi
