#!/bin/bash
source /etc/opt/board.txt
WHT="\033[1m"
FIN="\033[0m"

hdmi-audio(){
echo "Running Setup ..."
sudo amixer sset 'FRDDR_A SINK 1 SEL' 'OUT 1'
sudo amixer sset 'FRDDR_A SRC 1 EN' 'on'
sudo amixer sset 'TDMOUT_B SRC SEL' 'IN 0'
sudo amixer sset 'TOHDMITX I2S SRC' 'I2S B'
sudo amixer sset 'TOHDMITX' 'on'
sudo amixer sset 'FRDDR_B SINK 1 SEL' 'OUT 2'
sudo amixer sset 'FRDDR_B SRC 1 EN' 'on'
sudo amixer sset 'FRDDR_C SINK 1 SEL' 'OUT 3'
sudo amixer sset 'FRDDR_C SRC 1 EN' 'on'
sudo alsactl store
echo "Done."
echo ""
}

confirm(){
echo -e "${WHT}Setup Audio ..?${FIN}"
echo -e ""
read -p "Continue (y/n)?" choice
case "$choice" in 
  y|Y ) echo ""; hdmi-audio;;
  n|N ) echo && echo -e "Skipping setup ..."; echo "";;
  * ) echo && echo -e "Invalid choice."; echo ""; confirm;;
esac
}

if [ $# -eq 0 ]; then
	echo -e "\e[0;31mMissing options!${FIN}";
	echo "(run $0 -h for help)";
	echo "";
	exit 0;
fi

while getopts "rh" OPTION; do
	case $OPTION in

		r)
			echo ""
			echo -e "${WHT}Running System Setup${FIN} ..."
			sleep 1s
			sudo dpkg-reconfigure locales tzdata keyboard-configuration
			sleep 1s
			if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
				echo "";
				echo "Preparing tasksel ...";
				if [[ `command -v tasksel` ]]; then
					:;
				else
					sudo apt update;
					sudo apt install -y tasksel;
				fi
				sleep 1s;
				sudo apt-get update;
				sudo apt-get install --reinstall debconf;
				sudo dpkg-reconfigure tasksel;
				echo "Done.";
				echo "";
			fi
			sleep 1s
			if [[ "$BOARD" == "radxazero" ]]; then
				confirm;
			fi
			if [[ "$FAMILY_EXT" == "odroid" ]]; then
				confirm;
			fi
			if [ -f /etc/motd ]; then
				sudo rm -f /etc/motd;
				sudo touch /etc/motd;
			fi
			sleep 1s
			sudo update-ca-certificates -f
			echo ""
			echo -e "${WHT}System is ready to go${FIN}."
			if [ -f /usr/local/bin/setup ]; then
				sudo rm -f /usr/local/bin/setup;
			fi
			exit 0
			;;
		h)                       
			echo ""
			echo -e "   -r        Run"
			echo ""
			exit 0
			;;
	esac
done
exit 0
