#!/bin/bash
if [[ -f "/etc/opt/board.txt" ]]; then
	. /etc/opt/board.txt
fi
if [[ -f "/etc/os-release" ]]; then
	NAME=`cat /etc/os-release | grep -w 'NAME=' | sed 's/NAME="//g' | sed 's/"//g'`
else
	NAME="none"
fi

audio_mixer(){
sudo amixer sset 'FRDDR_A SINK 1 SEL' 'OUT 1'
sudo amixer sset 'FRDDR_A SRC 1 EN' 'on'
sudo amixer sset 'TDMOUT_B SRC SEL' 'IN 0'
sudo amixer sset 'TOHDMITX I2S SRC' 'I2S B'
sudo amixer sset 'TOHDMITX' 'on'
sudo amixer sset 'FRDDR_B SINK 1 SEL' 'OUT 2'
sudo amixer sset 'FRDDR_B SRC 1 EN' 'on'
sudo amixer sset 'FRDDR_C SINK 1 SEL' 'OUT 3'
sudo amixer sset 'FRDDR_C SRC 1 EN' 'on'
sudo alsactl store
echo "Done."
echo ""
}

confirm(){
echo -e "Setup audio ..?"
echo -e ""
read -p "Continue (y/n)?" choice
case "$choice" in 
	y|Y ) echo ""; audio_mixer;;
	n|N ) echo && echo -e "Skipping audio setup ..."; echo "";;
	* ) echo && echo -e "Invalid choice."; echo ""; confirm;;
esac
}

if [ $# -eq 0 ]; then
	echo -e "Missing options!"
	echo "(run $0 -h for help)"
	echo ""
	exit 0
fi

while getopts "rh" OPTION; do
	case $OPTION in

		r)
			echo ""
			echo -e "Running system setup ..."
			sleep .75
			sudo dpkg-reconfigure locales tzdata keyboard-configuration
			sleep .50
			if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
				if [[ "$NAME" == "Ubuntu" ]]; then echo ""; fi
				echo "Configuring tasksel ..."
				if [[ `command -v tasksel` ]]; then
					:;
				else
					sudo apt update
					sudo apt install -y tasksel
				fi
				sleep .75
				sudo apt-get update
				sudo apt-get install --reinstall debconf
				sudo dpkg-reconfigure tasksel
				echo "Done."
				echo ""
			fi
			sleep .50
			if [[ -f "/etc/opt/board.txt" ]]; then
				if [[ "$BOARD" == "radxazero" || "$FAMILY_EXT" == "odroid" ]]; then
					confirm
				fi
			fi
			sleep .50
			sudo update-ca-certificates -f
			echo ""
			echo -e "Setup complete."
			exit 0
			;;
		h)
			echo -e ""
			echo -e "	-r	Run"
			echo ""
			exit 0
			;;
	esac
done

exit 0
