#!/bin/bash
FREE_DATA=`free -m | grep Mem` 
CURRENT=`echo $FREE_DATA | cut -f3 -d' '`
TOTAL=`echo $FREE_DATA | cut -f2 -d' '`

echo
figlet -f small "System Monitor" -c
echo
echo -e "CPU:      " `top -b -n1 | grep "Cpu(s)" | awk '{print $2 + $4}'` 
echo -e "CPU Temp: " $(cat /sys/class/thermal/thermal_zone0/temp|cut -c1-2)°C
echo -e "Cores:    " $(sudo cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq)
echo -e "RAM:      " $(echo "scale = 2; $CURRENT/$TOTAL*100" | bc)
echo -e "Governor: " $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
echo -e "Uptime:   " $(uptime)
echo

