#!/bin/bash
echo
figlet -f small "System Monitor" -c
echo
echo -e "CPU Temp: " $(cat /sys/class/thermal/thermal_zone0/temp|cut -c1-2)°C
echo -e "Cores:    " $(sudo cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq)
echo -e "Governor: " $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
echo -e "Uptime:   " $(uptime)
echo
