#!/bin/bash

while ! [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]
do
	sleep 1
done

if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
	echo "setup" > /sys/class/leds/openvfd/led_on
fi

exit 0
