#!/bin/bash
# BPI-M4ZERO LED TRIGGER

RED_LED="/sys/class/leds/red:status/trigger"
if [ -f "${RED_LED}" ]; then
	ROOT_DEVICE=`findmnt -v -n -o SOURCE /`
	ROOT_DEVICE=${ROOT_DEVICE/\/dev\//}
	ROOT_DEVICE=${ROOT_DEVICE/mmcblk/mmc}
	ROOT_DEVICE=${ROOT_DEVICE/p[0-9]/}
	echo -n "$ROOT_DEVICE" > $RED_LED
fi

exit 0
