#!/bin/bash
# Bind root device activity to Linux kernel LED trigger

RED_LED="/sys/class/leds/imx6:red:front/trigger"
if [[ -f "$RED_LED" ]]; then
	ROOT_DEVICE=`findmnt -v -n -o SOURCE /`
	ROOT_DEVICE=${ROOT_DEVICE/\/dev\//}
	ROOT_DEVICE=${ROOT_DEVICE/mmcblk/mmc}
	ROOT_DEVICE=${ROOT_DEVICE/p[0-9]/}
	echo -n "$ROOT_DEVICE" > $RED_LED
fi
