#!/bin/bash
# Bind root device activity to Linux kernel LED trigger
# Stop blue LED from blinking

GREEN_LED="/sys/class/leds/librecomputer:system-status/trigger"
if [ -e $GREEN_LED ]; then
        ROOT_DEVICE=`findmnt -v -n -o SOURCE /`
        ROOT_DEVICE=${ROOT_DEVICE/\/dev\//}
        ROOT_DEVICE=${ROOT_DEVICE/mmcblk/mmc}
        ROOT_DEVICE=${ROOT_DEVICE/p[0-9]/}
        echo -n "$ROOT_DEVICE" > $GREEN_LED
fi

BLUE_LED="/sys/class/leds/librecomputer:blue/brightness"
if [ -e $BLUE_LED ]; then
        echo 1 > $BLUE_LED
        sleep 2s
        echo 0 > $BLUE_LED
fi
