#!/bin/bash
# bind blue led to root (default)
# blue led off


if [ -f /sys/class/leds/c1:blue:alive/trigger ]; then
	LED="c1:blue:alive";
fi
if [ -f /sys/class/leds/blue:status/trigger ]; then
	LED="blue:status";
fi
if [ -f /sys/class/leds/n2:blue/trigger ]; then
	LED="n2:blue";
fi
if [ -f /sys/class/leds/blue:heartbeat/trigger ]; then
	LED="blue:heartbeat";
fi

activity(){
BLUE_LED="/sys/class/leds/${LED}/trigger"
if [ -e $BLUE_LED ]; then
	ROOT_DEVICE=`findmnt -v -n -o SOURCE /`
	ROOT_DEVICE=${ROOT_DEVICE/\/dev\//}
	ROOT_DEVICE=${ROOT_DEVICE/mmcblk/mmc}
	ROOT_DEVICE=${ROOT_DEVICE/p[0-9]/}
	echo -n "$ROOT_DEVICE" > $BLUE_LED
fi
}

off(){
if [ -f /sys/class/leds/${LED}/brightness ]; then
	echo "0" > /sys/class/leds/${LED}/brightness;
fi
}

activity
#off
