#!/bin/bash
# Bind root device activity to blue LED trigger
# Turn blue LED off (default)

activity(){
BLUE_LED="/sys/class/leds/blue:status/trigger"
if [ -e $BLUE_LED ]; then
        ROOT_DEVICE=`findmnt -v -n -o SOURCE /`
        ROOT_DEVICE=${ROOT_DEVICE/\/dev\//}
        ROOT_DEVICE=${ROOT_DEVICE/mmcblk/mmc}
        ROOT_DEVICE=${ROOT_DEVICE/p[0-9]/}
        echo -n "$ROOT_DEVICE" > $BLUE_LED
fi
}

off(){
echo 0 > /sys/class/leds/blue:status/brightness
}

#activity
off
