#!/bin/bash
# Bind root device activity to the status LED trigger
# Turn off power LED

RED_LED="/sys/class/leds/orangepi:red:status/trigger"
if [ -e $RED_LED ]; then
	ROOT_DEVICE=`findmnt -v -n -o SOURCE /`
	ROOT_DEVICE=${ROOT_DEVICE/\/dev\//}
	ROOT_DEVICE=${ROOT_DEVICE/mmcblk/mmc}
	ROOT_DEVICE=${ROOT_DEVICE/p[0-9]/}
	echo -n "$ROOT_DEVICE" > $RED_LED
fi

GREEN_LED="/sys/class/leds/orangepi:green:pwr/brightness"
if [ -e $GREEN_LED ]; then
	echo "0" > $GREEN_LED
fi
