#!/bin/bash
# Bind root device activity to Linux ACT LED trigger
# Turn off PWR LED

GREEN_LED="/sys/class/leds/ACT/trigger"
if [ -e $GREEN_LED ]; then
	ROOT_DEVICE=`findmnt -v -n -o SOURCE /`
	ROOT_DEVICE=${ROOT_DEVICE/\/dev\//}
	ROOT_DEVICE=${ROOT_DEVICE/mmcblk/mmc}
        ROOT_DEVICE=${ROOT_DEVICE/p[0-9]/}
	echo -n "$ROOT_DEVICE" > $GREEN_LED
fi

RED_LED="/sys/class/leds/PWR/brightness"
if [ -e $RED_LED ]; then
	echo "0" > $RED_LED
fi
