#!/bin/bash
# Bind root device activity to Linux kernel LED trigger
# Stop red LED from blinking

GREEN_LED="/sys/class/leds/firefly:yellow:user/trigger"
if [ -e $GREEN_LED ]; then
	ROOT_DEVICE=`findmnt -v -n -o SOURCE /`
	ROOT_DEVICE=${ROOT_DEVICE/\/dev\//}
	ROOT_DEVICE=${ROOT_DEVICE/mmcblk/mmc}
	ROOT_DEVICE=${ROOT_DEVICE/p[0-9]/}
	echo -n "$ROOT_DEVICE" > $GREEN_LED
fi

RED_LED="/sys/class/leds/firefly:blue:power/brightness"
if [ -e $RED_LED ]; then
	echo "0" > $RED_LED
fi
