#!/bin/bash

if [ -f /sys/class/leds/standby/brightness ]; then
	LED="standby";
fi
if [ -f /sys/class/leds/led-1/brightness ]; then
	LED="led-1"
fi

if [ -f /sys/class/leds/${LED}/brightness ]; then
        echo "0" > /sys/class/leds/${LED}/brightness;
fi

exit 0
