#!/bin/bash
# led trigger
if [ -e /sys/class/leds/standby/brightness ]; then
        echo 0 > /sys/class/leds/standby/brightness;
else
        if [ -e /sys/class/leds/led-1/brightness ]; then
                echo 0 > /sys/class/leds/led-1/brightness;
        fi
fi
