#!/bin/bash
# Tinker Board RK3288

ORANGE_LED="/sys/class/leds/led-1/trigger"
RED_LED="/sys/class/leds/led-2/trigger"
if [ -e $ORANGE_LED ]; then
	if [[ `ls /dev/sd*[!0-9]` ]] > /dev/null 2>&1; then
		:;
	else
		sleep 1.90; echo "none" > $ORANGE_LED
	fi
fi
if [ -e $RED_LED ]; then
	echo "none" > $RED_LED
fi

exit 0

