#!/bin/bash
RED="\e[1;31m"
GRN="\e[1;32m"
PNK="\e[1;35m"
WHT="\e[1;37m"
YLW="\e[1;33m"
FIN="\e[0m"

echo_nok(){
echo -e -n "${PNK}[${FIN}${GRN}OK${FIN}${PNK}]${FIN}"
}

echo_jammy(){
echo -e -n "${PNK}[${FIN}${GRN}Ubuntu Jammy Jellyfish${FIN}${PNK}]${FIN}"
}

echo_bullseye(){
echo -e -n "${PNK}[${FIN}${GRN}Debian Bullseye${FIN}${PNK}]${FIN}"
}

echo_fail(){
echo -n -e "${PNK}[${FIN}${RED}failed${FIN}${PNK}]${FIN}"
}

ierror(){
echo
echo -e "${WHT}Please check your internet connection and try again${FIN}."
}

derror(){
echo
echo -e "${WHT}The OS you are running is not supported${FIN}."
}

internet_check(){
echo -en "${WHT}Checking Internet Connection:${FIN} "
if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
	echo_nok;
	echo "";
else
	echo_fail;
	echo "";
	ierror;
	exit 0;
fi
}

distro_check(){
echo -en "${WHT}Checking Host Machine:${FIN} "
sleep 1s
if [[ `grep -w "jammy" "/etc/os-release"` ]]; then
	echo_jammy;
	echo "";
else
	if [[ `grep -w "bullseye" "/etc/os-release"` ]]; then
		echo_bullseye;
		echo "";
	else
		echo_fail;
		echo "";
		derror;
		exit 0;
	fi
fi
}

echo ""
internet_check
distro_check
echo ""
echo -e "${WHT}Starting install${FIN} ..."
sleep 1s
if [[ `uname -m | grep x86_64` ]]; then
	if [[ `command -v make` ]]; then
		sudo apt update;
		sudo apt upgrade -y;
		make ccompile;
	else
		sudo apt update;
		sudo apt upgrade -y;
		sudo apt install -y make;
		make ccompile;
	fi
fi
if [[ `uname -m | grep aarch64` ]]; then
	if [[ `command -v make` ]]; then
		sudo apt update;
		sudo apt upgrade -y;
		make ncompile;
	else
		sudo apt update;
		sudo apt upgrade -y;
		sudo apt install -y make;
		make ncompile;
	fi
fi
make dialogrc > /dev/null 2>&1
echo ""
make
exit 0
