#!/bin/bash

RED="\e[0;31m"
GRN="\e[0;32m"
PNK="\e[0;35m"
TXT="\033[0m"
YLW="\e[0;33m"
FIN="\e[0m"

echo ""
echo -en "${TXT}Checking Internet Connection:${FIN} "
if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
	echo -en "${PNK}[${FIN}${GRN}OK${FIN}${PNK}]${FIN}";
	echo "";
else
	echo -en "${PNK}[${FIN}${RED}failed${FIN}${PNK}]${FIN}";
	echo "";
	echo -e "${TXT}Please check your internet connection and try again${FIN}.";
	exit 0;
fi
echo -en "${TXT}Checking Host Machine:${FIN} "
sleep 1s
if [[ `grep -w "jammy" "/etc/os-release"` ]]; then
	echo -en "${PNK}[${FIN}${GRN}Ubuntu Jammy Jellyfish${FIN}${PNK}]${FIN}";
	echo "";
else
	if [[ `grep -w "kinetic" "/etc/os-release"` ]]; then
		echo "";
		echo -e "${TXT}The OS you are running is not supported${FIN}.";
		exit 0;
		#echo -en "${PNK}[${FIN}${GRN}Ubuntu Kinetic Kudu${FIN}${PNK}]${FIN}";
		#echo "";
	else
		if [[ `grep -w "bullseye" "/etc/os-release"` ]]; then
			echo -en "${PNK}[${FIN}${GRN}Debian Bullseye${FIN}${PNK}]${FIN}";
			echo "";
		else
			echo -ne "${PNK}[${FIN}${RED}failed${FIN}${PNK}]${FIN}";
			echo "";
			echo -e "${TXT}The OS you are running is not supported${FIN}.";
			exit 0;
		fi
	fi
fi
echo ""
echo -e "${TXT}Starting install${FIN} ..."
sleep 1s
if [[ `uname -m | grep x86_64` ]]; then
	if [[ `command -v make` ]]; then
		sudo apt update;
		sudo apt upgrade -y;
		make ccompile;
	else
		sudo apt update;
		sudo apt upgrade -y;
		sudo apt install -y make;
		make ccompile;
	fi
fi
if [[ `uname -m | grep aarch64` ]]; then
	if [[ `command -v make` ]]; then
		sudo apt update;
		sudo apt upgrade -y;
		make ncompile;
	else
		sudo apt update;
		sudo apt upgrade -y;
		sudo apt install -y make;
		make ncompile;
	fi
fi
make dialogrc > /dev/null 2>&1
echo ""
clear -x
make

exit 0
