#!/bin/bash
# this file gets sourced and run_function1/2 executed

run_function1 (){
# remove all related user information from stage2
if [ -f ${P_VALUE}/root/stage2 ]; then
	sed -i 's/adduser ${USERNAME} --gecos ${NAME} --disabled-password/#adduser ${USERNAME} --gecos ${NAME} --disabled-password/g' ${P_VALUE}/root/stage2
	sed -i 's/echo "${USERNAME}:${PASSWORD}" | chpasswd/#echo "${USERNAME}:${PASSWORD}" | chpasswd/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} sudo/#adduser ${USERNAME} sudo/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} audio/#adduser ${USERNAME} audio/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} dialout/#adduser ${USERNAME} dialout/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} video/#adduser ${USERNAME} video/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} disk/#adduser ${USERNAME} disk/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} plugdev/#adduser ${USERNAME} plugdev/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} netdev/#adduser ${USERNAME} netdev/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} bluetooth/#adduser ${USERNAME} bluetooth/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} input/#adduser ${USERNAME} input/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} tty/#adduser ${USERNAME} tty/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} i2c/#adduser ${USERNAME} i2c/g' ${P_VALUE}/root/stage2
	sed -i 's/groupadd gpio/#groupadd gpio/g' ${P_VALUE}/root/stage2
	sed -i 's/groupadd spi/#groupadd spi/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} gpio/#adduser ${USERNAME} gpio/g' ${P_VALUE}/root/stage2
	sed -i 's/adduser ${USERNAME} spi/#adduser ${USERNAME} spi/g' ${P_VALUE}/root/stage2
	sed -i 's/mkdir -p \/home\/${USERNAME}\/.config\/mc/#mkdir -p \/home\/${USERNAME}\/.config\/mc/g' ${P_VALUE}/root/stage2
	sed -i 's/mv -f user-ini \/home\/${USERNAME}\/.config\/mc\/\ini/#mv -f user-ini \/home\/${USERNAME}\/.config\/mc\/ini/g' ${P_VALUE}/root/stage2
	sed -i 's/mv -f nanorc-user \/home\/${USERNAME}\/.nanorc/#mv -f nanorc-user \/home\/${USERNAME}\/.nanorc/g' ${P_VALUE}/root/stage2
	sed -i 's/chown -R ${USERNAME}:${USERNAME} \/home\/${USERNAME}/#chown -R ${USERNAME}:${USERNAME} \/home\/${USERNAME}/g' ${P_VALUE}/root/stage2
	sed -i 's/tee \/etc\/sudoers.d\/010_${USERNAME}-nopasswd <<EOF/#tee \/etc\/sudoers.d\/010_${USERNAME}-nopasswd <<EOF/g' ${P_VALUE}/root/stage2
	sed -i 's/${USERNAME} ALL=(ALL) NOPASSWD: ALL/#${USERNAME} ALL=(ALL) NOPASSWD: ALL/g' ${P_VALUE}/root/stage2
	sed -i '375d' ${P_VALUE}/root/stage2
fi
}

run_function2 (){
# add user account service
if [ -f /root/userscripts/useraccount ]; then
	mkdir -p /usr/local/sbin;
	mv -f /root/userscripts/useraccount /usr/local/sbin/;
	chmod +x /usr/local/sbin/useraccount;
	mv -f /root/{nanorc-user,user-ini} /etc/opt/;
fi
if [[ "$DISTRO" == "debian" ]]; then
	if [ -f /root/userscripts/useraccount.service ]; then
		mkdir -p /etc/systemd/system/;
		mv -f /root/userscripts/useraccount.service /etc/systemd/system/;
		systemctl enable useraccount;
		rm -f /root/userscripts/useraccount.init;
	fi
fi
if [[ "$DISTRO" == "devuan" ]]; then
	if [ -f /root/userscripts/useraccount.init ]; then
		mkdir -p /etc/init.d;
		mv -f /root/userscripts/useraccount.init /etc/init.d/useraccount;
		chmod +x /etc/init.d/useraccount;
		update-rc.d useraccount defaults 5;
		rm -f /root/userscripts/useraccount.service;
	fi
fi
if [[ "$DISTRO" == "ubuntu" ]]; then
	if [ -f /root/userscripts/useraccount.service ]; then
		mkdir -p /etc/systemd/system/;
		mv -f /root/userscripts/useraccount.service /etc/systemd/system/;
		systemctl enable useraccount;
		rm -f /root/userscripts/useraccount.init;
	fi
fi
if [ -f /root/userscripts/useraccount.txt ]; then
	mkdir -p /boot;
	mv -f /root/userscripts/useraccount.txt /boot/rename_to_useraccount.txt;
fi
}
