#!/bin/bash

# ATF AND CRUST BINARY
atf_bl31 (){ # place bl31 file.
if [[ "$SERIES" =~ ^(sun50i-a64|sun50i-h5|sun50i-h6|sun50i-h618)$ ]]; then
	if [[ -f "../arm-trusted-firmware-${ATF_TAG}/build/${ATF_PLAT}/debug/bl31.bin" ]]; then
		cp ../arm-trusted-firmware-${ATF_TAG}/build/${ATF_PLAT}/debug/bl31.bin bl31.bin
		cp ../arm-trusted-firmware-${ATF_TAG}/build/${ATF_PLAT}/debug/bl31.bin atf-bl31
	else
		report_atf_error
	fi
	if [[ -f "../crust-${CRUST_TAG}/build/scp/scp.bin" ]]; then
		cp ../crust-${CRUST_TAG}/build/scp/scp.bin scp.bin
	else
		report_crust_error
	fi
fi
}

# U-BOOT
allwinner_uboot_config (){
if [[ "$BOARD" == "cubietruck" ]] && [[ -f "configs/${UBOOT_DEFCONFIG}" ]]; then
	sed -i 's/CONFIG_DRAM_CLK=432/CONFIG_DRAM_CLK=384/g' configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_MMC_SUNXI_SLOT_EXTRA=2" >> configs/${UBOOT_DEFCONFIG}
fi
if [[ "$BOARD" == "pinea64plus" ]] && [[ -f "configs/${UBOOT_DEFCONFIG}" ]]; then
	# Autoboot options
	echo "CONFIG_BOOT_RETRY=y" >> configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_BOOT_RETRY_TIME=5" >> configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_BOOT_RETRY_MIN=5" >> configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_RESET_TO_RETRY=y" >> configs/${UBOOT_DEFCONFIG}
fi
}

uboot_output (){
if [[ -f "u-boot-sunxi-with-spl.bin" ]]; then
	mkdir -p ../../${OUTPUT}
	cp -f u-boot-sunxi-with-spl.bin ../../${OUTPUT}/
	uboot_packaging
else
	report_error
fi
}

allwinner_uboot_run (){
sources_dir
if [[ "$ARCH" == "arm64" ]]; then
	arm_trusted_firmware
	if [[ "$HOST_CODENAME" == "bullseye" ]]; then :; else crust_firmware; fi
fi
uboot_run
uboot_output
}

allwinner_uboot_packaging (){
cp -f u-boot-sunxi-with-spl.bin ${PKGNAME}_${PKGVERSION}-${BV}_${ARCH_EXT}/usr/lib/${PKGNAME}/
}

# LINUX
allwinner_extra_patching (){
# allwinner: all
if [[ "$FAMILY" == "allwinner" ]] && [[ -d "../../${LINUX_PATCHDIR}/all" ]]; then
	if [[ `ls ../../${LINUX_PATCHDIR}/all/*.patch` ]] > /dev/null 2>&1; then
		echo "# ${LINUX_PATCHDIR}/all" | sed -e 's/\(.*\)/\U\1/' >> ${LOG_FILE}
		for i in ../../${LINUX_PATCHDIR}/all/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE}
	fi
fi
if [[ -d "../../${LINUX_PATCHDIR}/${LINUX_VERSION}/dts/${ARCH}" ]]; then
	if [[ `ls ../../${LINUX_PATCHDIR}/${LINUX_VERSION}/dts/${ARCH}/{Makefile,*.dts}` ]] > /dev/null 2>&1; then
		echo "# ${LINUX_PATCHDIR}/${LINUX_VERSION}/dts/${ARCH}" | sed -e 's/\(.*\)/\U\1/' >> ${LOG_FILE}
		ls ../../${LINUX_PATCHDIR}/${LINUX_VERSION}/dts/${ARCH}/*.dts* | sed 's/..\/..\///g' >> ${LOG_FILE}
		cp -fr ../../${LINUX_PATCHDIR}/${LINUX_VERSION}/dts/${ARCH}/*.dts* arch/${ARCH}/boot/dts/${PLATFORM}
		echo "" >> arch/${ARCH}/boot/dts/${PLATFORM}/Makefile
		cat ../../${LINUX_PATCHDIR}/${LINUX_VERSION}/dts/${ARCH}/Makefile >> arch/${ARCH}/boot/dts/${PLATFORM}/Makefile
	fi
fi
}

allwinner_extra_wireless (){
if [[ "$BOARD" == "orangepi3lts" ]] && [[ -d "../../${WIRELESSPATCHES}/unisoc/${LINUX_VERSION}" ]]; then
	if [[ `ls ../../${WIRELESSPATCHES}/unisoc/${LINUX_VERSION}/*.patch` ]] > /dev/null 2>&1; then
		echo "# ${WIRELESSPATCHES}/unisoc/${LINUX_VERSION}" | sed -e 's/\(.*\)/\U\1/' >> ${LOG_FILE}
		for i in ../../${WIRELESSPATCHES}/unisoc/${LINUX_VERSION}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE}
	fi
fi
}

# STAGE1
flash_uboot (){
dd if=${OUTPUT}/u-boot-sunxi-with-spl.bin of="${IMAGE_LOOP_DEV}" conv=fsync bs=1024 seek=8
}

allwinner_stage1_extra_firmware (){
if [[ "$BOARD" == "bananapim4zero" ]]; then
	mkdir -p ${P_VALUE}/lib/firmware/updates/brcm
	cp -r files/firmware/brcm/* ${P_VALUE}/lib/firmware/updates/brcm
fi
}

# STAGE2
allwinner_extra_firmware (){
if [[ -f "/lib/firmware/brcm/brcmfmac43430-sdio.bin" ]] && [[ -f "/lib/firmware/brcm/brcmfmac43430-sdio.txt" ]]; then
	ln -s /lib/firmware/brcm/brcmfmac43430-sdio.bin /lib/firmware/brcm/brcmfmac43430-sdio.friendlyarm,nanopi-neo-plus2.bin
	ln -s /lib/firmware/brcm/brcmfmac43430-sdio.bin /lib/firmware/brcm/brcmfmac43430-sdio.sinovoip,bpi-m2-zero.bin
	ln -s /lib/firmware/brcm/brcmfmac43430-sdio.bin /lib/firmware/brcm/brcmfmac43430-sdio.sinovoip,bpi-p2-zero.bin
	ln -s /lib/firmware/brcm/brcmfmac43430-sdio.txt /lib/firmware/brcm/brcmfmac43430-sdio.sinovoip,bpi-m2-zero.txt
	ln -s /lib/firmware/brcm/brcmfmac43430-sdio.txt /lib/firmware/brcm/brcmfmac43430-sdio.sinovoip,bpi-p2-zero.txt
fi
if [[ "$BOARD" =~ ^(bananapim2zero|bananapip2zero|nanopineoplus2)$ ]]; then
	git clone --depth=1 -q -b nanopi https://github.com/pyavitz/firmware.git
	rm -fdr firmware/{.git,README.md}; cp -fr firmware/* /lib/firmware; rm -fdr firmware
fi
if [[ "$BOARD" == "cubietruck" ]]; then
	git clone --depth=1 -q -b cubietruck https://github.com/pyavitz/firmware.git
	rm -fdr firmware/{.git,README.md}; cp -fr firmware/* /lib/firmware; rm -fdr firmware
fi
}

pinea64plus_bthelper (){
echo  ""
echo -e "Installing bluetooth helper ..."
sleep .50
git clone https://github.com/lwfinger/rtl8723bs_bt.git
cd rtl8723bs_bt
make
make install
mv rtk_hciattach /usr/local/bin/
cd ~
rm -fdr rtl8723bs_bt
mkdir -p /etc/modules-load.d/
echo "r8723bs" > /etc/modules-load.d/pine64.conf
echo "hci_uart" >> /etc/modules-load.d/pine64.conf
mkdir -p /etc/modprobe.d/
echo "options r8723bs rtw_power_mgnt=0" > /etc/modprobe.d/wifi-pwrmgnt.conf
cat <<EOF > "/usr/local/sbin/bthelper"
#!/bin/bash
if [[ -f "/sys/class/rfkill/rfkill0/state" ]]; then
	echo "1" > /sys/class/rfkill/rfkill0/state
	sleep 1s
	rtk_hciattach /dev/ttyS1 rtk_h5
	sleep 2s
	hciconfig hci0 up
fi
EOF
chmod +x /usr/local/sbin/bthelper
}
