#!/bin/bash

# STAGE1
flash_uboot(){
dd if=${OUTPUT}/u-boot-sunxi-with-spl.bin of="${IMAGE_LOOP_DEV}" conv=fsync bs=1024 seek=8
}

# STAGE2
nanopi_firmware(){
echo ""
echo "Adding NanoPi NEO Plus2 firmware ..."
cd ~
git clone -b nanopi https://github.com/pyavitz/firmware.git
if [[ -f "firmware/README.md" ]]; then
	rm -f firmware/README.md;
fi
cp -fr firmware/* /lib/firmware
if [ -f fw-0a5c_21e8.hcd ]; then 
	mv fw-0a5c_21e8.hcd /lib/firmware/brcm/BCM20702A0-0a5c-21e8.hcd;
	cp /lib/firmware/brcm/BCM20702A0-0a5c-21e8.hcd /lib/firmware/brcm/BCM20702A1-0a5c-21e8.hcd;
	chown root:root /lib/firmware/brcm/BCM20702A1-0a5c-21e8.hcd;
	chown root:root /lib/firmware/brcm/BCM20702A0-0a5c-21e8.hcd;
fi
if [ -f UPDATE.mem ]; then
	install -Dm644 UPDATE.mem /lib/firmware/renesas_usb_fw.mem;
	rm -f UPDATE.mem;
fi
mkdir -p /lib/firmware/rtl_nic
wget -cq https://kernel.googlesource.com/pub/scm/linux/kernel/git/firmware/linux-firmware.git/+archive/refs/heads/main/rtl_nic.tar.gz -P /lib/firmware/rtl_nic
if [[ -f "/lib/firmware/rtl_nic/rtl_nic.tar.gz" ]]; then
	tar xf /lib/firmware/rtl_nic/rtl_nic.tar.gz -C /lib/firmware/rtl_nic;
	rm -f /lib/firmware/rtl_nic/rtl_nic.tar.gz;
fi
rm -fdr firmware
echo "Done."
}

pine64_bthelper(){
tee /usr/local/sbin/pine64-bthelper <<EOF
#!/bin/bash
if [[ -f "/sys/class/rfkill/rfkill0/state" ]]; then
	echo "1" > /sys/class/rfkill/rfkill0/state
	sleep 1s
	rtk_hciattach /dev/ttyS1 rtk_h5
	sleep 2s
	hciconfig hci0 up
fi
EOF
if [[ -f "/usr/local/sbin/pine64-bthelper" ]]; then
	chmod +x /usr/local/sbin/pine64-bthelper;
fi
}

pine64_bthelper2(){
echo
echo "Installing bluetooth helper ..."
sleep 1s
git clone https://github.com/lwfinger/rtl8723bs_bt.git
cd rtl8723bs_bt
make
make install
mv rtk_hciattach /usr/local/bin/
cd ~
rm -fdr rtl8723bs_bt
mkdir -p /etc/modules-load.d/
echo "r8723bs" > /etc/modules-load.d/pine64.conf
echo "hci_uart" >> /etc/modules-load.d/pine64.conf
mkdir -p /etc/modprobe.d/
echo "options r8723bs rtw_power_mgnt=0" > /etc/modprobe.d/wifi-pwrmgnt.conf
echo "Done."
}
