#!/bin/bash

# ATF AND CRUST BINARY
atf_bl31 (){ # place bl31 file.
if [[ "$SERIES" =~ ^(sun50i-a64|sun50i-h5|sun50i-h6|sun50i-h618)$ ]]; then
	if [[ -f "../arm-trusted-firmware/build/${ATF_PLAT}/debug/bl31.bin" ]]; then
		cp ../arm-trusted-firmware/build/${ATF_PLAT}/debug/bl31.bin bl31.bin
		cp ../arm-trusted-firmware/build/${ATF_PLAT}/debug/bl31.bin atf-bl31
	else
		report_atf_error
	fi
	if [[ "$SERIES" =~ ^(sun50i-a64|sun50i-h5|sun50i-h6)$ ]]; then
		if [[ "$HOST_CODENAME" == "bullseye" ]]; then
			cp ../../files/boot/crust/${SERIES}-scp.bin scp.bin
		else
			if [[ -f "../crust/build/scp/scp.bin" ]]; then
				cp ../crust/build/scp/scp.bin scp.bin
			else
				report_crust_error
			fi
		fi
	fi
fi
}

# U-BOOT
uboot_configs (){
# add default builder config options
if [[ -f "configs/${UBOOT_DEFCONFIG}" ]]; then
	if [[ `grep -w "CONFIG_SD_BOOT=y" "configs/${UBOOT_DEFCONFIG}"` ]]; then :; else echo "CONFIG_SD_BOOT=y" >> configs/${UBOOT_DEFCONFIG}; fi
	if [[ `grep -w "CONFIG_EXT4_WRITE=y" "configs/${UBOOT_DEFCONFIG}"` ]]; then :; else echo "CONFIG_EXT4_WRITE=y" >> configs/${UBOOT_DEFCONFIG}; fi
	if [[ `grep -w "CONFIG_FS_BTRFS=y" "configs/${UBOOT_DEFCONFIG}"` ]]; then :; else echo "CONFIG_FS_BTRFS=y" >> configs/${UBOOT_DEFCONFIG}; fi
	if [[ `grep -w "CONFIG_CMD_BTRFS=y" "configs/${UBOOT_DEFCONFIG}"` ]]; then :; else echo "CONFIG_CMD_BTRFS=y" >> configs/${UBOOT_DEFCONFIG}; fi
fi
if [[ "$BOARD" == "cubietruck" ]] && [[ -f "configs/${UBOOT_DEFCONFIG}" ]]; then
	sed -i 's/CONFIG_DRAM_CLK=432/CONFIG_DRAM_CLK=384/g' configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_MMC_SUNXI_SLOT_EXTRA=2" >> configs/${UBOOT_DEFCONFIG}
fi
if [[ "$BOARD" == "pinea64plus" ]] && [[ -f "configs/${UBOOT_DEFCONFIG}" ]]; then
	# Autoboot options
	echo "CONFIG_BOOT_RETRY=y" >> configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_BOOT_RETRY_TIME=5" >> configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_BOOT_RETRY_MIN=5" >> configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_RESET_TO_RETRY=y" >> configs/${UBOOT_DEFCONFIG}
fi
}

uboot_output (){
if [[ -f "u-boot-sunxi-with-spl.bin" ]]; then
	mkdir -p ../../${OUTPUT}
	cp -f u-boot-sunxi-with-spl.bin ../../${OUTPUT}/
	uboot_packaging
	echo ""
else
	report_error
fi
}

allwinner_uboot_run (){
sources_dir
if [[ "$ARCH" == "arm64" ]]; then
	arm_trusted_firmware
	if [[ "$HOST_CODENAME" == "bullseye" ]]; then :; else crust_firmware; fi
fi
uboot_run
uboot_output
}

allwinner_uboot_packaging (){
cp -f u-boot-sunxi-with-spl.bin ${PKGNAME}_${PKGVERSION}-${BV}_${ARCH_EXT}/usr/lib/${PKGNAME}/
}

# LINUX
allwinner_extra_patching (){
# allwinner: all
if [[ "$FAMILY" == "allwinner" ]] && [[ -d "../../${LINUX_PATCHDIR}/all" ]]; then
	if [[ `ls ../../${LINUX_PATCHDIR}/all/*.patch` ]] > /dev/null 2>&1; then
		echo "# ${LINUX_PATCHDIR}/all" | sed -e 's/\(.*\)/\U\1/' >> ${LOG_FILE}
		for i in ../../${LINUX_PATCHDIR}/all/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE}
	fi
fi
}

allwinner_extra_wireless (){
if [[ "$BOARD" == "bananapim4zero" ]] && [[ -d "../../${WIRELESSPATCHES}/rtl8821cu" ]]; then
	if [[ `ls ../../${WIRELESSPATCHES}/rtl8821cu/*.patch` ]] > /dev/null 2>&1; then
		echo "# ${WIRELESSPATCHES}/rtl8821cu/${LINUX_VERSION}" | sed -e 's/\(.*\)/\U\1/' >> ${LOG_FILE}
		for i in ../../${WIRELESSPATCHES}/rtl8821cu/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE}
	fi
fi
if [[ "$BOARD" == "orangepi3lts" ]] && [[ -d "../../${WIRELESSPATCHES}/unisoc/${LINUX_VERSION}" ]]; then
	if [[ `ls ../../${WIRELESSPATCHES}/unisoc/${LINUX_VERSION}/*.patch` ]] > /dev/null 2>&1; then
		echo "# ${WIRELESSPATCHES}/unisoc/${LINUX_VERSION}" | sed -e 's/\(.*\)/\U\1/' >> ${LOG_FILE}
		for i in ../../${WIRELESSPATCHES}/unisoc/${LINUX_VERSION}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE}
	fi
fi
}

# STAGE1
flash_uboot (){
dd if=${OUTPUT}/u-boot-sunxi-with-spl.bin of="${IMAGE_LOOP_DEV}" conv=fsync bs=1024 seek=8
}

# STAGE2
pine64_bthelper (){
echo  ""
echo -e "Installing bluetooth helper ..."
sleep .50
git clone https://github.com/lwfinger/rtl8723bs_bt.git
cd rtl8723bs_bt
make
make install
mv rtk_hciattach /usr/local/bin/
cd ~
rm -fdr rtl8723bs_bt
mkdir -p /etc/modules-load.d/
echo "r8723bs" > /etc/modules-load.d/pine64.conf
echo "hci_uart" >> /etc/modules-load.d/pine64.conf
mkdir -p /etc/modprobe.d/
echo "options r8723bs rtw_power_mgnt=0" > /etc/modprobe.d/wifi-pwrmgnt.conf
cat <<EOF > "/usr/local/sbin/bthelper"
#!/bin/bash
if [[ -f "/sys/class/rfkill/rfkill0/state" ]]; then
	echo "1" > /sys/class/rfkill/rfkill0/state
	sleep 1s
	rtk_hciattach /dev/ttyS1 rtk_h5
	sleep 2s
	hciconfig hci0 up
fi
EOF
if [[ -f "/usr/local/sbin/bthelper" ]]; then
	chmod +x /usr/local/sbin/bthelper
fi
}
