#!/bin/bash

# ATF
arm-trusted-firmware(){
if [[ -e arm-trusted-firmware ]]; then
	echo -en "${WHT}arm trusted firmware${FIN} ";
	echo -en "${PNK}[${FIN}${YLW}found${FIN}${PNK}]${FIN} ";
	cd arm-trusted-firmware;
	make realclean > /dev/null 2>&1;
	git config pull.rebase false;
	echo -en "${PNK}[${FIN}${WHT}pulling${FIN}${PNK}]${FIN} ";
	git pull -q;
	echo_bdone;
else
	echo -en "${WHT}arm trusted firmware${FIN} ";
	echo -en "${PNK}[${FIN}${WHT}cloning${FIN}${PNK}]${FIN} ";
	git clone -q https://github.com/ARM-software/arm-trusted-firmware.git;
	cd arm-trusted-firmware;
	make realclean > /dev/null 2>&1;
	echo_bdone;
fi
echo ""
if [ $crosscompile -eq 1 ]; then
	echo -e "${GRN}  CC${FIN}";
	export CROSS_COMPILE=${CROSS_COMPILE};
	make -j${CORES} CC=${CROSS} ${ATF_EXT};
else
	echo -e "${GRN}  NC${FIN}";
	export ARCH=${ARCH};
	make -j${CORES} CC=${NATIVE} ${ATF_EXT};
fi
cd ..
if [ -f u-boot-${UBOOT_VERSION}.tar.gz ]; then echo ""; else :; fi 
}

rkbin(){
#RKURL="https://github.com/armbian/rkbin/archive/refs/heads"
#RKURL="https://github.com/rockchip-linux/rkbin/archive/refs/heads"
#RKURL="https://github.com/mj22226/rkbin/archive/refs/heads"
RKURL="https://github.com/pyavitz/debian-image-builder/releases/download/u-boot"
if [[ -f rkbin-master.tar.gz ]]; then
	echo -en "${WHT}rkbin-master${FIN} ";
	echo -e "${PNK}[${FIN}${YLW}found${FIN}${PNK}]${FIN}";
else
	echo -en "${WHT}rkbin-master${FIN} ";
	echo -en "${PNK}[${FIN}${WHT}downloading${FIN}${PNK}]${FIN} ";
	# pull from source
	#aria2c -q ${RKURL}/master.tar.gz;
	# pull from builder
	aria2c -q ${RKURL}/rkbin-master.tar.gz;
	echo_bdone;
fi
}
