#!/bin/bash

# ATF
arm-trusted-firmware(){
if [[ -e arm-trusted-firmware ]]; then
	atf_clean;
	cd arm-trusted-firmware;
	make realclean > /dev/null 2>&1;
	git config pull.rebase false;
	git pull;
else
	atf_dl;
	git clone https://github.com/ARM-software/arm-trusted-firmware.git;
	cd arm-trusted-firmware;
	make realclean > /dev/null 2>&1;
fi
echo ""
echo -e "${WHT}Compiling ATF${FIN} ..."
if [ $crosscompile -eq 1 ]; then
	echo -e "${GRN}  CC${FIN}";
	export CROSS_COMPILE=${CROSS_COMPILE};
	make -j${CORES} CC=${CROSS} ${ATF_EXT};
else
	echo -e "${GRN}  NC${FIN}";
	export ARCH=${ARCH};
	make -j${CORES} CC=${NATIVE} ${ATF_EXT};
fi
cd ..
echo_done
echo ""
}
