#!/bin/bash

gcc_version(){
echo NATIVE='"'/usr/bin/${COMPILER}'"' > gcc.txt
echo CROSS='"'/usr/bin/${CROSS_COMPILE}${COMPILER}'"' >> gcc.txt
source gcc.txt
}

ccache_version(){
echo NATIVE='"'/usr/lib/ccache/${COMPILER}'"' > ccache.txt
echo CROSS='"'/usr/lib/ccache/${CROSS_COMPILE}${COMPILER}'"' >> ccache.txt
source ccache.txt
}
