#!/bin/bash

crust_defconfig (){
if [[ "$BOARD" == "orangepi3lts" && ! -f "configs/${CRUST_DEFCONFIG}" ]]; then
	echo "CONFIG_PLATFORM_H6=y" > configs/${CRUST_DEFCONFIG}
	echo "CONFIG_CIR=y" >> configs/${CRUST_DEFCONFIG}
	echo "CONFIG_I2C_PINS_PL0_PL1=y" >> configs/${CRUST_DEFCONFIG}
	echo "CONFIG_MFD_AXP20X=y" >> configs/${CRUST_DEFCONFIG}
fi
}

crust_firmware (){
# https://github.com/crust-firmware/crust
# apt install gcc-or1k-elf
# The package isn't currently available in the Debian Bullseye repo.
# For the time being we will use precompiled binaries.
CRUST_TAG="v0.6"
GIT_CRUST_URL="https://github.com/crust-firmware/crust.git"
if [[ "$SERIES" =~ ^(sun8i-h2-plus|sun8i-h3|sun50i-a64|sun50i-h5|sun50i-h6)$ ]]; then
	if [[ `wget -S --spider https://raw.githubusercontent.com/crust-firmware/crust/refs/heads/master/Makefile 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
		if [[ -d "crust-${CRUST_TAG}" ]]; then
			echo -en "Crust ${CRUST_TAG}:"
			echo -en " Restoring"
			rm -fdr crust
			cd crust-${CRUST_TAG}
			make clean > /dev/null 2>&1
			cd ..
			cp -r crust-${CRUST_TAG} crust
			echo -e ", done."
		else
			rm -fdr crust-${CRUST_TAG} crust crust-${CRUST_TAG}.backup
			echo -en "Crust ${CRUST_TAG}:"
			echo -en " Cloning"
			git clone --depth=1 -b ${CRUST_TAG} -q -c advice.detachedHead=false ${GIT_CRUST_URL} crust-${CRUST_TAG}
			if [[ -d "crust-${CRUST_TAG}" ]]; then
				cd crust-${CRUST_TAG}
				make clean > /dev/null 2>&1
				cd ..
				echo -en ", creating work dir"
				cp -r crust-${CRUST_TAG} crust
				echo -e ", done."
			else
				echo -e ", failed."
				exit 1
			fi
		fi
	fi
	echo ""
	cd crust
	crust_defconfig
	if [[ -f "configs/${CRUST_DEFCONFIG}" ]]; then
		if [ $CROSSCOMPILE -eq 1 ]; then echo -e "${GRN}  CC${FIN}"; else echo -e "${GRN}  NC${FIN}"; fi
		make -j${CORES} ARCH=${ARCH} CROSS_COMPILE=or1k-elf- ${CRUST_DEFCONFIG}
		make -j${CORES} ARCH=${ARCH} CROSS_COMPILE=or1k-elf-
	else
		echo ""
		echo -e "${CRUST_DEFCONFIG} was not found."
		echo -e "Check that the name is correct in the lib/boards/${BOARD} file."
		echo -e ""
		read -p "Press enter to continue."
		exit 1
	fi
	cd ..
	echo ""
fi
}

report_crust_error (){
echo "Missing crust scp.bin blob. Please report build errors."
echo ""
exit 1
}
