#!/bin/bash

# COLOR
RED="\e[1;31m"
GRN="\e[1;32m"
PNK="\e[1;35m"
YLW="\e[1;33m"
WHT="\e[1;37m"
FIN="\e[0m"

# ECHOES
echo_duboot(){
echo -e "${WHT}Downloading u-boot${FIN} ..."
}

echo_cuboot(){
echo -e "${WHT}Compiling uboot${FIN} ..."
}

echo_compress(){
echo -e "${WHT}Compressing image${FIN} ..."
}

echo_extract(){
echo -e "${WHT}Extracting archive${FIN} ..."
}

echo_extracts(){
echo -e "${WHT}Extracting archives${FIN} ..."
}

echo_patch(){
echo -e "${WHT}Applying patches${FIN} ..."
}

echo_blobs(){
echo -e "${WHT}Downloading toolchains and blobs${FIN} ..."
}

echo_toolchain(){
echo -e "${WHT}Downloading toolchain${FIN} ..."
}

echo_bootfips(){
echo -e "${WHT}Downloading firmware image package${FIN} ..."
}

echo_done(){
echo -e "${WHT}Done${FIN}."
}

echo_ok(){
echo -e "${PNK}[${FIN}${GRN}ok${FIN}${PNK}]${FIN}"
}

echo_nok () {
echo -e -n "${PNK}[${FIN}${GRN}ok${FIN}${PNK}]${FIN}"
}

echo_fail () {
echo -n -e "${YLW}[${FIN}${RED}failed${FIN}${YLW}]${FIN}"; echo ""
}

echo_bdone(){
echo -e "${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}"
}

echo_firm(){
echo -e "${WHT}Downloading firmware${FIN} ..."
}

echo_stable(){
echo -e "${WHT}Downloading linux ${VERSION}${FIN} ..."
}

echo_mainline(){
echo -e "${WHT}Downloading linux ${VERSION}${FIN} ..."
}

echo_vendor(){
echo -e "${WHT}Downloading ${VKERNEL} ${VERSION}${FIN} ..."
}

echo_cconfig(){
echo -e "${WHT}Making ${MYCONFIG}${FIN} ..."
}

echo_menuconfig(){
echo -e "${WHT}Opening menuconfig${FIN} ..."
}

echo_build(){
echo -e "${WHT}--- Building deb packages${FIN} ..."
}

echo_defconfig(){
echo -e "${WHT}Making ${LINUX_DEFCONFIG}${FIN} ..."
}

atf_dl(){
echo -e "${WHT}Downloading arm trusted firmware${FIN} ..."
}

atf_clean(){
echo -e "${YLW}Cleaning arm trusted firmware${FIN} ..."
}
