#!/bin/bash

# COLOR
RED="\e[0;31m"
GRN="\e[0;32m"
PNK="\e[0;35m"
YLW="\e[0;36m"
WHT="\033[0m"
FIN="\e[0m"

# ECHOES
echo_duboot(){
echo -e "${WHT}Downloading U-Boot-${UBOOT_VERSION}${FIN} ..."
}

echo_cuboot(){
echo -e "${WHT}Compiling U-Boot-${UBOOT_VERSION}${FIN} ..."
}

echo_compress(){
echo -e "${WHT}== Compressing image${FIN}"
}

echo_extract(){
echo -e "${WHT}Extracting${FIN} ..."
}

echo_patch(){
echo -e "${WHT}Applying patches${FIN} ..."
}

echo_done(){
echo -e "${WHT}Done${FIN}."
}

echo_ok(){
echo -e "${PNK}[${FIN}${GRN}ok${FIN}${PNK}]${FIN}"
}

echo_nok () {
echo -en "${PNK}[${FIN}${GRN}ok${FIN}${PNK}]${FIN}"
}

echo_fail () {
echo -en "${YLW}[${FIN}${RED}failed${FIN}${YLW}]${FIN}"; echo ""
}

echo_bdone(){
echo -e "${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}"
}

echo_vendor(){
echo -e "${WHT}Downloading ${VENDOR_KERNEL} ${VERSION}${FIN} ..."
}

echo_cconfig(){
echo -e "${WHT}Making ${MYCONFIG}${FIN} ..."
}

echo_menuconfig(){
echo -e "${WHT}Opening menuconfig${FIN} ..."
}

echo_build(){
echo -e "${WHT}  Building deb packages${FIN} ..."
}

echo_defconfig(){
echo -e "${WHT}Making ${LINUX_DEFCONFIG}${FIN} ..."
}
