#!/bin/bash

# U-Boot
flash_uboot(){
if [[ "$SERIES" == "imx6q" ]]; then
	dd if=${OUTPUT}/sploader.bin of="${IMAGE_LOOP_DEV}" bs=1k seek=1 conv=sync
	dd if=${OUTPUT}/u-boot.bin of="${IMAGE_LOOP_DEV}" bs=1k seek=69 conv=sync
fi
if [[ "$SERIES" == "imx8mp" ]]; then
	dd if=${OUTPUT}/u-boot.bin of="${IMAGE_LOOP_DEV}" bs=1024 seek=33 conv=notrunc
fi
}
