#!/bin/bash

# STAGE1
flash_uboot (){
echo ""
}

# STAGE2
generic_extra_firmware (){
mkdir -p /lib/firmware/updates/brcm
mv -f fw-0a5c_21e8.hcd /lib/firmware/updates/brcm/BCM20702A0-0a5c-21e8.hcd
ln -s /lib/firmware/updates/brcm/BCM20702A0-0a5c-21e8.hcd /lib/firmware/updates/brcm/BCM20702A1-0a5c-21e8.hcd
install -Dm644 UPDATE.mem /lib/firmware/updates/renesas_usb_fw.mem
rm -f UPDATE.mem
}
