#!/bin/bash

git_download (){
if [[ `git ls-remote --heads ${GIT_URL}/${GIT_OWN}/${GIT_REPO}.git -b ${GIT_BRANCH} 2>&1 | grep -w "refs/heads/${GIT_BRANCH}"` ]]; then
	git_option
	if [[ "$GIT_SHALLOW" == "true" ]]; then git_verify; fi
	if [[ -d "${GIT_REPO}-${GIT_BRANCH}" ]]; then
		echo -en "${GIT_REPO}-${GIT_BRANCH}:"
		echo -en " Restoring"
		if [[ "$GIT_SHALLOW" == "false" ]]; then
			cd ${GIT_REPO}-${GIT_BRANCH}; git pull -q; make clean > /dev/null 2>&1; cd ..
		fi
		rm -fdr ${KERNEL}
		cp -r ${GIT_REPO}-${GIT_BRANCH} ${KERNEL}
		rm -fdr ${KERNEL}/.git # modern packaging picks up the most recent git commit
		echo -e ", done."
	else
		echo -e "This may take a while ..."
		echo ""
		git clone ${GIT_OPT} -b ${GIT_BRANCH} ${GIT_URL}/${GIT_OWN}/${GIT_REPO}.git ${GIT_REPO}-${GIT_BRANCH}
		sleep .50
		if [[ -d "${GIT_REPO}-${GIT_BRANCH}" ]] && [[ -f "${GIT_REPO}-${GIT_BRANCH}/Makefile" ]]; then
			cd ${GIT_REPO}-${GIT_BRANCH}
			if [[ `type ${FAMILY}_extra_git` ]] &>/dev/null; then ${FAMILY}_extra_git; fi
			make clean > /dev/null 2>&1; cd ..
			echo -en "${GIT_REPO}-${GIT_BRANCH}:"
			echo -en " Creating work dir"
			if [[ -d "${KERNEL}" ]]; then rm -fdr ${KERNEL}; fi
			cp -r ${GIT_REPO}-${GIT_BRANCH} ${KERNEL}
			rm -fdr ${KERNEL}/.git # modern packaging picks up the most recent git commit
			echo -e ", done."
		else
			echo -en "${GIT_REPO}-${GIT_BRANCH}:"
			echo -en " Download"
			echo -e ", failed."
			exit 1
		fi
	fi
else
	echo ""
	echo -e "The git branch ${GIT_BRANCH} is not available?"
	exit 1
fi
}

git_setup (){
sleep .75
if [[ -d "${KERNEL}" ]]; then
	cd ${KERNEL}
	export ARCH=${ARCH}
	# remove builddeb and mkdebian scripts
	rm -f scripts/package/{builddeb,mkdebian}
	# add custom builddeb and mkdebian scripts
	if [[ "$LEGACY_PACKAGING" == "true" ]]; then
		cp -fr ../../packaging/legacy/{builddeb,mkdebian} scripts/package/
	else
		cp -fr ../../packaging/{builddeb,mkdebian} scripts/package/
	fi
	chmod +x scripts/package/{builddeb,mkdebian}
else
	echo "NOTICE: Directory ${KERNEL} is MIA. Please make a report."
	echo ""
	exit 1
fi
}

git_option (){
GIT_HASH=`git ls-remote --heads ${GIT_URL}/${GIT_OWN}/${GIT_REPO}.git | grep -w "refs/heads/${GIT_BRANCH}" | sed -n '1p' | sed "s/refs\/heads\/${GIT_BRANCH}//g" | sed s/'\s'//g`
if [[ -f "../.cache/git_shallow.${GIT_REPO}-${GIT_BRANCH}" ]] && [[ -d "${GIT_REPO}-${GIT_BRANCH}" ]]; then
	:;
else
	rm -f ../.cache/git_shallow.${GIT_REPO}-${GIT_BRANCH}
	rm -fdr ${GIT_REPO}-${GIT_BRANCH}
fi
if [[ -f "../.cache/git_shallow.${GIT_REPO}-${GIT_BRANCH}" ]]; then
	source ../.cache/git_shallow.${GIT_REPO}-${GIT_BRANCH}
	if [[ "$GIT_SHALLOW" == "true" ]]; then GIT_OPT="--depth 1"; else GIT_OPT=""; fi
else
	mkdir -p ../.cache
	echo 'GIT_SHALLOW="true"' > ../.cache/git_shallow.${GIT_REPO}-${GIT_BRANCH}
	echo GIT_COMMIT='"'${GIT_HASH}'"' >> ../.cache/git_shallow.${GIT_REPO}-${GIT_BRANCH}
	GIT_OPT="--depth 1"
fi
GIT_HASH_SHORT=`echo "${GIT_HASH}" | sed 's/^\(.\{7\}\).*/\1/'`
GIT_COMMIT_SHORT=`echo "${GIT_COMMIT}" | sed 's/^\(.\{7\}\).*/\1/'`
}

git_verify (){
echo -en "Commit:"
if [[ "$GIT_COMMIT" == "$GIT_HASH" ]]; then
	echo -en " ${GIT_COMMIT_SHORT}"
	sleep .50
	echo -e ", ok."
else
	
	echo -en " ${GIT_HASH_SHORT}"
	sleep .50
	echo -e " ${ITL}NEW!${FIN}"
	sed -i 's/^GIT_COMMIT=.*/GIT_COMMIT="'"${GIT_HASH}"'"/' ../.cache/git_shallow.${GIT_REPO}-${GIT_BRANCH}
	echo -en "Removing: ${GIT_COMMIT_SHORT}"
	rm -fdr ${GIT_REPO}-${GIT_BRANCH} ${GIT_REPO}-${GIT_BRANCH}.backup
	echo -e ", done."
	echo ""
fi
}
