#!/bin/bash

# github
check_github(){
if [[ -f "../github.txt" ]]; then
	if [[ "$VERSION" == "4.9.y" || "$VERSION" == "4.19.y" ]]; then
		SETUP="vendor"
	fi
	if [ -z "$GITHUB" ]; then GITHUB=`sed -n 1p ../github.txt`; fi
	if [ -z "$GITHUB_REPO" ]; then GITHUB_REPO=`sed -n 2p ../github.txt`; fi	
	if [ -z "$GITHUB_BRANCH" ]; then GITHUB_BRANCH=`sed -n 3p ../github.txt`; fi
	VENDOR_KERNEL="${GITHUB_REPO}-${GITHUB_BRANCH}"
fi
if [[ `wget -S --spider https://raw.githubusercontent.com/${GITHUB}/${GITHUB_REPO}/${GITHUB_BRANCH}-${VERSION}/Makefile 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	vendor_download
	vendor_extract
else
	echo ""
	echo -e "${WHT}It appears the kernel you selected is not available${FIN}?"
	exit
fi
}

vendor_download(){
if [[ -f "${VENDOR_KERNEL}-${VERSION}.tar.gz" ]]; then
	:;
else
	echo_vendor
	${DOWNLOAD} https://github.com/${GITHUB}/${GITHUB_REPO}/archive/refs/heads/${GITHUB_BRANCH}-${VERSION}.tar.gz
	echo_bdone
fi
extra_wireless
}

vendor_extract(){
echo ""
echo_extract
pv ${VENDOR_KERNEL}-${VERSION}.tar.gz | tar -xzf - -C .
mv -f ${VENDOR_KERNEL}-${VERSION} linux-${VERSION}
if [[ -e "linux-${VERSION}/debian" ]]; then
	rm -fdr linux-${VERSION}/debian;
fi
}

vendor_setup(){
cd ${KERNEL}-${VERSION}
if [ $rtl8812au -eq 1 ]; then
	rtl8812au
fi
if [ $rtl88x2bu -eq 1 ]; then
	rtl88x2bu
fi
if [ $rtl8811cu -eq 1 ]; then
	rtl8811cu
fi
export ARCH=${ARCH}
if [[ "$VERSION" == "4.9.y" ]]; then
	# remove builddeb script
	rm -f scripts/package/builddeb
	# add custom builddeb script
	cp -fr ../../packaging/builddeb-4.9 scripts/package/builddeb
	chmod +x scripts/package/builddeb
fi
if [[ "$VERSION" == "4.19.y" ]]; then
	# remove builddeb and mkdebian scripts
	rm -f scripts/package/{builddeb,mkdebian}
	# add custom builddeb and mkdebian scripts
	cp -fr ../../packaging/builddeb-4.19 scripts/package/builddeb
	cp -fr ../../packaging/mkdebian-4.19 scripts/package/mkdebian
	chmod +x scripts/package/{builddeb,mkdebian}
fi
}

vendor_config(){
echo_defconfig
if [[ "$FAMILY_EXT" == "odroid" ]] && [[ "$VERSION" == "4.9.y" ]]; then
	cp -f ../${DEF}/${FAMILY_EXT}-${VERSION}_defconfig arch/${ARCH}/configs/${LINUX_DEFCONFIG}
fi
if [[ "$FAMILY_EXT" == "rk356x" ]] && [[ "$VERSION" == "4.19.y" ]]; then
	cp -f ../${DEF}/${FAMILY_EXT}-${VERSION}_defconfig arch/${ARCH}/configs/${LINUX_DEFCONFIG}
fi
if [ -f arch/${ARCH}/configs/${LINUX_DEFCONFIG} ]; then
	:;
else
	cp -f ../${DEF}/${LINUX_DEFCONFIG} arch/${ARCH}/configs/
fi
rtl8812au_module
rtl88x2bu_module
rtl8811cu_module
if [ $crosscompile -eq 1 ]; then
	make -j${CORES} KBUILD_DEBARCH=${DEBARCH} ARCH=${ARCH} CC=${CROSS} CFLAGS="${CFLAGS}" CROSS_COMPILE=${CROSS_COMPILE} ${LINUX_DEFCONFIG}
else
	make -j${CORES} KBUILD_DEBARCH=${DEBARCH} ARCH=${ARCH} CC=${NATIVE} CFLAGS="${CFLAGS}" ${LINUX_DEFCONFIG}
fi
echo_done
}
