#!/bin/bash

# PATCHING
sun50i_packaging(){
sed -i 's/packagename=linux-image-$version/packagename=sun50i-linux-image/g' scripts/package/builddeb
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=sun50i-linux-headers/g' scripts/package/builddeb
sed -i 's/packagename=linux-image-$version/packagename=sun50i-linux-image/g' scripts/package/mkdebian
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=sun50i-linux-headers/g' scripts/package/mkdebian
}

sun8i_packaging(){
sed -i 's/packagename=linux-image-$version/packagename=sun8i-linux-image/g' scripts/package/builddeb
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=sun8i-linux-headers/g' scripts/package/builddeb
sed -i 's/packagename=linux-image-$version/packagename=sun8i-linux-image/g' scripts/package/mkdebian
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=sun8i-linux-headers/g' scripts/package/mkdebian
}

meson64_packaging(){
sed -i 's/packagename=linux-image-$version/packagename=meson64-linux-image/g' scripts/package/builddeb
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=meson64-linux-headers/g' scripts/package/builddeb
if [ -f scripts/package/mkdebian ]; then
	sed -i 's/packagename=linux-image-$version/packagename=meson64-linux-image/g' scripts/package/mkdebian;
	sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=meson64-linux-headers/g' scripts/package/mkdebian;
fi
if [[ `grep -w "fwpackagename=linux-firmware-image-$version" "scripts/package/builddeb"` ]]; then
	sed -i 's/fwpackagename=linux-firmware-image-$version/fwpackagename=meson64-linux-firmware/g' scripts/package/builddeb;
fi
}

meson8b_packaging(){
sed -i 's/packagename=linux-image-$version/packagename=meson8b-linux-image/g' scripts/package/builddeb
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=meson8b-linux-headers/g' scripts/package/builddeb
sed -i 's/packagename=linux-image-$version/packagename=meson8b-linux-image/g' scripts/package/mkdebian
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=meson8b-linux-headers/g' scripts/package/mkdebian
}

raspberrypi_packaging(){
sed -i 's/packagename=linux-image-$version/packagename=raspberrypi-linux-image/g' scripts/package/builddeb
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=raspberrypi-linux-headers/g' scripts/package/builddeb
sed -i 's/packagename=linux-image-$version/packagename=raspberrypi-linux-image/g' scripts/package/mkdebian
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=raspberrypi-linux-headers/g' scripts/package/mkdebian
}

rockchip_packaging(){
sed -i 's/packagename=linux-image-$version/packagename=rockchip64-linux-image/g' scripts/package/builddeb
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=rockchip64-linux-headers/g' scripts/package/builddeb
sed -i 's/packagename=linux-image-$version/packagename=rockchip64-linux-image/g' scripts/package/mkdebian
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=rockchip64-linux-headers/g' scripts/package/mkdebian
}

samsung_packaging(){
sed -i 's/packagename=linux-image-$version/packagename=exynos-linux-image/g' scripts/package/builddeb
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=exynos-linux-headers/g' scripts/package/builddeb
sed -i 's/packagename=linux-image-$version/packagename=exynos-linux-image/g' scripts/package/mkdebian
sed -i 's/kernel_headers_packagename=linux-headers-$version/kernel_headers_packagename=exynos-linux-headers/g' scripts/package/mkdebian
}

user_patches(){
if [[ `ls ../../${USERPATCHES}/*.patch` ]] > /dev/null 2>&1; then
	echo ""
	echo -e "${WHT}Applying user patches${FIN} ..."
	for i in ../../${USERPATCHES}/*.patch; do patch -p1 < $i; done;
	echo_done;
fi
}

log_setup(){
LOG_DIR="../../output/logs"
LOG_FILE="${LOG_DIR}/${BOARD}-patch.log"
if [ -e ${LOG_FILE} ]; then
	mv -f ${LOG_FILE} ${LOG_FILE}.1;
	echo "Linux ${VERSION}" > ${LOG_FILE};
	echo `date` >> ${LOG_FILE};
else
	mkdir -p ${LOG_DIR};
	echo "Linux ${VERSION}" > ${LOG_FILE};
	echo `date` >> ${LOG_FILE};
fi
}

# create dry run log
dryrun(){
log_setup
echo ""
echo -en "${WHT}Patching${FIN} ${PNK}[${FIN}${YLW}dry run${FIN}${PNK}]${FIN}";
# apply across all boards
if [[ -d "../../${LPATCHESALL}/${LINUX_VERSION}" ]]; then
	if [[ `ls ../../${LPATCHESALL}/${LINUX_VERSION}/*.patch` ]] > /dev/null 2>&1; then
		for i in ../../${LPATCHESALL}/${LINUX_VERSION}/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	fi
fi
if [[ "$FAMILY" == "allwinner" ]]; then
	for i in ../../${LINUX_PATCHDIR}/${LINUX_VERSION}/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
fi
if [[ "$BOARD" == "lepotato" ]]; then
	for i in ../../${LINUX_PATCHDIR}/${BOARD}/${LINUX_VERSION}/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	for i in ../../${LINUX_PATCHDIR}/all/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	if [[ "$LINUX_VERSION" == "5.15" ]]; then
		for i in ../../${LINUX_PATCHDIR}/misc/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	fi
fi
if [[ "$BOARD" == "radxazero" ]]; then
	for i in ../../${LINUX_PATCHDIR}/${BOARD}/${LINUX_VERSION}/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	for i in ../../${LINUX_PATCHDIR}/all/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	if [[ "$LINUX_VERSION" == "5.15" ]]; then
		for i in ../../${LINUX_PATCHDIR}/misc/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	fi
fi
if [[ "$FAMILY_EXT" == "odroid" ]]; then
	for i in ../../${LINUX_PATCHDIR}/${FAMILY_EXT}/${LINUX_VERSION}/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	for i in ../../${LINUX_PATCHDIR}/${FAMILY_EXT}/all/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	for i in ../../${LINUX_PATCHDIR}/all/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	if [[ "$LINUX_VERSION" == "5.15" ]]; then
		for i in ../../${LINUX_PATCHDIR}/misc/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	fi
fi
if [[ "$FAMILY" == "rockchip" ]]; then
	if [[ "$FAMILY_EXT" == "rk3328" ]] || [[ "$FAMILY_EXT" == "rk3399" ]]; then
		for i in ../../${LINUX_PATCHDIR}/${FAMILY_EXT}/${LINUX_VERSION}/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
		for i in ../../${LINUX_PATCHDIR}/all/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	fi
	if [[ "$FAMILY_EXT" == "rk356x" ]]; then
		for i in ../../${LINUX_PATCHDIR}/${FAMILY_EXT}/${BOARD}/${LINUX_VERSION}/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
		for i in ../../${LINUX_PATCHDIR}/all/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	fi
fi
if [[ "$FAMILY" == "samsung" ]] || [[ "$FAMILY_EXT" == "meson8b" ]]; then
	for i in ../../${LINUX_PATCHDIR}/${LINUX_VERSION}/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
fi
}

# check log and report
check(){
if [[ `grep "Skipping patch" "${LOG_FILE}"` ]]; then
	grep "Skipping patch" "${LOG_FILE}" | echo -en " ${PNK}[${FIN}"${WHT}skipping${FIN} ${WHT}`wc -l`${FIN}"${PNK}]${FIN}";
fi
if [[ `grep "FAILED" "${LOG_FILE}"` ]]; then
	grep "FAILED" "${LOG_FILE}" | echo -en " ${PNK}[${FIN}"${RED}fails${FIN} ${WHT}`wc -l`${FIN}"${PNK}]${FIN}";
	if [ $verbose -eq 1 ]; then
		exit 0;
	fi
fi
}

# apply patches
apply(){
echo "" >> ${LOG_FILE}
echo "# APPLYING PATCHES" >> ${LOG_FILE}
echo -e " ${PNK}[${FIN}${GRN}applying${FIN}${PNK}]${FIN}";
# apply across all boards
if [[ -d "../../${LPATCHESALL}/${LINUX_VERSION}" ]]; then
	if [[ `ls ../../${LPATCHESALL}/${LINUX_VERSION}/*.patch` ]] > /dev/null 2>&1; then
		for i in ../../${LPATCHESALL}/${LINUX_VERSION}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	fi
fi
if [[ "$FAMILY" == "allwinner" ]]; then
	for i in ../../${LINUX_PATCHDIR}/${LINUX_VERSION}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
fi
if [[ "$BOARD" == "lepotato" ]]; then
	for i in ../../${LINUX_PATCHDIR}/${BOARD}/${LINUX_VERSION}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	for i in ../../${LINUX_PATCHDIR}/all/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	if [[ "$LINUX_VERSION" == "5.15" ]]; then
		for i in ../../${LINUX_PATCHDIR}/misc/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	fi
fi
if [[ "$BOARD" == "radxazero" ]]; then
	for i in ../../${LINUX_PATCHDIR}/${BOARD}/${LINUX_VERSION}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	for i in ../../${LINUX_PATCHDIR}/all/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	if [[ "$LINUX_VERSION" == "5.15" ]]; then
		for i in ../../${LINUX_PATCHDIR}/misc/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	fi
fi
if [[ "$FAMILY_EXT" == "odroid" ]]; then
	for i in ../../${LINUX_PATCHDIR}/${FAMILY_EXT}/${LINUX_VERSION}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	for i in ../../${LINUX_PATCHDIR}/${FAMILY_EXT}/all/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	for i in ../../${LINUX_PATCHDIR}/all/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	if [[ "$LINUX_VERSION" == "5.15" ]]; then
		for i in ../../${LINUX_PATCHDIR}/misc/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	fi
fi
if [[ "$FAMILY" == "rockchip" ]]; then
	if [[ "$FAMILY_EXT" == "rk3328" ]] || [[ "$FAMILY_EXT" == "rk3399" ]]; then
		for i in ../../${LINUX_PATCHDIR}/${FAMILY_EXT}/${LINUX_VERSION}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
		for i in ../../${LINUX_PATCHDIR}/all/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	fi
	if [[ "$FAMILY_EXT" == "rk356x" ]]; then
		for i in ../../${LINUX_PATCHDIR}/${FAMILY_EXT}/${BOARD}/${LINUX_VERSION}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
		for i in ../../${LINUX_PATCHDIR}/all/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	fi
fi
if [[ "$FAMILY" == "samsung" ]] || [[ "$FAMILY_EXT" == "meson8b" ]]; then
	for i in ../../${LINUX_PATCHDIR}/${LINUX_VERSION}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
fi
}

# ALLWINNER
allwinner_patching(){
# packaging
if [[ "$FAMILY_EXT" == "sun8i" ]]; then
	sun8i_packaging;
fi
if [[ "$FAMILY_EXT" == "sun50i" ]]; then
	sun50i_packaging;
fi
# patching
dryrun; check; apply; user_patches;
cp -f ../../${PACKAGING}/headers-byteshift.patch headers-byteshift.patch
echo ""
}

# AMLOGIC
amlogic_patching(){
# packaging
if [[ "$VERSION" == "4.9.y" ]]; then
	patch -p1 < ../../${PACKAGING}/vendor-4.9-packaging.patch > /dev/null 2>&1;
fi
if [[ "$ARCH" == "arm" ]]; then
	meson8b_packaging;
fi
if [[ "$ARCH" == "arm64" ]]; then
	meson64_packaging;
fi
# patching
if [[ ! -z $REPO_KERNEL ]]; then
	user_patches;
else
	dryrun; check; apply; user_patches;
fi
cp -f ../../${PACKAGING}/headers-byteshift.patch headers-byteshift.patch
echo ""
}

## BROADCOM
raspberrypi_patching(){
# packaging
raspberrypi_packaging
# patching
user_patches
cp -f ../../${PACKAGING}/headers-byteshift.patch headers-byteshift.patch
echo ""
}

## ROCKCHIP
rockchip_patching(){
# packaging
if [[ "$VERSION" == "4.19.y" ]]; then
	patch -p1 < ../../${PACKAGING}/vendor-4.19-packaging.patch > /dev/null 2>&1;
fi
rockchip_packaging
# patching
if [[ ! -z $REPO_KERNEL ]]; then
	user_patches;
else
	dryrun; check; apply; user_patches;
fi
cp -f ../../${PACKAGING}/headers-byteshift.patch headers-byteshift.patch
echo ""
}

# SAMSUNG
samsung_patching(){
# packaging
samsung_packaging
# patching
dryrun; check; apply; user_patches;
cp -f ../../${PACKAGING}/headers-byteshift.patch headers-byteshift.patch
if [[ "$BOARD" == "odroidxu4" ]] && [[ -e "../../files/firmware/edid" ]]; then
	mkdir -p firmware
	cp -fr ../../files/firmware/edid firmware/;
fi
echo ""
}
