#!/bin/bash

uboot_configs(){
# boot logo
LOGODIR="drivers/video"
BOOTLOGO="files/boot/uboot/u_boot_logo.bmp"
BOOTLOGODIR="files/boot/uboot"
if [[ "$RANDOM_LOGO" == "true" ]] && [[ -f "../../${BOOTLOGO}" ]]; then
	ls ../../${BOOTLOGODIR}/u_boot_logo*.bmp | shuf -n 100 | xargs -I % cp % ${LOGODIR}/u_boot_logo.bmp
fi
if [[ "$RANDOM_LOGO" == "false" ]] && [[ -f "../../${BOOTLOGO}" ]]; then
	cp -f ../../${BOOTLOGO} ${LOGODIR}/
fi
# allwinner
if [[ "$FAMILY" == "allwinner" ]]; then
	echo "CONFIG_SD_BOOT=y" >> configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_EXT4_WRITE=y" >> configs/${UBOOT_DEFCONFIG}
	if [[ "$BOARD" == "cubietruck" ]]; then
		sed -i 's/CONFIG_DRAM_CLK=432/CONFIG_DRAM_CLK=384/g' configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_MMC_SUNXI_SLOT_EXTRA=2" >> configs/${UBOOT_DEFCONFIG}
	fi
	if [[ "$BOARD" == "pinea64plus" ]]; then
		# Autoboot options
		echo "CONFIG_BOOT_RETRY=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_BOOT_RETRY_TIME=5" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_BOOT_RETRY_MIN=5" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_RESET_TO_RETRY=y" >> configs/${UBOOT_DEFCONFIG}
	fi
fi
# amlogic
if [[ "$FAMILY" == "amlogic" ]]; then
	echo "CONFIG_SD_BOOT=y" >> configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_EXT4_WRITE=y" >> configs/${UBOOT_DEFCONFIG}
	if [[ "$BOARD" == "lepotato" ]]; then
		cp ../../${PRECOMPILED_UBOOT_DIR}/${BOARD}.bmp tools/logos/libre-computer.bmp
	fi
	if [[ "$BOARD" == "radxazero" ]]; then
		echo "CONFIG_BOOTDELAY=5" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_USE_PREBOOT=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_VIDEO_LOGO=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_BMP_16BPP=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_BMP_24BPP=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_BMP_32BPP=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_LZ4=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_LZO=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_LZMA=y" >> configs/${UBOOT_DEFCONFIG}
	fi
	if [[ "$BOARD" == "odroidn2" || "$BOARD" == "odroidn2l" || "$BOARD" == "odroidn2plus" ]]; then
		echo "CONFIG_CPU=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_SUPPORT_EMMC_RPMB=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_MMC_HS200_SUPPORT=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_SPL_MMC_HS200_SUPPORT=y" >> configs/${UBOOT_DEFCONFIG}
	fi
	if [[ "$BOARD" == "x96air" ]] && [[ "$UBOOT_VERSION" == "v2023.01" ]]; then
		# trouble shooting: show console output
		#echo "CONFIG_CONSOLE_MUX=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_SYS_CONSOLE_IS_IN_ENV=y" >> configs/${UBOOT_DEFCONFIG}
		if [[ -f "../../${PRECOMPILED_UBOOT_DIR}/${FAMILY_EXT}.bmp" ]]; then
			cp ../../${PRECOMPILED_UBOOT_DIR}/${FAMILY_EXT}.bmp tools/logos/
		fi
	fi
fi
# broadcom
if [[ "$FAMILY" == "broadcom" ]]; then
	echo "CONFIG_SD_BOOT=y" >> configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_EXT4_WRITE=y" >> configs/${UBOOT_DEFCONFIG}
fi
# freescale
if [[ "$FAMILY" == "freescale" ]]; then
	echo "CONFIG_SD_BOOT=y" >> configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_EXT4_WRITE=y" >> configs/${UBOOT_DEFCONFIG}
fi
# rockchip
if [[ "$FAMILY" == "rockchip" ]]; then
	echo "CONFIG_SD_BOOT=y" >> configs/${UBOOT_DEFCONFIG}
	echo "CONFIG_EXT4_WRITE=y" >> configs/${UBOOT_DEFCONFIG}
	if [[ "$FAMILY_EXT" == "rk3288" ]]; then
		echo "CONFIG_DM_RESET=y" >> configs/${UBOOT_DEFCONFIG}
	fi
	if [[ "$BOARD" == "renegade" ]]; then
		echo "CONFIG_USE_PREBOOT=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_BOARD_LATE_INIT=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_CMD_GPIO=y" >> configs/${UBOOT_DEFCONFIG}
	fi
	if [[ "$BOARD" == "nanopct4" ]]; then
		echo "CONFIG_MISC=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_PHY_ROCKCHIP_INNO_USB2=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_PHY_ROCKCHIP_TYPEC=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_USB_DWC3_GENERIC=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_DISPLAY_ROCKCHIP_EDP=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_OF_LIBFDT_OVERLAY=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_USE_PREBOOT=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_PCIE_DW_ROCKCHIP=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_ROCKCHIP_USB2_PHY=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_USB_DWC2=y" >> configs/${UBOOT_DEFCONFIG}
	fi
	if [[ "$BOARD" == "nanopir4se" ]]; then
		echo "CONFIG_MMC_IO_VOLTAGE=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_SPL_MMC_IO_VOLTAGE=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_MMC_UHS_SUPPORT=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_SPL_MMC_UHS_SUPPORT=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_MMC_HS200_SUPPORT=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_SPL_MMC_HS200_SUPPORT=y" >> configs/${UBOOT_DEFCONFIG}
	fi
	if [[ "$BOARD" == "rockpro64" || "$BOARD" == "pinebookpro" ]]; then
		echo "CONFIG_PCIE_DW_ROCKCHIP=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_OF_LIBFDT_OVERLAY=y" >> configs/${UBOOT_DEFCONFIG}
	fi
	if [[ "$FAMILY_EXT" == "rk356x" ]]; then
		echo "CONFIG_BOOTMETH_SCRIPT=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_OF_LIBFDT_OVERLAY=y" >> configs/${UBOOT_DEFCONFIG}
		echo "CONFIG_DM_VIDEO=y" >> configs/${UBOOT_DEFCONFIG}
		if [[ "$BOARD" == "nanopir5c" || "$BOARD" == "nanopir5s" ]]; then
			echo "CONFIG_MMC_IO_VOLTAGE=y" >> configs/${UBOOT_DEFCONFIG}
			echo "CONFIG_SPL_MMC_IO_VOLTAGE=y" >> configs/${UBOOT_DEFCONFIG}
			echo "CONFIG_MMC_UHS_SUPPORT=y" >> configs/${UBOOT_DEFCONFIG}
			echo "CONFIG_SPL_MMC_UHS_SUPPORT=y" >> configs/${UBOOT_DEFCONFIG}
		fi
	fi
fi
# samsung
if [[ "$FAMILY" == "samsung" ]]; then
	echo "CONFIG_SD_BOOT=y" >> configs/${UBOOT_DEFCONFIG}
fi
# add BTRFS support
if [[ `grep -w "CONFIG_FS_BTRFS=y" "configs/${UBOOT_DEFCONFIG}"` ]]; then :; else echo "CONFIG_FS_BTRFS=y" >> configs/${UBOOT_DEFCONFIG}; fi
if [[ `grep -w "CONFIG_CMD_BTRFS=y" "configs/${UBOOT_DEFCONFIG}"` ]]; then :; else echo "CONFIG_CMD_BTRFS=y" >> configs/${UBOOT_DEFCONFIG}; fi
}
