#!/bin/bash

opensbi_firmware (){
if [[ `wget -S --spider ${OPENSBI_URL} 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	if [[ -d "opensbi-${OPENSBI_TAG}" ]] && [[ -d "opensbi-${OPENSBI_TAG}.backup" ]]; then
		echo -en "${WHT}Opensbi ${OPENSBI_TAG}${FIN}"
		echo -en " ${PNK}[${FIN}${YLW}restoring${FIN}${PNK}]${FIN}"
		rm -fdr opensbi-${OPENSBI_TAG}
		echo -en " ${WHT}...${FIN}"
		mv -f opensbi-${OPENSBI_TAG}.backup opensbi-${OPENSBI_TAG}
		cd opensbi-${OPENSBI_TAG}
		if [[ "$VERBOSE" == "1" ]]; then git checkout ${OPENSBI_TAG}; git pull -q; else git checkout ${OPENSBI_TAG} &> /dev/null; git pull -q; fi
		make clean
		cd ..
		cp -r opensbi-${OPENSBI_TAG} opensbi-${OPENSBI_TAG}.backup
		echo -e " ${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}"
	else
		if [[ -d "opensbi-${OPENSBI_TAG}" ]]; then rm -fdr opensbi-${OPENSBI_TAG}; fi
		echo -en "${WHT}Opensbi ${OPENSBI_TAG}${FIN}"
		echo -en " ${PNK}[${FIN}${WHT}cloning${FIN}${PNK}]${FIN}"
		git clone -q -c advice.detachedHead=false ${OPENSBI_URL} -b ${OPENSBI_TAG} opensbi-${OPENSBI_TAG}
		if [[ -d "opensbi-${OPENSBI_TAG}" ]]; then
			cd opensbi-${OPENSBI_TAG}
			make clean
			cd ..
			echo -en " ${PNK}[${FIN}${WHT}creating backup${FIN}${PNK}]${FIN}"
			cp -r opensbi-${OPENSBI_TAG} opensbi-${OPENSBI_TAG}.backup
			echo -e " ${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}"
		else
			echo -e " ${PNK}[${FIN}${RED}failed${FIN}${PNK}]${FIN}"
			exit 1
		fi
	fi
fi
cd opensbi-${OPENSBI_TAG}
opensbi_patching
if [ $CROSSCOMPILE -eq 1 ]; then echo -e "${GRN}  CC${FIN}"; else echo -e "${GRN}  NC${FIN}"; fi
ubuild "PLATFORM=${OPENSBI_PLATFORM} PLATFORM_DEFCONFIG=${OPENSBI_DEFCONFIG}"
if [[ -f "${OPENSBI_FIRMWARE}" ]]; then :; else report_opensbi_error; fi
cd ..
echo ""
}

report_opensbi_error (){
echo "Missing firmware ${OPENSBI_FIRMWARE}. Please report build errors."
echo ""
exit 1
}
