#!/bin/bash

sources_list (){
SOURCES_LIST="${P_VALUE}/etc/apt/sources.list.d/${DISTRO}.sources"
}

mirrors (){
source mirror.txt
if [[ "$DISTRO" == "bianbu" ]]; then MIRROR="https://archive.spacemit.com/bianbu/"
elif [[ "$DISTRO" == "debian" ]]; then MIRROR="${DEBIAN_MIRROR}"
elif [[ "$DISTRO" == "devuan" ]]; then MIRROR="${DEVUAN_MIRROR}"
elif [[ "$DISTRO" == "kali" ]]; then MIRROR="${KALI_MIRROR}"
elif [[ "$DISTRO" == "ubuntu" ]]; then
	if [[ "$ARCH" == "x86" ]]; then MIRROR="${UBUNTU_AMD64_MIRROR}"; else MIRROR="${UBUNTU_MIRROR}"; fi
fi
}

# BIANBU
bianbu_release (){
# https://docs.bit-brick.com/docs/k1/os/desktop/bianbu_desktop_2.2
if [[ "$DISTRO_VERSION" =~ ^(noble)$ ]]; then
	tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
Suites: noble/snapshots/v2.3 noble-security/snapshots/v2.3 noble-updates/snapshots/v2.3 noble-porting/snapshots/v2.3 noble-customization/snapshots/v2.3 bianbu-v2.3-updates
Components: main universe restricted multiverse
Signed-By: /usr/share/keyrings/bianbu-archive-keyring.gpg
EOF
else
	echo -e "Only Bianbu Noble is supported at this time."
	exit 1
fi
}

# DEBIAN
debian_release (){
POOL="main contrib non-free non-free-firmware"
if [[ "$DISTRO_VERSION" =~ ^(bookworm|trixie|testing)$ ]]; then
	tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION} ${DISTRO_VERSION}-updates ${DISTRO_VERSION}-proposed-updates ${DISTRO_VERSION}-backports
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
URIs: ${MIRROR}-security
Suites: ${DISTRO_VERSION}-security
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF
else
	tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION}
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF
fi
}

# DEVUAN
devuan_release (){
POOL="main contrib non-free non-free-firmware"
if [[ "$DISTRO_VERSION" =~ ^(daedalus|excalibur)$ ]]; then
	tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION} ${DISTRO_VERSION}-updates ${DISTRO_VERSION}-proposed-updates ${DISTRO_VERSION}-backports
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/devuan-archive-keyring.gpg

Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION}-security
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/devuan-archive-keyring.gpg
EOF
else
	tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION}
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/devuan-archive-keyring.gpg
EOF
fi
}

# KALI
kali_release (){
# https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
POOL="main contrib non-free non-free-firmware"
tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_VERSION}
Components: ${POOL}
Enabled: yes
Signed-By: /usr/share/keyrings/kali-archive-keyring.gpg
EOF
}

# UBUNTU
ubuntu_release (){
tee ${SOURCES_LIST} <<EOF
Types: deb
URIs: ${MIRROR}
#Architectures: ${ARCH_EXT}
Suites: ${DISTRO_VERSION} ${DISTRO_VERSION}-updates ${DISTRO_VERSION}-backports
Components: main restricted universe multiverse
Enabled: yes
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: ${MIRROR}
#Architectures: ${ARCH_EXT}
Suites: ${DISTRO_VERSION}-security
Components: main restricted universe multiverse
Enabled: yes
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
EOF
if [[ "$ARCH" == "x86" ]]; then sed -i 's/#Architectures/Architectures/g' ${SOURCES_LIST}; fi
}

choose_release (){
if [[ "$DISTRO" =~ ^(bianbu|debian|devuan|kali|raspbian|ubuntu)$ ]]; then
	${DISTRO}_release
else
	echo "${CAP_DISTRO} ${CAP_RELEASE} is not supported."
	exit 0
fi
}
