#!/bin/bash

debian_stable(){
rm -f ${RELEASE}
tee ${RELEASE} <<EOF
deb http://deb.debian.org/debian ${DISTRO_VERSION} main contrib non-free
deb http://deb.debian.org/debian ${DISTRO_VERSION}-updates main contrib non-free
deb http://deb.debian.org/debian ${DISTRO_VERSION}-proposed-updates main contrib non-free
deb http://deb.debian.org/debian-security ${DISTRO_VERSION}-security main contrib non-free
deb http://deb.debian.org/debian ${DISTRO_VERSION}-backports main contrib non-free
EOF
}

debian_unstable(){
rm -f ${RELEASE}
tee ${RELEASE} <<EOF
deb http://deb.debian.org/debian ${DISTRO_VERSION} main contrib non-free
EOF
}

devuan_stable(){
rm -f ${RELEASE}
tee ${RELEASE} <<EOF
deb http://deb.devuan.org/merged ${DISTRO_VERSION} main contrib non-free
deb http://deb.devuan.org/merged ${DISTRO_VERSION}-updates main contrib non-free
deb http://deb.devuan.org/devuan ${DISTRO_VERSION}-proposed-updates main contrib non-free
deb http://deb.devuan.org/merged ${DISTRO_VERSION}-security main contrib non-free
deb http://deb.devuan.org/merged ${DISTRO_VERSION}-backports main contrib non-free
EOF
}

devuan_unstable(){
rm -f ${RELEASE}
tee ${RELEASE} <<EOF
deb http://deb.devuan.org/merged ${DISTRO_VERSION} main contrib non-free
EOF
}

kali_rolling(){
rm -f ${RELEASE}
tee ${RELEASE} <<EOF
deb http://http.kali.org/kali ${DISTRO_VERSION} main contrib non-free
EOF
}

ubuntu_release(){
rm -f ${RELEASE}
tee ${RELEASE} <<EOF
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION} main restricted
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-updates main restricted
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION} universe
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-updates universe
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION} multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-updates multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-backports main restricted universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-security main restricted
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-security universe
deb http://ports.ubuntu.com/ubuntu-ports/ ${DISTRO_VERSION}-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu ${DISTRO_VERSION} partner
# deb-src http://archive.canonical.com/ubuntu ${DISTRO_VERSION} partner
EOF
}

choose_release(){
if [[ "$DISTRO" == "debian" ]]; then
	if [[ "$DISTRO_VERSION" == "bullseye" ]]; then
		debian_stable;
	else
		debian_unstable;
	fi
fi
if [[ "$DISTRO" == "devuan" ]]; then
	if [[ "$DISTRO_VERSION" == "chimaera" ]]; then
		devuan_stable;
	else
		devuan_unstable;
	fi
fi
if [[ "$DISTRO" == "kali" ]]; then
	if [[ "$DISTRO_VERSION" == "kali-rolling" ]]; then
		kali_rolling;
	fi
fi
if [[ "$DISTRO" == "ubuntu" ]]; then
	ubuntu_release;
fi
}
