#!/bin/bash

# may need to run emmc bootloader recovery on the module before flashing the img
# https://wiki.odroid.com/accessory/emmc/recovery_xu4
flash_uboot(){
dd if=${OUTPUT}/bl1.bin of="${IMAGE_LOOP_DEV}" seek=1 conv=fsync
dd if=${OUTPUT}/bl2.bin of="${IMAGE_LOOP_DEV}" seek=31 conv=fsync
dd if=${OUTPUT}/u-boot.bin of="${IMAGE_LOOP_DEV}" seek=63 conv=fsync
dd if=${OUTPUT}/tzsw.bin of="${IMAGE_LOOP_DEV}" seek=1503 conv=fsync
dd if=/dev/zero of="${IMAGE_LOOP_DEV}" seek=2015 bs=512 count=32 conv=fsync
}
