#!/bin/bash

shrink (){
export LC_ALL=C.UTF-8
if [[ -f "${IMAGE_FILE_NAME}" ]]; then mv -f ${IMAGE_FILE_NAME} shrink.img; else echo "Shrink failed! Missing file ${IMAGE_FILE_NAME}."; exit 0; fi
KPARTX="$(kpartx -av shrink.img)"
if [[ "$HOST_MACHINE" == "Ubuntu" ]]; then
	# snapd woes; grep for higher loop numbers.
	LOOP=`grep -o 'loop[0-9]\+p.' <<<"$KPARTX"`
else
	LOOP=`grep -o 'loop.p.' <<<"$KPARTX"`
fi
sleep .25
if [[ "$P_VALUE" == "p1" ]]; then shrink_p1; fi
if [[ "$P_VALUE" == "p2" ]]; then shrink_p2; fi
}

calculate (){
DU=`du -sh ${ROOTFS_LABEL} | sed "s/${ROOTFS_LABEL}//g" | sed s/'\s'//g | sed 's/G//g'`
if [[ "$P_VALUE" == "p1" ]]; then CALC=$(echo $DU + 0.6 | bc | sed 's/\.//g'); fi
if [[ "$P_VALUE" == "p2" ]]; then CALC=$(echo $DU + 1.0 | bc | sed 's/\.//g'); fi
GB=$(echo $CALC | head -c 1)
if [[ "$P_VALUE" == "p1" ]]; then
	if [[ "$GB" == "1" ]]; then CALC=$(echo $DU + 0.5 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "2" ]]; then :; fi
	if [[ "$GB" == "3" ]]; then CALC=$(echo $DU + 0.7 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "4" ]]; then CALC=$(echo $DU + 0.8 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "5" ]]; then CALC=$(echo $DU + 0.9 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "6" ]]; then CALC=$(echo $DU + 1.0 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "7" ]]; then CALC=$(echo $DU + 1.1 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "8" ]]; then CALC=$(echo $DU + 1.2 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "9" ]]; then CALC=$(echo $DU + 1.3 | bc | sed 's/\.//g'); fi
fi
if [[ "$P_VALUE" == "p2" ]]; then
	if [[ "$GB" == "1" ]]; then CALC=$(echo $DU + 0.9 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "2" ]]; then :; fi
	if [[ "$GB" == "3" ]]; then CALC=$(echo $DU + 1.2 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "4" ]]; then CALC=$(echo $DU + 1.3 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "5" ]]; then CALC=$(echo $DU + 1.4 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "6" ]]; then CALC=$(echo $DU + 1.5 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "7" ]]; then CALC=$(echo $DU + 1.6 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "8" ]]; then CALC=$(echo $DU + 1.7 | bc | sed 's/\.//g'); fi
	if [[ "$GB" == "9" ]]; then CALC=$(echo $DU + 1.8 | bc | sed 's/\.//g'); fi
fi
IMGSIZE="${CALC}00MB"
}

shrink_p1 (){
ROOTFS_LOOP="/dev/mapper/$LOOP"
ROOTFS="${ROOTFS_LOOP}"
if [[ "$FSTYPE" == "ext4" ]]; then fsck.${FSTYPE} -pf "$ROOTFS" > /dev/null 2>&1; fi
mkdir -p ${ROOTFS_LABEL}
sleep .50
mount "${ROOTFS}" ${ROOTFS_LABEL}
sleep 1
calculate
if [ $RAM -ne 0 ]; then IMAGE_FOLDER="ram/"; fi
mkdir -p "$IMAGE_FOLDER"
if [ $RAM -ne 0 ]; then mount -t tmpfs -o size=4G tmpfs $IMAGE_FOLDER; fi
partition > /dev/null 2>&1
uuid
echo -en "Resizing image to"
sleep 1
echo -en " ${IMGSIZE}:"
if [ $VERBOSE -eq 1 ]; then cp -axv ${ROOTFS_LABEL}/* p1/; else cp -ax ${ROOTFS_LABEL}/* p1/; fi
sleep .75
echo -en " Finishing"
umount ${ROOTFS_LABEL}
sleep .75
rm -fdr ${ROOTFS_LABEL}
kpartx -d shrink.img
sleep .50
rm -f shrink.img
if [[ "$EXTLINUX" == "true" ]] && [[ "$EFI" == "false" ]]; then extlinux > /dev/null 2>&1; fi
if [[ "$BOOTCMD" == "true" ]] && [[ "$EFI" == "false" ]]; then bootcmd > /dev/null 2>&1; fi
if [[ "$BOOTINI" == "true" ]] && [[ "$EFI" == "false" ]]; then bootini > /dev/null 2>&1; fi
p1_fstab > /dev/null 2>&1
umount p1
sleep .50
if [[ "$FSTYPE" == "ext4" ]]; then fsck.${FSTYPE} -pf "${IMAGE_LOOP_DEV_ROOTFS}" > /dev/null 2>&1; fi
losetup -d "${IMAGE_LOOP_DEV}"
mv "${IMAGE_FOLDER}${IMAGE_FILE_NAME}" "${IMAGE_FILE_NAME}"
if [ $RAM -ne 0 ]; then umount "${IMAGE_FOLDER}"; fi
rmdir "${IMAGE_FOLDER}"
rmdir p1
echo -e ", done."
}

shrink_p2 (){
B_LOOP=`echo "$LOOP" | sed -n '1p'`
R_LOOP=`echo "$LOOP" | sed -n '2p'`
BOOT_LOOP="/dev/mapper/$B_LOOP"
ROOTFS_LOOP="/dev/mapper/$R_LOOP"
if [[ "$EFI" == "true" ]]; then EFI_BOOT="${BOOT_LOOP}"; else BOOT="${BOOT_LOOP}"; fi
ROOTFS="${ROOTFS_LOOP}"
if [[ "$FSTYPE" == "ext4" ]]; then fsck.${FSTYPE} -pf "$ROOTFS" > /dev/null 2>&1; fi
if [[ "$EFI" == "true" ]]; then mkdir -p EFI; else mkdir -p BOOT; fi
mkdir -p ${ROOTFS_LABEL}
sleep .50
if [[ "$EFI" == "true" ]]; then mount "${EFI_BOOT}" EFI; else mount "${BOOT}" BOOT; fi
sleep 1
mount "${ROOTFS}" ${ROOTFS_LABEL}
sleep 1
calculate
if [ $RAM -ne 0 ]; then IMAGE_FOLDER="ram/"; fi
mkdir -p "$IMAGE_FOLDER"
if [ $RAM -ne 0 ]; then mount -t tmpfs -o size=4G tmpfs $IMAGE_FOLDER; fi
partition > /dev/null 2>&1
uuid
echo -en "Resizing image to"
sleep 1
echo -en " ${IMGSIZE}:"
if [[ "$EFI" == "true" ]] then cp -fr EFI/* p1/; else cp -fr BOOT/* p1/; fi
if [ $VERBOSE -eq 1 ]; then
	if [[ "$FSTYPE" == "btrfs" ]]; then cp -axv ${ROOTFS_LABEL}/@/* p2/; else cp -axv ${ROOTFS_LABEL}/* p2/; fi
else
	if [[ "$FSTYPE" == "btrfs" ]]; then cp -ax ${ROOTFS_LABEL}/@/* p2/; else cp -ax ${ROOTFS_LABEL}/* p2/; fi
fi
sleep .75
echo -en " Finishing"
if [[ "$EFI" == "true" ]]; then umount EFI; else umount BOOT; fi
umount ${ROOTFS_LABEL}
sleep .75
rm -fdr BOOT EFI; rm -fdr ${ROOTFS_LABEL}
kpartx -d shrink.img
sleep .50
rm -f shrink.img
if [[ "$EXTLINUX" == "true" ]] && [[ "$EFI" == "false" ]]; then extlinux > /dev/null 2>&1; fi
if [[ "$BOOTCMD" == "true" ]] && [[ "$EFI" == "false" ]]; then bootcmd > /dev/null 2>&1; fi
if [[ "$PETITBOOT" == "true" ]] && [[ "$EFI" == "false" ]]; then odroid_bootcmd > /dev/null 2>&1; fi
if [[ "$BOOTINI" == "true" ]] && [[ "$EFI" == "false" ]]; then bootini > /dev/null 2>&1; fi
if [[ "$FAMILY" == "broadcom" ]] && [[ "$EFI" == "false" ]]; then brcm_cmdline; config_dot_txt; fi
p2_fstab > /dev/null 2>&1
umount p2; umount p1
sleep .50
if [[ "$FSTYPE" == "ext4" ]]; then fsck.${FSTYPE} -pf "${IMAGE_LOOP_DEV_ROOTFS}" > /dev/null 2>&1; fi
losetup -d "${IMAGE_LOOP_DEV}"
mv "${IMAGE_FOLDER}${IMAGE_FILE_NAME}" "${IMAGE_FILE_NAME}"
if [ $RAM -ne 0 ]; then umount "${IMAGE_FOLDER}"; fi
rmdir "${IMAGE_FOLDER}"
rmdir p1 p2
echo -e ", done."
}
