#!/bin/bash

# shrink image
shrink(){
if [[ "$GPT" == "false" ]]; then
	chmod +x scripts/shrink;
	scripts/shrink -s ${DEVICE_SOC}-${DISTRO}-${DISTRO_VERSION}-${IMAGE_DATE}.img;
fi
if [[ "$P_VALUE" == "p1" ]]; then
	p1_kpartx;
fi
if [[ "$P_VALUE" == "p2" ]]; then
	if [[ "$EFI" == "true" ]]; then
		:;
	else
		p2_kpartx;
	fi
fi
}

find_p1_partuuid(){
if [ -f part-uuid.txt ]; then rm -f part-uuid.txt; fi
ROOTFS="${ROOTFS_LOOP}"
ROOT_PARTUUID=$(blkid -o export -- ${ROOTFS} | sed -ne 's/^PARTUUID=//p')
echo ROOT_PARTUUID='"'$ROOT_PARTUUID'"' > part-uuid.txt
source part-uuid.txt
}

p1_kpartx(){
if [[ "$P_ROOTFS" == "p1" ]]; then
	echo 'ROOTFS_LOOP="/dev/mapper/' > kpart1;
	echo '"' > kpart3;
fi
if [[ "$P_ROOTFS" == "p2" ]]; then
	echo 'LOOP1="/dev/mapper/' > kpart1;
	echo 'ROOTFS_LOOP="/dev/mapper/' >> kpart1;
	echo '"' > kpart3;
	echo '"' >> kpart3;
fi
IMAGE_FILE="${DEVICE_SOC}-${DISTRO}-${DISTRO_VERSION}-${IMAGE_DATE}.img"
kpartx="$(kpartx -av $IMAGE_FILE)"
echo "$kpartx"
if [[ `grep -w "VERSION_CODENAME=jammy" "/etc/os-release"` ]]; then
	# snapd woes; grep for higher loop numbers
	grep -o 'loop[0-9]\+p.' <<<"$kpartx" > kpart2;
else
	grep -o 'loop.p.' <<<"$kpartx" > kpart2;
fi
paste -d '\0' kpart1 kpart2 kpart3 > kpart.txt
rm -f {kpart1,kpart2,kpart3}
source kpart.txt
ROOTFS="${ROOTFS_LOOP}"
mkdir -p p1
sleep 1s
mount "${ROOTFS}" p1
find_p1_partuuid
echo ""
p1_extlinux
# default_bootcmd
sleep 1s
echo ""
umount p1
rm -fdr p1
kpartx -d ${IMAGE_FILE}
rm -f kpart.txt
}

find_p2_partuuid(){
if [ -f part-uuid.txt ]; then rm -f part-uuid.txt; fi
ROOTFS="${ROOTFS_LOOP}"
ROOT_UUID=$(blkid -o export -- ${ROOTFS} | sed -ne 's/^UUID=//p')
ROOT_PARTUUID=$(blkid -o export -- ${ROOTFS} | sed -ne 's/^PARTUUID=//p')
echo ROOT_UUID='"'$ROOT_UUID'"' > part-uuid.txt
echo ROOT_PARTUUID='"'$ROOT_PARTUUID'"' >> part-uuid.txt
source part-uuid.txt
}

p2_kpartx(){
echo 'BOOT_LOOP="/dev/mapper/' > kpart1
echo 'ROOTFS_LOOP="/dev/mapper/' >> kpart1
IMAGE_FILE="${DEVICE_SOC}-${DISTRO}-${DISTRO_VERSION}-${IMAGE_DATE}.img"
kpartx="$(kpartx -av $IMAGE_FILE)"
echo "$kpartx"
if [[ `grep -w "VERSION_CODENAME=jammy" "/etc/os-release"` ]]; then
	# snapd woes; grep for higher loop numbers
	grep -o 'loop[0-9]\+p.' <<<"$kpartx" > kpart2;
else
	grep -o 'loop.p.' <<<"$kpartx" > kpart2;
fi
echo '"' > kpart3
echo '"' >> kpart3
paste -d '\0' kpart1 kpart2 kpart3 > kpart.txt
rm -f {kpart1,kpart2,kpart3}
source kpart.txt
BOOT="${BOOT_LOOP}"
mkdir -p p1
sleep 1s
mount "${BOOT}" p1
find_p2_partuuid
echo ""
if [ $petitboot -eq 1 ]; then
	odroid_bootcmd;
fi
if [[ "$FAMILY" == "broadcom" ]]; then
	extlinux-conf;
	config-txt > /dev/null 2>&1;
fi
if [[ "$BOARD" == "odroidc1" ]]; then
	odroid_bootini;
fi
echo ""
sleep 1s
umount p1
rm -fdr p1
kpartx -d ${IMAGE_FILE}
rm -f kpart.txt
}
