#!/bin/bash

# setup patch log
log_setup(){
LOG_DIR="../../output/logs"
LOG_FILE="${LOG_DIR}/${BOARD}-u-boot-patch.log"
if [[ -f "${LOG_FILE}" ]]; then
	mv -f ${LOG_FILE} ${LOG_FILE}.1;
	echo "U-Boot ${UBOOT_VERSION}" > ${LOG_FILE};
	echo `date` >> ${LOG_FILE};
else
	mkdir -p ${LOG_DIR};
	echo "U-Boot ${UBOOT_VERSION}" > ${LOG_FILE};
	echo `date` >> ${LOG_FILE};
fi
}

uboot_patching(){
# dry run
if [[ -d "../../${UBOOT_PATCHDIR}/${UBOOT_VERSION}/${BOARD}" ]] || [[ -d "../../${UBOOT_PATCHDIR}/${UBOOT_VERSION}/${FAMILY_EXT}" ]]; then
	log_setup;
	echo "";
	echo -en "${WHT}Patching${FIN} ${PNK}[${FIN}${YLW}dry run${FIN}${PNK}]${FIN}";
	if [[ `ls ../../${UBOOT_PATCHDIR}/${UBOOT_VERSION}/${BOARD}/*.patch` ]] > /dev/null 2>&1; then
		for i in ../../${UBOOT_PATCHDIR}/${UBOOT_VERSION}/${BOARD}/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	fi
	if [[ `ls ../../${UBOOT_PATCHDIR}/${UBOOT_VERSION}/${FAMILY_EXT}/*.patch` ]] > /dev/null 2>&1; then
		for i in ../../${UBOOT_PATCHDIR}/${UBOOT_VERSION}/${FAMILY_EXT}/*.patch; do patch --dry-run -N -p1 < $i; done >> ${LOG_FILE};
	fi
fi
# check log and report
if [[ -f "${LOG_FILE}" ]]; then
	if [[ `grep "Skipping patch" "${LOG_FILE}"` ]]; then
		grep "Skipping patch" "${LOG_FILE}" | echo -en " ${PNK}[${FIN}"${WHT}skipping${FIN} ${WHT}`wc -l`${FIN}"${PNK}]${FIN}";
	fi
	if [[ `grep "FAILED" "${LOG_FILE}"` ]]; then
		grep "FAILED" "${LOG_FILE}" | echo -en " ${PNK}[${FIN}"${RED}fails${FIN} ${WHT}`wc -l`${FIN}"${PNK}]${FIN}";
		if [ $verbose -eq 1 ]; then
			exit 0;
		fi
	fi
fi
# apply patches
if [[ -d "../../${UBOOT_PATCHDIR}/${UBOOT_VERSION}/${BOARD}" ]] || [[ -d "../../${UBOOT_PATCHDIR}/${UBOOT_VERSION}/${FAMILY_EXT}" ]]; then
	echo "" >> ${LOG_FILE}
	echo "# APPLYING PATCHES" >> ${LOG_FILE}
	echo -e " ${PNK}[${FIN}${GRN}applying${FIN}${PNK}]${FIN}";
	if [[ `ls ../../${UBOOT_PATCHDIR}/${UBOOT_VERSION}/${BOARD}/*.patch` ]] > /dev/null 2>&1; then
		for i in ../../${UBOOT_PATCHDIR}/${UBOOT_VERSION}/${BOARD}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	fi
	if [[ `ls ../../${UBOOT_PATCHDIR}/${UBOOT_VERSION}/${FAMILY_EXT}/*.patch` ]] > /dev/null 2>&1; then
		for i in ../../${UBOOT_PATCHDIR}/${UBOOT_VERSION}/${FAMILY_EXT}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
	fi
fi
if [[ `ls ../../${UPATCHESALL}/*.patch` ]] > /dev/null 2>&1; then
	for i in ../../${UPATCHESALL}/*.patch; do patch -N -p1 < $i; done >> ${LOG_FILE};
fi
}
