#!/bin/bash

uboot-source(){
mkdir -p ${SRC}
cp -f board.txt ${SRC}/
cd ${SRC}
rm -fdr {amlogic-boot-fip-master,rkbin-master,blobs/amlogic-u-boot,u-boot}
}

uboot_search(){
if [[ `wget -S --spider https://github.com/pyavitz/debian-image-builder/releases/download/u-boot/u-boot-${UBOOT_VERSION}.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	echo -en "${WHT}u-boot-${UBOOT_VERSION}${FIN} ";
	echo -en "${PNK}[${FIN}${WHT}downloading${FIN}${PNK}]${FIN} ";
	aria2c -q https://github.com/pyavitz/debian-image-builder/releases/download/u-boot/u-boot-${UBOOT_VERSION}.tar.gz
	echo_bdone;
else
	uboot_searching;
fi
}

uboot_searching(){
if [[ `wget -S --spider https://source.denx.de/u-boot/u-boot/-/archive/${UBOOT_VERSION}/u-boot-${UBOOT_VERSION}.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	echo -en "${WHT}u-boot-${UBOOT_VERSION}${FIN} ";
	echo -en "${PNK}[${FIN}${WHT}downloading${FIN}${PNK}]${FIN} ";
	aria2c -q https://source.denx.de/u-boot/u-boot/-/archive/${UBOOT_VERSION}/u-boot-${UBOOT_VERSION}.tar.gz
	echo_bdone;
else
	echo ""
	echo -e "${WHT}Version selected is not available.${FIN}"
	exit;
fi
}

u-boot(){
if [[ -f "u-boot-${UBOOT_VERSION}.tar.gz" ]]; then
	echo -en "${WHT}u-boot-${UBOOT_VERSION}${FIN} ";
	echo -e "${PNK}[${FIN}${YLW}found${FIN}${PNK}]${FIN}";
else
	uboot_search;
fi
# extract
echo ""
echo_extract
if [[ "$FAMILY" == "amlogic" ]]; then
	if [[ -f "amlogic-boot-fip-master.tar.gz" ]]; then
		pv amlogic-boot-fip-master.tar.gz | tar -xzf - -C .;
	fi
fi
if [[ "$FAMILY_EXT" == "rk356x" ]]; then
	if [[ -f rkbin-master.tar.gz ]]; then
		pv rkbin-master.tar.gz | tar -xzf - -C .;
	fi
fi
pv u-boot-${UBOOT_VERSION}.tar.gz | tar -xzf - -C .
mv -f u-boot-${UBOOT_VERSION} u-boot
# arm trusted firmware
if [[ "$FAMILY" == "allwinner" ]]; then
	if [[ "$ARCH" == "arm64" ]]; then
		cp arm-trusted-firmware/build/${ATF_PLAT}/debug/bl31.bin u-boot/bl31.bin;
	fi
fi
if [[ "$FAMILY" == "rockchip" ]]; then
	if [[ "$FAMILY_EXT" == "rk3328" ]] || [[ "$FAMILY_EXT" == "rk3399" ]]; then
		cp arm-trusted-firmware/build/${ATF_PLAT}/release/bl31/bl31.elf u-boot/bl31.elf;
	fi
	if [[ "$FAMILY_EXT" == "rk356x" ]]; then
		cp -f ${RKBIN_ELF} u-boot/bl31.elf;
		cp -f ${RKBIN_RAM} u-boot/ram_init.bin;
	fi
fi
# patching
cp board.txt u-boot/
cd u-boot
uboot_patching
# make defconfig
echo ""
export ARCH=${ARCH}
uboot_configs
if [ $crosscompile -eq 1 ]; then
	echo -e "${GRN}  CC${FIN}"
	make -j${CORES} CC=${CROSS} CROSS_COMPILE=${CROSS_COMPILE} ${UBOOT_DEFCONFIG};
else
	echo -e "${GRN}  NC${FIN}"
	make -j${CORES} CC=${NATIVE} ${UBOOT_DEFCONFIG};
fi
# menuconfig
if [ $menuconfig -eq 1 ]; then
	if [ $crosscompile -eq 1 ]; then
		echo -e "${GRN}  CC${FIN}"
		make -j${CORES} CC=${CROSS} CROSS_COMPILE=${CROSS_COMPILE} menuconfig;
	else
		echo -e "${GRN}  NC${FIN}"
		make -j${CORES} CC=${NATIVE} menuconfig;
	fi
fi
# compile
echo
echo_cuboot
if [ $crosscompile -eq 1 ]; then
	echo -e "${GRN}  CC${FIN}"
	make -j${CORES} CC=${CROSS} CROSS_COMPILE=${CROSS_COMPILE};
else
	echo -e "${GRN}  NC${FIN}"
	make -j${CORES} CC=${NATIVE};
fi
}

# allwinner
allwinner-uboot-string(){
uboot-source
if [[ "$ARCH" == "arm64" ]]; then
	arm-trusted-firmware;
fi
u-boot
if [[ -f "u-boot-sunxi-with-spl.bin" ]]; then
	mkdir -p ../../${OUTPUT}
	cp -f u-boot-sunxi-with-spl.bin ../../${OUTPUT}/
	cp -f tools/mkimage ../../${OUTPUT}/
	echo_done
	echo "";
else
	echo "Something went wrong? Please report."
	echo ""
	exit 1;
fi
}

# amlogic
amlogic-uboot-string(){
uboot-source
amlogic-boot-fips
u-boot
if [[ ! -z $RUN_FIP ]]; then
	echo "$DEFAULT_MOTD : Firmware Image Package" | sed 's/ :/:/g'
	${RUN_FIP};
fi
if [[ -f "fip/u-boot.bin" ]]; then
	mkdir -p ../../${OUTPUT}
	cp -f fip/u-boot.bin ../../${OUTPUT}
	cp -f fip/u-boot.bin.sd.bin ../../${OUTPUT}
	cp -f tools/mkimage ../../${OUTPUT}
	echo_done
	echo "";
else
	echo "Something went wrong? Please report."
	echo ""
	exit 1;
fi
}

# broadcom
bcm2711-uboot-string(){
uboot-source
u-boot
if [[ -f "u-boot.bin" ]]; then
	mkdir -p ../../${OUTPUT}
	cp -f u-boot.bin ../../${OUTPUT}/
	echo_done
	echo "";
else
	echo "Something went wrong? Please report."
	echo ""
	exit 1;
fi
}

# rockchip
rockchip-uboot-string(){
uboot-source
if [[ "$FAMILY_EXT" == "rk3328" ]] || [[ "$FAMILY_EXT" == "rk3399" ]]; then
	arm-trusted-firmware;
fi
if [[ "$FAMILY_EXT" == "rk356x" ]]; then
	rkbin;
fi
u-boot
if [[ -f "idbloader.img" ]]; then
	mkdir -p ../../${OUTPUT}
	cp -f idbloader.img ../../${OUTPUT}/idbloader.bin
	cp -f u-boot.itb ../../${OUTPUT}/
	echo_done
	echo "";
else
	echo "Something went wrong? Please report."
	echo ""
	exit 1;
fi
}

# samsung
samsung-uboot-string(){
uboot-source
u-boot
if [[ -f "u-boot.bin" ]]; then
	mkdir -p ../../${OUTPUT}
	cp -f u-boot.bin ../../${OUTPUT}/
	cp -f ../../${CUBOOT}/bl1.bin ../../${OUTPUT}/
	cp -f ../../${CUBOOT}/bl2.bin ../../${OUTPUT}/
	cp -f ../../${CUBOOT}/tzsw.bin ../../${OUTPUT}/
	echo_done
	echo "";
else
	echo "Something went wrong? Please report."
	echo ""
	exit 1;
fi
}
