#!/bin/bash

uboot-source(){
mkdir -p ${SRC}
if [[ -f "board.txt" ]]; then
	# I don't think this is needed
	cp -f board.txt ${SRC}/
fi
cd ${SRC}
if [[ -d "u-boot-${UBOOT_VERSION}" ]]; then
	rm -fdr u-boot-${UBOOT_VERSION}
fi
rm -fdr {amlogic-boot-fip-master,rkbin-master,blobs/amlogic-u-boot,u-boot}
}

uboot_search(){
if [[ `wget -S --spider https://github.com/pyavitz/debian-image-builder/releases/download/u-boot/u-boot-${UBOOT_VERSION}.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	echo -en "${WHT}u-boot-${UBOOT_VERSION}${FIN} "
	echo -en "${PNK}[${FIN}${WHT}downloading${FIN}${PNK}]${FIN} "
	aria2c -q https://github.com/pyavitz/debian-image-builder/releases/download/u-boot/u-boot-${UBOOT_VERSION}.tar.gz
	echo_bdone
else
	uboot_searching
fi
}

uboot_searching(){
if [[ `wget -S --spider https://source.denx.de/u-boot/u-boot/-/archive/${UBOOT_VERSION}/u-boot-${UBOOT_VERSION}.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	echo -en "${WHT}u-boot-${UBOOT_VERSION}${FIN} "
	echo -en "${PNK}[${FIN}${WHT}downloading${FIN}${PNK}]${FIN} "
	aria2c -q https://source.denx.de/u-boot/u-boot/-/archive/${UBOOT_VERSION}/u-boot-${UBOOT_VERSION}.tar.gz
	echo_bdone
else
	echo ""
	echo -e "${WHT}Version selected is not available.${FIN}"
	exit 0
fi
}

u-boot(){
if [[ -f "u-boot-${UBOOT_VERSION}.tar.gz" ]]; then
	echo -en "${WHT}u-boot-${UBOOT_VERSION}${FIN} "
	echo -e "${PNK}[${FIN}${YLW}found${FIN}${PNK}]${FIN}"
else
	uboot_search
fi
# extract
echo ""
echo_extract
if [[ "$FAMILY" == "amlogic" ]] && [[ -f "amlogic-boot-fip-master.tar.gz" ]]; then
	pv amlogic-boot-fip-master.tar.gz | tar -xzf - -C .
fi
if [[ "$FAMILY_EXT" == "rk356x" ]] && [[ -f "rkbin-master.tar.gz" ]]; then
	pv rkbin-master.tar.gz | tar -xzf - -C .
fi
if [[ -f "u-boot-${UBOOT_VERSION}.tar.gz" ]]; then
	pv u-boot-${UBOOT_VERSION}.tar.gz | tar -xzf - -C .
	mv -f u-boot-${UBOOT_VERSION} u-boot
else
	echo -e "Missing u-boot-${UBOOT_VERSION} tarball."
	exit 0
fi
# arm trusted firmware
if [[ "$FAMILY" == "allwinner" ]] && [[ "$ARCH" == "arm64" ]]; then
	cp arm-trusted-firmware/build/${ATF_PLAT}/debug/bl31.bin u-boot/bl31.bin
fi
if [[ "$FAMILY" == "rockchip" ]]; then
	if [[ "$FAMILY_EXT" == "rk3328" || "$FAMILY_EXT" == "rk3399" ]]; then
		cp arm-trusted-firmware/build/${ATF_PLAT}/release/bl31/bl31.elf u-boot/bl31.elf
	fi
	if [[ "$FAMILY_EXT" == "rk356x" ]]; then
		cp -f ${RKBIN_ELF} u-boot/bl31.elf
		cp -f ${RKBIN_RAM} u-boot/ram_init.bin
	fi
fi
# patching
cp board.txt u-boot/
cd u-boot
uboot_patching
# make defconfig
echo ""
export ARCH=${ARCH}
uboot_configs
if [ $crosscompile -eq 1 ]; then
	echo -e "${GRN}  CC${FIN}"
	make -j${CORES} CC=${CROSS} CROSS_COMPILE=${CROSS_COMPILE} ${UBOOT_DEFCONFIG}
else
	echo -e "${GRN}  NC${FIN}"
	make -j${CORES} CC=${NATIVE} ${UBOOT_DEFCONFIG}
fi
# menuconfig
if [ $menuconfig -eq 1 ]; then
	if [ $crosscompile -eq 1 ]; then
		echo -e "${GRN}  CC${FIN}"
		make -j${CORES} CC=${CROSS} CROSS_COMPILE=${CROSS_COMPILE} menuconfig
	else
		echo -e "${GRN}  NC${FIN}"
		make -j${CORES} CC=${NATIVE} menuconfig
	fi
fi
# compile
echo
echo_cuboot
if [ $crosscompile -eq 1 ]; then
	echo -e "${GRN}  CC${FIN}"
	make -j${CORES} CC=${CROSS} CROSS_COMPILE=${CROSS_COMPILE}
else
	echo -e "${GRN}  NC${FIN}"
	make -j${CORES} CC=${NATIVE}
fi
}

# allwinner
allwinner-uboot-string(){
uboot-source
if [[ "$ARCH" == "arm64" ]]; then
	arm-trusted-firmware
fi
u-boot
if [[ -f "u-boot-sunxi-with-spl.bin" ]]; then
	mkdir -p ../../${OUTPUT}
	cp -f u-boot-sunxi-with-spl.bin ../../${OUTPUT}/
	uboot_packaging
	echo ""
else
	echo "Something went wrong? Please report."
	exit 0
fi
}

# amlogic
amlogic-uboot-string(){
uboot-source
amlogic-boot-fips
u-boot
if [[ ! -z $RUN_FIP ]]; then
	echo "$DEFAULT_MOTD : Firmware Image Package" | sed 's/ :/:/g'
	${RUN_FIP}
fi
if [[ -f "fip/u-boot.bin" ]]; then
	mkdir -p ../../${OUTPUT}
	cp -f fip/u-boot.bin ../../${OUTPUT}
	cp -f fip/u-boot.bin.sd.bin ../../${OUTPUT}
	uboot_packaging
	echo ""
else
	echo "Something went wrong? Please report."
	echo ""
	exit 0
fi
}

# broadcom
broadcom-uboot-string(){
uboot-source
u-boot
if [[ -f "u-boot.bin" ]]; then
	mkdir -p ../../${OUTPUT}
	cp -f u-boot.bin ../../${OUTPUT}/
	uboot_packaging
	echo ""
else
	echo "Something went wrong? Please report."
	echo ""
	exit 0
fi
}

# freescale
freescale-uboot-string(){
uboot-source
u-boot
if [[ -f "u-boot.img" ]]; then
	mkdir -p ../../${OUTPUT}
	cp -f SPL ../../${OUTPUT}/sploader.bin
	cp -f u-boot.img ../../${OUTPUT}/u-boot.bin
	uboot_packaging
	echo ""
else
	echo "Something went wrong? Please report."
	echo ""
	exit 0
fi
}

# rockchip
rockchip-uboot-string(){
uboot-source
if [[ "$FAMILY_EXT" == "rk3328" || "$FAMILY_EXT" == "rk3399" ]]; then
	arm-trusted-firmware
fi
if [[ "$FAMILY_EXT" == "rk356x" ]]; then
	rkbin
fi
u-boot
if [[ -f "idbloader.img" ]]; then
	mkdir -p ../../${OUTPUT}
	if [[ "$ARCH" == "arm" ]]; then
		cp -f idbloader.img ../../${OUTPUT}/idbloader.bin
		cp -f u-boot.bin u-boot.itb
		cp -f u-boot.itb ../../${OUTPUT}/
		uboot_packaging
		echo ""
	else
		cp -f idbloader.img ../../${OUTPUT}/idbloader.bin
		cp -f u-boot.itb ../../${OUTPUT}/
		uboot_packaging
		echo ""
	fi
else
	echo "Something went wrong? Please report."
	echo ""
	exit 0
fi
}

# samsung
samsung-uboot-string(){
uboot-source
u-boot
if [[ -f "u-boot.bin" ]]; then
	mkdir -p ../../${OUTPUT}
	cp -f u-boot.bin ../../${OUTPUT}/
	cp -f ../../${PRECOMPILED_UBOOT_DIR}/bl1.bin ../../${OUTPUT}/
	cp -f ../../${PRECOMPILED_UBOOT_DIR}/bl2.bin ../../${OUTPUT}/
	cp -f ../../${PRECOMPILED_UBOOT_DIR}/tzsw.bin ../../${OUTPUT}/
	uboot_packaging
	echo ""
else
	echo "Something went wrong? Please report."
	echo ""
	exit 0
fi
}
