#!/bin/bash

driver_download (){
if [[ -d "${DRIVER}" ]]; then
	echo -en "${PNK}[${FIN}${YLW}found${FIN}${PNK}]${FIN}"
	cd ${DRIVER}
	git config pull.rebase false
	echo -en " ${PNK}[${FIN}${WHT}pulling${FIN}${PNK}]${FIN}"
	git pull -q
	cd ..
else
	echo -en "${PNK}[${FIN}${WHT}cloning${FIN}${PNK}]${FIN}"
	git clone -q ${DRIVER_URL} ${DRIVER}
fi
}

# RTL8189ES
add_rtl8189es (){
rm -fdr drivers/net/wireless/realtek/rtl8189es
mkdir -p drivers/net/wireless/realtek/rtl8189es
cp -R ../rtl8189es/{core,hal,include,os_dep,platform} drivers/net/wireless/realtek/rtl8189es
cp -R ../rtl8189es/Makefile drivers/net/wireless/realtek/rtl8189es/Makefile
cp -R ../rtl8189es/Kconfig drivers/net/wireless/realtek/rtl8189es/Kconfig
echo "obj-\$(CONFIG_RTL8189ES) += rtl8189es/" >> drivers/net/wireless/realtek/Makefile
sed -i 's/---help---/help/g' drivers/net/wireless/realtek/rtl8189es/Kconfig
sed -i '/source "drivers\/net\/wireless\/realtek\/rtl818x\/Kconfig"/a source "drivers\/net\/wireless\/realtek\/rtl8189es\/Kconfig"' \
	"drivers/net/wireless/realtek/Kconfig"
}

# RTL8852BS
add_rtl8852bs (){
rm -fdr drivers/net/wireless/realtek/${DRIVER}
mkdir -p drivers/net/wireless/realtek/${DRIVER}
cp -fr ../${DRIVER}/* drivers/net/wireless/realtek/${DRIVER}/
rm -f drivers/net/wireless/realtek/${DRIVER}/README.md
echo "obj-\$(CONFIG_RTL8852BS)		+= rtl8852bs/" >> drivers/net/wireless/realtek/Makefile
sed -i '/source "drivers\/net\/wireless\/realtek\/rtl818x\/Kconfig"/a source "drivers\/net\/wireless\/realtek\/rtl8852bs\/Kconfig"' \
	"drivers/net/wireless/realtek/Kconfig"
}

extra_wireless (){
if [[ "$BOARD" == "bananapif3" ]]; then
	DRIVER_INFO="Realtek 8852BS"
	DRIVER="rtl8852bs"
	DRIVER_URL="https://github.com/pyavitz/rtl8852bs.git"
fi
if [[ "$BOARD" == "orangepir1" ]]; then
	DRIVER_INFO="Realtek 8189ES"
	DRIVER="rtl8189es"
	DRIVER_URL="https://github.com/jwrdegoede/rtl8189ES_linux"
fi
if [[ -v "DRIVER" ]] && [[ ! -z "$DRIVER" ]]; then
	echo -en "${WHT}${DRIVER_INFO}${FIN} "
	driver_download
	echo -e " ${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}"
fi
}
