#!/bin/bash

report_error (){
if [ $RTW88 -eq 1 ] && [ $RTW88_DEVEL -eq 1 ]; then
	echo -e "Both RTW88 and RTW88_DEVEL can not be enabled."
	exit 1
fi
}

driver_download (){
if [[ -d "${DRIVER}" ]]; then
	echo -en "${WHT}${DRIVER_INFO}${FIN} "
	echo -en "${PNK}[${FIN}${YLW}found${FIN}${PNK}]${FIN}"
	cd ${DRIVER}
	git config pull.rebase false
	echo -en " ${PNK}[${FIN}${WHT}pulling${FIN}${PNK}]${FIN}"
	git pull -q
	cd ..
	echo -e " ${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}"
else
	echo -en "${PNK}[${FIN}${WHT}cloning${FIN}${PNK}]${FIN}"
	git clone -q ${DRIVER_URL} ${DRIVER}
	echo -e " ${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}"
fi
}

extra_wireless (){
report_error
# RTL8189ES
if [[ "$BOARD" == "orangepir1" ]]; then
	DRIVER_INFO="Realtek 8189ES"
	DRIVER="rtl8189es"
	DRIVER_URL="https://github.com/jwrdegoede/${DRIVER}_linux.git"
	driver_download
	rm -fdr ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	mkdir -p ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	cp -fr ${DRIVER}/{core,hal,include,os_dep,platform} ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	cp -fr ${DRIVER}/{Kconfig,Makefile} ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}/
	echo "obj-\$(CONFIG_RTL8189ES) += rtl8189es/" >> ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/Makefile
	cat <<EOF > ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}/Kconfig
config RTL8189ES
	tristate "Realtek 8189E SDIO support"
	depends on USB
	default m
	help
	  Help message of RTL8189ES
EOF
	sed -i '/source "drivers\/net\/wireless\/realtek\/rtl818x\/Kconfig"/a source "drivers\/net\/wireless\/realtek\/rtl8189es\/Kconfig"' \
		"${KERNEL}-${VERSION}/drivers/net/wireless/realtek/Kconfig"
fi

# RTL8821CU
if [[ "$BOARD" == "bananapim4zero" ]]; then
	DRIVER_INFO="Realtek 8821CU"
	DRIVER="rtl8821cu"
	DRIVER_URL="https://github.com/morrownr/8821cu-20210916.git"
	driver_download
	rm -fdr ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	mkdir -p ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	cp -fr ${DRIVER}/{core,hal,include,os_dep,platform} ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	cp -fr ${DRIVER}/{Kconfig,Makefile,halmac.mk,rtl8821c.mk} ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	echo "obj-\$(CONFIG_RTL8821CU) += rtl8821cu/" >> ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/Makefile
	cat <<EOF > ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}/Kconfig
config RTL8821CU
	tristate "Realtek 8821C USB support"
	depends on USB
	default m
	help
	  Help message of RTL8821CU
EOF
	sed -i "s/CONFIG_RTW_DEBUG = y/CONFIG_RTW_DEBUG = n/g" ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}/Makefile
	sed -i '/source "drivers\/net\/wireless\/realtek\/rtl818x\/Kconfig"/a source "drivers\/net\/wireless\/realtek\/rtl8821cu\/Kconfig"' \
		"${KERNEL}-${VERSION}/drivers/net/wireless/realtek/Kconfig"
fi

# RTL8852BS
if [[ "$BOARD" == "bananapif3" ]]; then
	DRIVER_INFO="Realtek 8852BS"
	DRIVER="rtl8852bs"
	DRIVER_URL="https://github.com/pyavitz/${DRIVER}.git"
	driver_download
	rm -fdr ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	mkdir -p ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	cp -fr ${DRIVER}/* ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}/
	rm -f ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}/README.md
	echo "obj-\$(CONFIG_RTL8852BS)		+= rtl8852bs/" >> ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/Makefile
	sed -i '/source "drivers\/net\/wireless\/realtek\/rtl818x\/Kconfig"/a source "drivers\/net\/wireless\/realtek\/rtl8852bs\/Kconfig"' \
		"${KERNEL}-${VERSION}/drivers/net/wireless/realtek/Kconfig"
fi

# RTW88
if [ $RTW88 -eq 1 ]; then
	DRIVER_INFO="RTW88"
	DRIVER="rtw88"
	DRIVER_URL="https://github.com/lwfinger/${DRIVER}.git"
	driver_download
	rm -fdr ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	mkdir -p ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}
	cp -fr ${DRIVER}/* ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}/
	rm -fdr ${KERNEL}-${VERSION}/drivers/net/wireless/realtek/${DRIVER}/{alt_rtl8821ce,README.md}
fi
}
