#!/bin/bash
clear -x

read -p "Overclocking requires proper cooling, are you sure [y/n]? " -n 1 -r
echo    # (optional) move to a new line
if [ "$REPLY" != "y" ]; then
    exit 1
fi

echo "Enabling overclocking"
echo "overclock=1" | sudo tee /etc/opt/overclock.txt
sudo service tweaks restart
sleep 3
