#!/bin/bash
clear -x

read -p "You are about to set locales and timezone, are you sure [y/n]? " -n 1 -r
echo    # (optional) move to a new line
if [ "$REPLY" != "y" ]; then
    exit 1
fi

echo "Setting locales and timezone"
sudo dpkg-reconfigure locales tzdata
sleep 3
