#!/bin/bash
RED="\e[0;31m"
FIN="\e[0m"

NAME=""
user=""
passwd=""
MOTD="Debian"
HOSTNAME="computer"
DISTRO="debian"
DISTRO_VERSION="bullseye"
UBOOT_VERSION="v2021.10"
VERSION="5.15.6"
BUILD_VERSION="1"
menuconfig="0"
rc="0"
COMPILER="gcc-10"
crosscompile="1"
ccache="0"
rtl88XXau="0"
rtl88X2bu="0"
rtl88XXcu="0"
custom_defconfig="0"
MYCONFIG=""

# open fd
exec 3>&1

# Store data to $VALUES variable
VALUES=$(dialog --ok-label "Submit" --no-cancel \
	  --backtitle "Debian Image Builder" \
	  --title "Config Menu" \
	  --form "Choose:" \
0 40 0 \
	"Name:"		1 1	"$NAME" 		1 7 27 0 \
	"Username:"	2 1	"$user" 		2 11 22 0 \
	"Password:"	3 1	"$passwd"  		3 11 22 0 \
	"Branding:"	4 1	"$MOTD"			4 11 22 0 \
	"Hostname:"	5 1	"$HOSTNAME"		5 11 22 0 \
	""		6 1	""	 		6 14 0 0 \
	"Distribution"	7 1	""	 		7 14 0 0 \
	"Distro:"	8 1	"$DISTRO"	  	8 9 24 0 \
	"Release:"	9 1	"$DISTRO_VERSION"  	9 10 23 0 \
	""		10 1	""	 		10 14 0 0 \
        "U-Boot:"   	11 1    "$UBOOT_VERSION"        11 9 10 0 \
        "Branch:"   	12 1    "$VERSION"        	12 9 10 0 \
        "Build:"   	13 1    "$BUILD_VERSION"        13 8 4 0 \
        "RC:"   	14 1    "$rc"	        	14 5 2 0 \
	"Menuconfig:"	15 1	"$menuconfig"  		15 13 2 0 \
	"Compiler:"	16 1	"$COMPILER"  		16 11 9 0 \
	"Crosscompile:" 17 1	"$crosscompile" 	17 15 2 0 \
	"Caching on:"	18 1	"$ccache"	 	18 13 2 0 \
	""		19 1	""	 		19 14 0 0 \
	"Wireless"	20 1	""	 		20 14 0 0 \
	"rtl88XXau:"	21 1	"$rtl88XXau"	 	21 12 2 0 \
	"rtl88X2bu:"	22 1	"$rtl88X2bu"	 	22 12 2 0 \
	"rtl88XXcu:"	23 1	"$rtl88XXcu"	 	23 12 2 0 \
	""		24 1	""	 		24 14 0 0 \
	"Customize"	25 1	""	 		25 14 0 0 \
	"Defconfig:"	26 1	"$custom_defconfig" 	26 12 2 0 \
	"Name:"		27 1	"$MYCONFIG"	  	27 7 27 0 \
2>&1 1>&3)

# close fd
exec 3>&-

# convert into vars
echo "$VALUES" > tmp1
echo NAME='"' > tmp0
echo user='"' >> tmp0
echo passwd='"' >> tmp0
echo MOTD='"' >> tmp0
echo HOSTNAME='"' >> tmp0
echo DISTRO='"' >> tmp0
echo DISTRO_VERSION='"' >> tmp0
echo UBOOT_VERSION='"' >> tmp0
echo VERSION='"' >> tmp0
echo BUILD_VERSION='"' >> tmp0
echo rc= >> tmp0
echo menuconfig= >> tmp0
echo COMPILER='"' >> tmp0
echo crosscompile= >> tmp0
echo ccache= >> tmp0
echo rtl8812au= >> tmp0
echo rtl88x2bu= >> tmp0
echo rtl8811cu= >> tmp0
echo custom_defconfig= >> tmp0
echo MYCONFIG='"' >> tmp0
echo emmc=0 >> tmp0
echo verbose=0 >> tmp0
echo auto=1 >> tmp0
echo aircrack=0 >> tmp0
echo CFLAGS='"''"' >> tmp0
echo KBUSER='"'marvin'"' >> tmp0
echo KBHOST='"'martian'"' >> tmp0
echo "set_locales(){" >> tmp0
echo "apt install -y locales" >> tmp0
echo "export LANGUAGE=en_US.UTF-8" >> tmp0
echo "export LANG=en_US.UTF-8" >> tmp0
echo "export LC_ALL=C.UTF-8" >> tmp0
echo "locale-gen en_US.UTF-8" >> tmp0
echo "}" >> tmp0
echo "set_timezone(){" >> tmp0
echo "ln -snf /usr/share/zoneinfo/America/New_York /etc/localtime" >> tmp0
echo "echo -n 'America/New_York' > /etc/timezone" >> tmp0
echo "}" >> tmp0
echo 'NAMESERVER1="8.8.8.8"' >> tmp0
echo 'NAMESERVER2="8.8.4.4"' >> tmp0
echo builder=3.1 >> tmp0
echo '"' > tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo >> tmp2
echo >> tmp2
echo '"' >> tmp2
echo >> tmp2
echo >> tmp2
echo >> tmp2
echo >> tmp2
echo >> tmp2
echo >> tmp2
echo _defconfig'"' >> tmp2
paste -d '\0' tmp0 tmp1 tmp2  > userdata.txt
rm -f tmp0 tmp1 tmp2

# categories
sed -i '1i### USER INFORMATION' userdata.txt
sed -i '7i### DISTRIBUTION AND RELEASE' userdata.txt
sed -i '10i### UBOOT AND LINUX KERNEL' userdata.txt
sed -i '19i### WIRELESS' userdata.txt
sed -i '23i### CUSTOM' userdata.txt
sed -i '30i### COMPILER TUNING' userdata.txt
sed -i '32i### WHOAMI AND HOST' userdata.txt
sed -i '35i### LOCALES' userdata.txt
sed -i '43i### TIMEZONE' userdata.txt
sed -i '48i### NAME SERVER' userdata.txt
sed -i '51i### DO NOT EDIT BELOW THIS LINE' userdata.txt

# clear screen
clear

# userdata
echo -e "${RED}userdata file created${FIN}."
