#!/bin/bash
source lib/boards/$1
source userdata.txt
MAKE_OUTPUT="output/$1"
BTITLE=`echo $FAMILY: $DEFAULT_MOTD | sed -e 's/\(.*\)/\U\1/'`
TITLE=`echo $DEFAULT_MOTD`
DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

while true; do
	exec 3>&1
	selection=$(dialog \
	--backtitle "$BTITLE" \
	--title "$TITLE" \
	--clear \
	--cancel-label "Exit" \
	--menu "Select:" $HEIGHT $WIDTH 4 \
	"1" "Make All (Feeling lucky?)" \
	"2" "Make Das U-Boot" \
	"3" "Make Linux Kernel" \
	"4" "Make Root Filesystem" \
	"5" "Make Flashable Image" \
	2>&1 1>&3)
	exit_status=$?
	exec 3>&-;
case $exit_status in
	$DIALOG_CANCEL)
		clear
		echo "Program terminated."
		exit
		;;
	$DIALOG_ESC)
		clear
		echo "Program aborted." >&2
		exit 1
		;;
esac
case $selection in
	0 )
		clear
		echo "Program terminated."
		;;
	1 )
		if [ $logging -eq 1 ]; then
			echo LOGNAME=$1 > logger.txt
			echo 'LOGFILE="$LOGNAME-all"' >> logger.txt
			./scripts/loggit make "all" "board=$1"
		else
			make "all" "board=$1"
		fi
		dialog --prgbox "Results:" "ls $IMG_EXP *$ARCH_EXT* $MAKE_OUTPUT/" 30 75
		exit 0
		;;
	2 )
		if [ $logging -eq 1 ]; then
			echo LOGNAME=$1 > logger.txt
			echo 'LOGFILE="$LOGNAME-u-boot"' >> logger.txt
			./scripts/loggit make "uboot" "board=$1"
		else
			make "uboot" "board=$1"
		fi

		# check rockchip u-boot binaries
		if [ -e $MAKE_OUTPUT/*.itb ]; then
			dialog --prgbox "Results:" "ls $MAKE_OUTPUT/*.bin; ls $MAKE_OUTPUT/*.itb" 30 75;
		else
			dialog --prgbox "Results:" "ls $MAKE_OUTPUT/*.bin" 30 75;
		fi
		;;
	3 )
		if [ $logging -eq 1 ]; then
			echo LOGNAME=$1 > logger.txt
			echo 'LOGFILE="$LOGNAME-linux"' >> logger.txt
			./scripts/loggit make "kernel" "board=$1"
		else
			make "kernel" "board=$1"
		fi
		dialog --prgbox "Results:" "ls $MAKE_OUTPUT/*.deb" 30 75
		;;
	4 )
		if [ $logging -eq 1 ]; then
			echo LOGNAME=$1 > logger.txt
			echo 'LOGFILE="$LOGNAME-rootfs"' >> logger.txt
			./scripts/loggit make "rootfs" "board=$1"
		else
			make "rootfs" "board=$1"
		fi
		dialog --prgbox "Results:" "ls *$ARCH_EXT*" 30 75
		;;
	5 )
		if [ $logging -eq 1 ]; then
			echo LOGNAME=$1 > logger.txt
			echo 'LOGFILE="$LOGNAME-image"' >> logger.txt
			./scripts/loggit make "image" "board=$1"
		else
			make "image" "board=$1"
		fi
		dialog --prgbox "Results:" "ls $IMG_EXP" 30 75
		;;
esac
done
