#!/bin/bash

boardnames(){
if [[ "$choice" == "1" ]]; then
	BOARD="lepotato"
fi
if [[ "$choice" == "2" ]]; then
	BOARD="nanopc"
fi
if [[ "$choice" == "3" ]]; then
	BOARD="nanopim1"
fi
if [[ "$choice" == "4" ]]; then
	BOARD="nanopineo"
fi
if [[ "$choice" == "5" ]]; then
	BOARD="nanopi"
fi
if [[ "$choice" == "6" ]]; then
	BOARD="odroidc4"
fi
if [[ "$choice" == "7" ]]; then
	BOARD="odroidhc1"
fi
if [[ "$choice" == "8" ]]; then
	BOARD="odroidm1"
fi
if [[ "$choice" == "9" ]]; then
	BOARD="odroidn2"
fi
if [[ "$choice" == "10" ]]; then
	BOARD="odroidn2plus"
fi
if [[ "$choice" == "11" ]]; then
	BOARD="opione"
fi
if [[ "$choice" == "12" ]]; then
	BOARD="opipc"
fi
if [[ "$choice" == "13" ]]; then
	BOARD="pine64"
fi
if [[ "$choice" == "14" ]]; then
	BOARD="radxazero"
fi
if [[ "$choice" == "15" ]]; then
	BOARD="raspi4"
fi
if [[ "$choice" == "16" ]]; then
	BOARD="renegade"
fi
if [[ "$choice" == "17" ]]; then
	BOARD="rock64"
fi
if [[ "$choice" == "18" ]]; then
	BOARD="rockpro64"
fi
if [[ "$choice" == "19" ]]; then
	BOARD="tritium"
fi
}
