dtb-y += amlogic-t7-a311d2-khadas-vim4.dtb
dtb-y += amlogic-t7-a311d2-khadas-vim4n.dtb
# overlays
dtb-y += 4k2k_fb.dtbo
dtb-y += i2cm_a.dtbo
dtb-y += i2s.dtbo
dtb-y += onewire.dtbo
dtb-y += pwm_f.dtbo
dtb-y += spi0.dtbo
#dtb-y += ext_board.dtbo
dtb-y += i2cm_f.dtbo
dtb-y += panfrost.dtbo
dtb-y += spdifout.dtbo
dtb-y += uart_e.dtbo
