#!/bin/bash

if [[ -f "/etc/opt/board.txt" ]]; then
	. /etc/opt/board.txt
else
	exit 0
fi
if [[ -f "/etc/opt/overclock.txt" ]]; then
	. /etc/opt/overclock.txt
else
	echo "overclock=0" > /etc/opt/overclock.txt
	. /etc/opt/overclock.txt
fi

if [[ "$BOARD" == "bananapicm4" || "$BOARD" == "bananapim2s" ]]; then
	if [ $overclock -eq 1 ]; then
		echo 2016000 > /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
		echo 2400000 > /sys/devices/system/cpu/cpufreq/policy2/scaling_max_freq
	else
		echo 1908000 > /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
		echo 2208000 > /sys/devices/system/cpu/cpufreq/policy2/scaling_max_freq
	fi
fi

if [[ "$BOARD" == "bananapim2pro" || "$BOARD" == "bananapim5" ]]; then
	if [ $overclock -eq 1 ] && [[ -e "/sys/devices/system/cpu/cpufreq/boost" ]]; then
		echo "1" > /sys/devices/system/cpu/cpufreq/boost
		governor -r
	fi
fi

if [[ -e "/sys/class/net/eth0/queues/rx-0/rps_cpus" ]] && [[ `grep -w "0f" "/sys/class/net/eth0/queues/rx-0/rps_cpus"` ]]; then
	:;
else
	echo "f" > /sys/class/net/eth0/queues/rx-0/rps_cpus
fi

# HACK: if linux 5.15; then bring up bluetooth; fi
KERNEL_RELEASE=`ls /boot/config-* | sed 's/\/boot\/config-//g' | sed 's/....$//'`
if [[ "$KERNEL_RELEASE" == "5.15" ]]; then
	if [[ -e "/sys/bus/serial/drivers/hci_uart_h5/serial0-0" ]]; then
		sleep .50
		echo -n "serial0-0" > /sys/bus/serial/drivers/hci_uart_h5/unbind
		sleep .50
		echo -n "serial0-0" > /sys/bus/serial/drivers/hci_uart_h5/bind
	fi
fi

exit 0
