#!/bin/bash

if [[ -f "/etc/opt/board.txt" ]]; then
	. /etc/opt/board.txt
else
	exit 0
fi
if [[ -f "/etc/opt/overclock.txt" ]]; then
	. /etc/opt/overclock.txt
else
	echo "overclock=0" > /etc/opt/overclock.txt
	. /etc/opt/overclock.txt
fi

if [[ "$BOARD" == "bananapicm4" ]]; then
	if [ $overclock -eq 1 ]; then
		echo 2016000 > /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
		echo 2400000 > /sys/devices/system/cpu/cpufreq/policy2/scaling_max_freq
	else
		echo 1908000 > /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
		echo 2208000 > /sys/devices/system/cpu/cpufreq/policy2/scaling_max_freq
	fi
fi

if [[ "$BOARD" == "bananapim5" ]]; then
	if [ $overclock -eq 1 ] && [[ -e "/sys/devices/system/cpu/cpufreq/boost" ]]; then
		echo "1" > /sys/devices/system/cpu/cpufreq/boost
		governor -r
	fi
fi

if [[ -e "/sys/class/net/eth0/queues/rx-0/rps_cpus" ]] && [[ `grep -w "0f" "/sys/class/net/eth0/queues/rx-0/rps_cpus"` ]]; then
	:;
else
	echo "f" > /sys/class/net/eth0/queues/rx-0/rps_cpus
fi

exit 0
