#!/bin/bash
# Need to restart auto-negotiation on ethernet

if [[ -f "/sys/class/net/eth0/carrier" ]] && [[ `grep "1" /sys/class/net/eth0/carrier` ]]; then
	if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
		:;
	else
		sleep 5; ethtool -r eth0;
	fi
fi
