#!/bin/bash
# OrangePi 3 tweaks

if [[ -f "/etc/opt/board.txt" ]]; then
	. /etc/opt/board.txt
else
	exit 0
fi
if [[ -f "/etc/opt/overclock.txt" ]]; then
	. /etc/opt/overclock.txt
else
	echo 'overclock="0"' > /etc/opt/overclock.txt
	. /etc/opt/overclock.txt
fi
if [[ -f "/sys/devices/system/cpu/cpufreq/boost" ]]; then
	if [ $overclock -eq 1 ]; then
		echo "1" > /sys/devices/system/cpu/cpufreq/boost
		governor -r
	else
		echo "0" > /sys/devices/system/cpu/cpufreq/boost
		governor -r
	fi
fi

if [[ "$BOARD" == "orangepi3lts" ]]; then
	# Disable hung_task_timeout_secs
	# Prevent kernel panic and hang ups caused by the unisoc wifi driver
	if [[ -f "/proc/sys/kernel/hung_task_timeout_secs" ]]; then echo "0" > /proc/sys/kernel/hung_task_timeout_secs; fi
	if [[ -f "/usr/local/sbin/hciattach_opi" ]]; then
		rfkill unblock all; sleep .50; hciattach_opi -s 1500000 /dev/ttyBT0 sprd
	fi
fi

exit 0
