#!/bin/bash
# OrangePi 3 LTS tweaks

# Disable hung_task_timeout_secs
# Prevent kernel panic and hang ups caused by the unisoc wifi driver
if [[ -f "/proc/sys/kernel/hung_task_timeout_secs" ]]; then echo "0" > /proc/sys/kernel/hung_task_timeout_secs; fi

exit 0
