#!/bin/bash

if [[ -f "/etc/opt/board.txt" ]]; then
	. /etc/opt/board.txt
else
	exit 0
fi
if [[ -f "/etc/opt/overclock.txt" ]]; then
	. /etc/opt/overclock.txt
else
	echo 'overclock="0"' > /etc/opt/overclock.txt
	. /etc/opt/overclock.txt
fi

# Overclock
if [[ "$SERIES" == "rk3566" ]] && [[ -f "/sys/devices/system/cpu/cpufreq/boost" ]]; then
	if [ $overclock -eq 1 ]; then
		echo "1" > /sys/devices/system/cpu/cpufreq/boost
		governor -r
	else
		echo "0" > /sys/devices/system/cpu/cpufreq/boost
		governor -r
	fi
fi

exit 0
