#!/bin/bash

if [[ -f "/etc/opt/board.txt" ]]; then
	. /etc/opt/board.txt
else
	exit 0
fi
if [[ -f "/etc/opt/overclock.txt" ]]; then
	. /etc/opt/overclock.txt
else
	echo 'overclock="0"' > /etc/opt/overclock.txt
	. /etc/opt/overclock.txt
fi

# Disable hung_task_timeout_secs
if [[ -f "/proc/sys/kernel/hung_task_timeout_secs" ]]; then echo "0" > /proc/sys/kernel/hung_task_timeout_secs; fi

if [ $overclock -eq 1 ] && [[ -e "/sys/devices/system/cpu/cpufreq/boost" ]]; then
	echo "1" > /sys/devices/system/cpu/cpufreq/boost
	governor -r
else
	echo "0" > /sys/devices/system/cpu/cpufreq/boost
	governor -r
fi

exit 0
