#!/bin/bash

if [[ -e "/sys/bus/serial/drivers/hci_uart_h5/serial0-0" ]]; then
	sleep .50
	echo -n "serial0-0" > /sys/bus/serial/drivers/hci_uart_h5/unbind
	sleep .50
	echo -n "serial0-0" > /sys/bus/serial/drivers/hci_uart_h5/bind
fi

exit 0
