#!/bin/bash

# architecture
ARCH="riscv"
ARCH_EXT="riscv64"
DEBARCH=""
CROSS_COMPILE="${ARCH_EXT}-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-${ARCH_EXT}-static"

# device information
SERIES="k1"
FAMILY="spacemit"
FAMILY_EXT=""
DTB="${SERIES}-bananapi-f3"

# default config
LINUX_DEFCONFIG="k1_defconfig"
UBOOT_DEFCONFIG="k1_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="8192"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# output
BOARD="bananapif3"
OUTPUT="output/${BOARD}"

# extlinux
BOOT_KERNEL="Image"
BOOT_INITRD="uInitrd"
FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="earlycon=sbi console=tty1 console=ttyS0,115200 console=both"
LOGLEVEL="loglevel=5"
EXTRA="net.ifnames=0"

# motd
DEFAULT_MOTD="BananaPi F3"

# customize
#MODULES_BLACKLIST="hci_uart"
MODULES_LOAD="8852bs"

# opensbi firmware
OPENSBI_URL="https://gitee.com/bianbu-linux/opensbi.git"
OPENSBI_TAG="bl-v2.0.y"
OPENSBI_PLATFORM="generic"
OPENSBI_DEFCONFIG="k1_defconfig"
OPENSBI_FIRMWARE="build/platform/${OPENSBI_PLATFORM}/firmware/fw_dynamic.itb"
OPENSBI_PATCHDIR="patches/opensbi/${OPENSBI_TAG}/${BOARD}"

# kernel
LINUX_EXTRA_FIRMWARE="files/firmware/${FAMILY}/esos.elf"

# patches
LINUX_PATCHING="false"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git (https://gitee.com/bianbu-linux/linux-6.6.git)
FORCE_GIT="true"
GIT_OWN="bianbu-linux"
GIT_REPO="linux-6.6"
GIT_BRANCH="bl-v2.0.y"
GIT_URL="https://gitee.com"
GIT_BLOB="blob"
# git linux patching
GIT_PATCHING="true"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"
# u-boot (if variable not found ignore)
GIT_UBOOT_TAG="bl-v2.0.y" # tag or branch
GIT_UBOOT_URL="${GIT_URL}/bianbu-linux/uboot-2022.10.git -b ${GIT_UBOOT_TAG} ${BOARD}-u-boot"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION="v2022.10"

# devicetree and platform
DEVICETREE="${DTB}.dtb k1-x_deb1.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="true"
COMMON_PKGNAME="spacemit"
