#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="meson-g12b"
FAMILY="amlogic"
FAMILY_EXT="bananapi"
DTB="${SERIES}-a311d-bananapi-m2s"

# default config
LINUX_DEFCONFIG="meson64_defconfig"
UBOOT_DEFCONFIG="bananapi-m2s_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="8192"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# firmware image package
RUN_FIP="${SERIES}-a311d"
BOARD_FIP="bananapi-m2s"

# output
BOARD="bananapim2s"
OUTPUT="output/${BOARD}"

# extlinux
BOOT_KERNEL="Image"
BOOT_INITRD="uInitrd"
FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=tty1 console=ttyAML0,115200n8 console=both"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0 no_console_suspend"

# motd
DEFAULT_MOTD="BananaPi M2S"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git
FORCE_GIT="false"
GIT_OWN=""
GIT_REPO=""
GIT_BRANCH=""
GIT_URL=""
GIT_BLOB=""
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION="v2024.01"

# devicetree and platform
DEVICETREE="${DTB}.dtb ${SERIES}-s922x-bananapi-m2s.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="true"
COMMON_PKGNAME="meson"
