#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="sun50i-h618"
FAMILY="allwinner"
FAMILY_EXT="sun50i"
DTB="${SERIES}-bananapi-m4-zero"

# default config
LINUX_DEFCONFIG="sunxi64_defconfig"
UBOOT_DEFCONFIG="bananapi_m4zero_defconfig"
CRUST_DEFCONFIG="${UBOOT_DEFCONFIG}"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="4096"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# arm trusted firmware
ATF_PLAT="sun50i_h616"
ATF_EXT="PLAT=${ATF_PLAT} DEBUG=1 bl31"

# output
BOARD="bananapim4zero"
OUTPUT="output/${BOARD}"

# extlinux
FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=tty1 console=ttyS0,115200n8 console=both"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0 usbcore.quirks=0x0bda:0xc820:g"

# motd
DEFAULT_MOTD="BananaPi M4 Zero"

# customize
MODULES_BLACKLIST="rtw88_8821c rtw88_8821cu"

# patches
LINUX_PATCHING="false"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git (https://github.com/BPI-SINOVOIP/pi-linux/tree/pi-6.1-sunxi)
FORCE_GIT="true"
GIT_OWN="BPI-SINOVOIP"
GIT_REPO="pi-linux"
GIT_BRANCH="pi-6.1-sunxi"
GIT_URL="https://github.com"
GIT_BLOB="blob"
# git patching
GIT_PATCHING="true"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION="v2024.01"

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="true"
COMMON_PKGNAME="sunxi"
