#!/bin/bash

# architecture
ARCH="arm"
ARCH_EXT="armhf"
DEBARCH=""
CROSS_COMPILE="arm-linux-gnueabihf-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-arm-static"

# device information
SERIES="imx6q"
FAMILY="freescale"
FAMILY_EXT="solidrun"
DTB="${SERIES}-cubox-i"

# default config
LINUX_DEFCONFIG="mx6cuboxi_defconfig"
UBOOT_DEFCONFIG="mx6cuboxi_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="4096"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# output
BOARD="cuboxi"
OUTPUT="output/${BOARD}"

# cmdline
CONSOLE="console=tty1 console=ttymxc0,115200n8 console=both"
EXTRA="cma=128M net.ifnames=0"

# motd
DEFAULT_MOTD="Cubox-i"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force github
FORCE_GITHUB="false"
GITHUB=""
GITHUB_REPO=""
GITHUB_BRANCH=""
GITHUB_BRANCH_VERSION=""

# override userdata file
FORCE_VERSION="false"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION=""

# devicetree and platform
DEVICETREE="${DTB}.dtb"
DEVICETREE2=""
DEVICETREE3=""
DEVICETREE4=""
PLATFORM="${FAMILY}"
