#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="imx8mp"
FAMILY="freescale"
FAMILY_EXT="imx8"
DTB="${SERIES}-evk"

# default config
LINUX_DEFCONFIG="imx8mp-evk_defconfig"
UBOOT_DEFCONFIG="imx8mp_evk_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="true"
P_VALUE="p2"
OFFSET="8192"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# arm trusted firmware
ATF_PLAT="imx8mp"
ATF_EXT="PLAT=${ATF_PLAT} bl31"

# output
BOARD="ft20"
OUTPUT="output/${BOARD}"

# extlinux
BOOT_KERNEL="Image"
BOOT_INITRD="uInitrd"
FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=tty1 console=ttyAML0,115200n8 console=both"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0"

# motd
DEFAULT_MOTD="FT20"

# patches
LINUX_PATCHING="false"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION="2023.04"
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git (https://github.com/nxp-imx/linux-imx/)
FORCE_GIT="true"
GIT_OWN="nxp-imx"
GIT_REPO="linux-imx"
GIT_BRANCH="lf-6.1.y"
GIT_URL="https://github.com"
GIT_BLOB="blob"
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION="v2023.04"

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="false"
COMMON_PKGNAME="imx"
