#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="meson-axg"
FAMILY="amlogic"
FAMILY_EXT="none"
DTB="${SERIES}-amper-gateway-am-gz80x"

# default config
LINUX_DEFCONFIG="meson64_defconfig"
UBOOT_DEFCONFIG="amper_gateway_am-gz80x_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="8192"

# boot config
EXTLINUX="false"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="true"

# firmware image package
RUN_FIP="${SERIES}"
BOARD_FIP="jethub-j100"

# output
BOARD="gateway-gz80x"
OUTPUT="output/${BOARD}"

# extlinux and bootcmd
BOOT_KERNEL="Image"
BOOT_INITRD="uInitrd"
BOOTCMD_FDTOVERLAYS=""
EXTLINUX_FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=ttyAML0,115200n8"
LOGLEVEL="loglevel=7"
EXTRA="net.ifnames=0 no_console_suspend"

# motd
DEFAULT_MOTD="Amper Gateway AM-GZ80x"

# patching
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git
FORCE_GIT="false"
GIT_OWN=""
GIT_REPO=""
GIT_BRANCH=""
GIT_URL=""
GIT_BLOB=""
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION="v2024.10"

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="true"
COMMON_PKGNAME="meson"
