#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="rk3588s"
FAMILY="rockchip"
FAMILY_EXT="rk3588"
DTB="${SERIES}-khadas-edge2"

# default config
LINUX_DEFCONFIG="kedges_defconfig"
#LINUX_DEFCONFIG="kedges_defconfig" # vendor
UBOOT_DEFCONFIG="khadas-edge2-rk3588s_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p2"
OFFSET="32768"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# arm trusted firmware
ATF_PLAT=""
ATF_EXT=""
RKBIN_ELF="rk3588_bl31_v1.45.elf"
RKBIN_RAM="rk3588_ddr_lp4_2112MHz_lp5_2736MHz_eyescan_v1.11.bin"

# output
BOARD="khadasedge2"
OUTPUT="output/${BOARD}"

# extlinux
BOOT_KERNEL="Image"
BOOT_INITRD="uInitrd"
FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="earlycon=uart8250,mmio32,0xfeb50000 console=ttyFIQ0 console=tty0 console=both"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0 rootflags=data=writeback"

# motd
DEFAULT_MOTD="Khadas Edge2"

# patches
LINUX_PATCHING="false"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}/${FAMILY_EXT}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="false"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION="2017.09"
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git (https://github.com/khadas/linux/)
FORCE_GIT="true"
GIT_OWN="khadas"
GIT_REPO="linux"
GIT_BRANCH="khadas-edges-6.1.y"
GIT_URL="https://github.com"
GIT_BLOB="blob"
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION="v2024.07"

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="false"
COMMON_PKGNAME="rk"
