#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="sun50i-h618"
FAMILY="allwinner"
FAMILY_EXT="sun50i"
DTB="${SERIES}-kickpi-k2b"

# default config
LINUX_DEFCONFIG="sunxi64_defconfig"
UBOOT_DEFCONFIG="kickpi_k2b_v2_defconfig"
CRUST_DEFCONFIG="${UBOOT_DEFCONFIG}"

# partition layout
BOOT_EXT4="false" # change P_VALUE to p2 if enabled
BOOT_VFAT="false" # change P_VALUE to p2 if enabled
EFI="false" # change P_VALUE to p2 and BOOT_VFAT to true if enabled
GPT="false" # set to true if rockchip
OFFSET="4MiB"
P_VALUE="p1" # p1 = single partition

# boot options
BOOTCMD="false"
BOOTINI="false"
BOOTSCR="boot.cmd" # define name of boot.cmd / boot.ini (files/boot/scripts)
EXTLINUX="true" # default
PETITBOOT="false" # obsolete

# arm trusted firmware
ATF_TAG="lts-v2.12.5"
ATF_PLAT="sun50i_h616"
ATF_EXT="PLAT=${ATF_PLAT} DEBUG=1 bl31"

# output
BOARD="kickpik2b-v2"
OUTPUT="output/${BOARD}"

# extlinux and bootcmd
BOOT_KERNEL="Image"
BOOT_INITRD="uInitrd"
BOOTCMD_FDTOVERLAYS="#overlays="
EXTLINUX_FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=tty1 console=ttyS0,115200n8"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0 video=HDMI-A-1:1920x1080"

# Serial
DEVUAN_SERIAL="T0:23:respawn:/sbin/getty -L ttyS0 115200 vt100"

# motd
DEFAULT_MOTD="KickPi K2B V2"

# customize
#MODULES_BLACKLIST=""
MODULES_LOAD="hidp rfcomm bnep aic8800_btlpm"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git ()
FORCE_GIT="false"
GIT_OWN=""
GIT_REPO=""
GIT_BRANCH=""
GIT_URL=""
GIT_BLOB="blob"
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION="6.12.y"
FORCE_UBOOT_VERSION="v2025.07"

# devicetree and platform
DEVICETREE=""
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="true"
COMMON_PKGNAME="sunxi"
