#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="meson-gxl"
FAMILY="amlogic"
FAMILY_EXT="none"
DTB="${SERIES}-s905x-libretech-cc"

# default config
LINUX_DEFCONFIG="meson64_defconfig"
UBOOT_DEFCONFIG="libretech-cc_defconfig"

# partition layout
BOOT_EXT4="false" # change P_VALUE to p2 if enabled
BOOT_VFAT="false" # change P_VALUE to p2 if enabled
EFI="false" # change P_VALUE to p2 and BOOT_VFAT to true if enabled
GPT="false" # set to true if rockchip
OFFSET="4MiB"
P_VALUE="p1" # p1 = single partition

# boot options
BOOTCMD="false"
BOOTINI="false"
BOOTSCR="boot.cmd" # define name of boot.cmd / boot.ini (files/boot/scripts)
EXTLINUX="true" # default
PETITBOOT="false" # obsolete

# firmware image package
RUN_FIP="${SERIES}"
BOARD_FIP="lepotato"

# output
BOARD="lepotato"
OUTPUT="output/${BOARD}"

# extlinux and bootcmd
BOOT_KERNEL="Image"
BOOT_INITRD="initrd.img"
BOOTCMD_FDTOVERLAYS="#overlays="
EXTLINUX_FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=tty1 console=ttyAML0,115200n8"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0 no_console_suspend"

# Serial
DEVUAN_SERIAL="T0:23:respawn:/sbin/getty -L ttyAML0 115200 vt100"

# motd
DEFAULT_MOTD="Libre Computer Le Potato"

# patching
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION="2024.07"
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git
FORCE_GIT="false"
GIT_OWN=""
GIT_REPO=""
GIT_BRANCH=""
GIT_URL=""
GIT_BLOB=""
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION="v2026.01"

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="true"
COMMON_PKGNAME="amlogic"

# build old kernel headers package (not recommended)
LEGACY_PACKAGING="false"

# use builder kernel packaging (recommended)
DEFAULT_PACKAGING="true"
