#!/bin/bash

# architecture
ARCH="arm"
ARCH_EXT="armhf"
DEBARCH=""
CROSS_COMPILE="arm-linux-gnueabihf-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-arm-static"

# device information
SERIES="sun8i-h3"
FAMILY="allwinner"
FAMILY_EXT="sun8i"
DTB="${SERIES}-nanopi-neo"

# default config
LINUX_DEFCONFIG="sunxi_defconfig"
UBOOT_DEFCONFIG="nanopi_neo_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="4096"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# output
BOARD="nanopineo"
OUTPUT="output/${BOARD}"

# cmdline
CONSOLE="console=tty1 console=ttyS0,115200n8 console=both"
EXTRA="net.ifnames=0"

# motd
DEFAULT_MOTD="NanoPi NEO"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force github
FORCE_GITHUB="false"
GITHUB=""
GITHUB_REPO=""
GITHUB_BRANCH=""
GITHUB_BRANCH_VERSION=""

# override userdata file
FORCE_VERSION="false"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION=""

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="true"
COMMON_PKGNAME="sunxi"
