#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="rk3399"
FAMILY="rockchip"
FAMILY_EXT="${SERIES}"
DTB="${SERIES}-nanopc-t4"

# default config
LINUX_DEFCONFIG="rockchip64-rk3399_defconfig"
UBOOT_DEFCONFIG="nanopc-t4-rk3399_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="32768"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# arm trusted firmware
ATF_PLAT="rk3399"
ATF_EXT="PLAT=${ATF_PLAT} bl31"
RKBIN_ELF=""
RKBIN_RAM=""

# output
BOARD="nanopct4"
OUTPUT="output/${BOARD}"

# cmdline
CONSOLE="console=tty1 console=ttyS2,115200n8 console=both"
EXTRA="net.ifnames=0 usb-storage.quirks=0x152d:0x0576:u"

# motd
DEFAULT_MOTD="NanoPC-T4"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}/${FAMILY_EXT}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="false"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git
FORCE_GIT="false"
GIT_OWN=""
GIT_REPO=""
GIT_BRANCH=""
GIT_URL=""
GIT_BLOB=""
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION="v2023.10"

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="false"
COMMON_PKGNAME="rk"
