#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="rk3568"
FAMILY="rockchip"
FAMILY_EXT="rk356x"
DTB="${SERIES}-odroid-m1"

# default config
LINUX_DEFCONFIG="rockchip64-rk356x_defconfig"
UBOOT_DEFCONFIG="odroid-m1-rk3568_defconfig"

# partition scheme
GPT="true"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="32768"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# arm trusted firmware
ATF_PLAT="rk3568"
ATF_EXT="PLAT=${ATF_PLAT} bl31"
RKBIN_ELF="rk3568_bl31_v1.24.elf"
RKBIN_RAM="rk3568_ddr_1560MHz_v1.13.bin"

# output
BOARD="odroidm1"
OUTPUT="output/${BOARD}"

# extlinux
BOOT_KERNEL="Image"
BOOT_INITRD="uInitrd"
FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=tty1 console=ttyS2,115200n8 console=both"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0 pci=nomsi fsck.mode=force cma=128m"

# motd
DEFAULT_MOTD="Odroid M1"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}/${FAMILY_EXT}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="false"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git
FORCE_GIT="false"
GIT_OWN=""
GIT_REPO=""
GIT_BRANCH=""
GIT_URL=""
GIT_BLOB=""
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION="" # currently defined by scripts/linux
FORCE_UBOOT_VERSION="v2022.07"

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="false"
COMMON_PKGNAME="rk"
