#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="meson-sm1"
FAMILY="amlogic"
FAMILY_EXT="odroid"
DTB="${SERIES}-odroid-hc4"

# default config
LINUX_DEFCONFIG="odroid_defconfig"
UBOOT_DEFCONFIG="odroid-hc4_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="8192"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# firmware image package
RUN_FIP="${SERIES}"
BOARD_FIP="odroid-hc4"

# output
BOARD="odroidhc4"
OUTPUT="output/${BOARD}"

# cmdline
CONSOLE="console=tty1 console=ttyAML0,115200n8 console=both"
EXTRA="net.ifnames=0 no_console_suspend"

# motd
DEFAULT_MOTD="Odroid HC4"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/odroidc4"

# force github
FORCE_GITHUB="false"
GITHUB=""
GITHUB_REPO=""
GITHUB_BRANCH=""
GITHUB_BRANCH_VERSION=""

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION="v2023.04"

# devicetree and platform
DEVICETREE="${DTB}.dtb"
DEVICETREE2="meson64_odroidhc4.dtb"
DEVICETREE3="${SERIES}-odroid-c4.dtb"
DEVICETREE4="meson64_odroidc4.dtb"
PLATFORM="${FAMILY}"
