#!/bin/bash

# architecture
ARCH="arm"
ARCH_EXT="armhf"
DEBARCH=""
CROSS_COMPILE="arm-linux-gnueabihf-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-arm-static"

# device information
SERIES="exynos5422"
FAMILY="samsung"
FAMILY_EXT="exynos"
DTB="${SERIES}-odroidxu4"

# default config
LINUX_DEFCONFIG="odroid-xu4_defconfig"
UBOOT_DEFCONFIG="odroid-xu3_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="4096"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# output
BOARD="odroidxu4"
OUTPUT="output/${BOARD}"

# cmdline
CONSOLE="console=tty1 console=ttySAC2,115200n8 console=both"
EXTRA="net.ifnames=0 smsc95xx.macaddr=00:1e:06:61:7a:39 s5p_mfc.mem=16M"
EXTRA2="usbhid.quirks=0x0eef:0x0005:0x0004"

# motd
DEFAULT_MOTD="Odroid XU4"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force github
FORCE_GITHUB="false"
GITHUB=""
GITHUB_REPO=""
GITHUB_BRANCH=""
GITHUB_BRANCH_VERSION=""

# override userdata file
FORCE_VERSION="false"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION=""

# devicetree and platform
DEVICETREE="${DTB}.dtb"
DEVICETREE2=""
DEVICETREE3=""
DEVICETREE4=""
PLATFORM="${FAMILY}"
