#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="meson-g12b"
FAMILY="amlogic"
FAMILY_EXT="odroid"
DTB="${SERIES}-odroid-n2-plus"

# default config
LINUX_DEFCONFIG="meson64_defconfig"
UBOOT_DEFCONFIG="odroid-n2_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="8192"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# firmware image package
RUN_FIP="${SERIES}-s922x"
BOARD_FIP="odroid-n2-plus"

# output
BOARD="odroidn2plus"
OUTPUT="output/${BOARD}"

# cmdline
CONSOLE="console=tty1 console=ttyAML0,115200n8 console=both"
EXTRA="net.ifnames=0 no_console_suspend clk_ignore_unused usb-storage.quirks=0x152d:0x0576:u"

# motd
DEFAULT_MOTD="Odroid N2+"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/odroidn2"

# force git
FORCE_GIT="false"
GIT_OWN=""
GIT_REPO=""
GIT_BRANCH=""
GIT_URL=""
GIT_BLOB=""
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION="v2023.07.02"

# devicetree and platform
DEVICETREE="${DTB}.dtb meson64_odroidn2_plus.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="true"
COMMON_PKGNAME="meson"
