#!/bin/bash

# architecture
ARCH="arm"
ARCH_EXT="armhf"
DEBARCH=""
CROSS_COMPILE="arm-linux-gnueabihf-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-arm-static"

# device information
SERIES="meson8b"
FAMILY="amlogic"
FAMILY_EXT="${SERIES}"
DTB="${SERIES}-odroidc1"

# default config
LINUX_DEFCONFIG="meson8b_defconfig"
UBOOT_DEFCONFIG=""

# partition scheme
GPT="false"
EFI="false"
VFAT="true"
P_VALUE="p2"
OFFSET="8192"

# boot config
EXTLINUX="false"
PETITBOOT="false"
BOOTINI="true"
BOOTCMD="false"

# output
BOARD="odroidc1"
OUTPUT="output/${BOARD}"

# extlinux
BOOT_KERNEL="Image"
BOOT_INITRD="uInitrd"
FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=tty1 console=ttyAML0,115200n8 console=both"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0 fsck.repair=yes"

# motd
DEFAULT_MOTD="Odroid C1"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}/${FAMILY_EXT}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="false"

# precompiled
PRECOMPILED_UBOOT="true"
PKGVERSION="2011.03"
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git
FORCE_GIT="false"
GIT_OWN=""
GIT_REPO=""
GIT_BRANCH=""
GIT_URL=""
GIT_BLOB=""
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION="5.19.17"
FORCE_UBOOT_VERSION=""

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="false"
COMMON_PKGNAME="meson"
