#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="sun50i-h6"
FAMILY="allwinner"
FAMILY_EXT="sun50i"
DTB="${SERIES}-orangepi-3"

# default config
LINUX_DEFCONFIG="sun50i_defconfig"
UBOOT_DEFCONFIG="orangepi_3_defconfig"
CRUST_DEFCONFIG="${UBOOT_DEFCONFIG}"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="4096"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# arm trusted firmware
ATF_PLAT="sun50i_h6"
ATF_EXT="PLAT=${ATF_PLAT} DEBUG=1 bl31"

# output
BOARD="orangepi3"
OUTPUT="output/${BOARD}"

# cmdline
CONSOLE="console=tty1 console=ttyS0,115200n8 console=both"
EXTRA="net.ifnames=0"

# motd
DEFAULT_MOTD="OrangePi 3"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force github
FORCE_GITHUB="false"
GITHUB=""
GITHUB_REPO=""
GITHUB_BRANCH=""
GITHUB_BRANCH_VERSION=""

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION="v2023.07.02"

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"
