#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="rk3588"
FAMILY="rockchip"
FAMILY_EXT="rk3588"
DTB="${SERIES}-orangepi-5-plus"

# default config
LINUX_DEFCONFIG="orangepi-5_defconfig"
#LINUX_DEFCONFIG="rockchip_linux_defconfig" # vendor
UBOOT_DEFCONFIG="_defconfig"

# partition scheme
GPT="true"
EFI="false"
VFAT="true"
P_VALUE="p2"
OFFSET="32768"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# arm trusted firmware
ATF_PLAT=""
ATF_EXT=""
RKBIN_ELF=""
RKBIN_RAM=""

# output
BOARD="orangepi5plus"
OUTPUT="output/${BOARD}"

# extlinux
KERNEL="Image"
INITRD="uInitrd"
FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=tty1 console=ttyS2,115200n8 console=both"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0 rootflags=data=writeback"

# motd
DEFAULT_MOTD="OrangePi 5 Plus"

# patches
LINUX_PATCHING="false"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}/${FAMILY_EXT}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="false"

# precompiled
PRECOMPILED_UBOOT="true"
PKGVERSION="2017.09"
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git (https://github.com/orangepi-xunlong/linux-orangepi/)
FORCE_GIT="true"
GIT_OWN="orangepi-xunlong"
GIT_REPO="linux-orangepi"
GIT_BRANCH="orange-pi-5.10-rk3588"
GIT_URL="https://github.com"
GIT_BLOB="blob"
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="false"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION=""

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="false"
COMMON_PKGNAME="rk"
