#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="sky1"
FAMILY="cix"
FAMILY_EXT=""
DTB="sky1-orion-o6"

# default config
LINUX_DEFCONFIG="uefi-arm64_defconfig"
UBOOT_DEFCONFIG=""

# partition scheme
GPT="true"
EFI="true"
VFAT="true"
P_VALUE="p2"
OFFSET="2048"

# boot config
EXTLINUX="false"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# output
BOARD="oriono6"
OUTPUT="output/${BOARD}"

# extlinux and bootcmd
BOOT_KERNEL="Image"
BOOT_INITRD="initrd.gz"
BOOTCMD_FDTOVERLAYS=""
EXTLINUX_FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=tty1 console=ttyAMA2,115200"
LOGLEVEL="loglevel=5"
EXTRA="net.ifnames=0"

# motd
DEFAULT_MOTD="Orion O6"

# customize
MODULES_LOAD=""

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO=""

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git (https://github.com/armbian/linux-cix.git)
FORCE_GIT="false"
GIT_OWN=""
GIT_REPO=""
GIT_BRANCH=""
GIT_URL=""
GIT_BLOB=""
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION="stable"
FORCE_UBOOT_VERSION=""

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="true"
COMMON_PKGNAME="cix"
