#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="rk3566"
FAMILY="rockchip"
FAMILY_EXT="rk356x"
DTB="${SERIES}-radxa-zero-3w"

# default config
LINUX_DEFCONFIG="rockchip64_defconfig"
UBOOT_DEFCONFIG="radxa-zero-3-rk3566_defconfig"

# partition scheme
GPT="true"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="32768"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# arm trusted firmware
ATF_PLAT="rk3568"
ATF_EXT="PLAT=${ATF_PLAT} bl31"
RKBIN_COMMIT="f43a462e7a1429a9d407ae52b4745033034a6cf9"
RKBIN_DIR="rkbin-${RKBIN_COMMIT}/bin/rk35"
RKBIN_ELF="bl31.elf"
RKBIN_RAM="rk3566_ddr_1056MHz_v1.23.bin"

# output
BOARD="radxazero3w"
OUTPUT="output/${BOARD}"

# extlinux and bootcmd
BOOT_KERNEL="Image"
BOOT_INITRD="uInitrd"
BOOTCMD_FDTOVERLAYS=""
EXTLINUX_FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=tty1 console=ttyS2,115200n8"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0"

# motd
DEFAULT_MOTD="Radxa Zero 3W"

# customize
#MODULES_BLACKLIST=""
#MODULES_LOAD=""

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="false"

# u-boot-rockchip.bin
UBOOT_RK_BIN="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git
FORCE_GIT="false"
GIT_OWN=""
GIT_REPO=""
GIT_BRANCH=""
GIT_URL=""
GIT_BLOB=""
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION="6.12.y"
FORCE_UBOOT_VERSION="v2025.04"

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="true"
COMMON_PKGNAME="rockchip"
