#!/bin/bash

# architecture
ARCH="arm"
ARCH_EXT="armel"
DEBARCH="${ARCH_EXT}"
CROSS_COMPILE="arm-linux-gnueabi-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-arm-static"

# device information
SERIES="bcm2835"
FAMILY="broadcom"
FAMILY_EXT="${SERIES}"
DTB="${SERIES}-rpi-zero-w"

# default config
LINUX_DEFCONFIG="bcmrpi_defconfig"
UBOOT_DEFCONFIG="rpi_0_w_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="true"
P_VALUE="p2"
OFFSET="8192"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# output
BOARD="raspberrypizero"
OUTPUT="output/${BOARD}"

# cmdline
CONSOLE="console=tty1 console=ttyS0,115200 console=both 8250.nr_uarts=1"
EXTRA="logo.nologo net.ifnames=0 firmware_class.path=/lib/firmware/updates/brcm"

# motd
DEFAULT_MOTD="Raspberry Pi Zero"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git (https://github.com/raspberrypi/linux/)
FORCE_GIT="false"
GIT_OWN=""
GIT_REPO=""
GIT_BRANCH=""
GIT_URL=""
GIT_BLOB=""
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="false"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION=""

# devicetree and platform
DEVICETREE="${DTB}.dtb ${SERIES}-rpi-zero.dtb bcm2708-rpi-zero-w.dtb bcm2708-rpi-zero.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="false"
COMMON_PKGNAME="bcm"
