#!/bin/bash

# architecture
ARCH="arm"
ARCH_EXT="armhf"
DEBARCH=""
CROSS_COMPILE="arm-linux-gnueabihf-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-arm-static"

# device information
SERIES="bcm2836"
FAMILY="broadcom"
FAMILY_EXT="${SERIES}"
DTB="${SERIES}-rpi-2-b"

# default config
LINUX_DEFCONFIG="bcm2709_defconfig"
UBOOT_DEFCONFIG="rpi_2_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="true"
P_VALUE="p2"
OFFSET="8192"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# output
BOARD="raspberrypi2"
OUTPUT="output/${BOARD}"

# cmdline
CONSOLE="console=tty1 console=ttyS0,115200 console=both 8250.nr_uarts=1"
EXTRA="logo.nologo net.ifnames=0 firmware_class.path=/lib/firmware/updates/brcm"

# motd
DEFAULT_MOTD="Raspberry Pi 2B"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force github (https://github.com/raspberrypi/linux/)
FORCE_GITHUB="false"
GITHUB=""
GITHUB_REPO=""
GITHUB_BRANCH=""
GITHUB_BRANCH_VERSION=""

# override userdata file
FORCE_VERSION="false"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION=""

# devicetree and platform
DEVICETREE="${DTB}.dtb bcm2709-rpi-2-b.dtb"
PLATFORM="${FAMILY}"
