#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="bcm2712"
FAMILY="broadcom"
FAMILY_EXT="raspberrypi"
DTB="${SERIES}-rpi-5-b"

# default config
LINUX_DEFCONFIG="bcm2712_defconfig"
#UBOOT_DEFCONFIG="_defconfig"

# partition layout
BOOT_EXT4="false" # change P_VALUE to p2 if enabled
BOOT_VFAT="true" # change P_VALUE to p2 if enabled
EFI="false" # change P_VALUE to p2 and BOOT_VFAT to true if enabled
GPT="false" # set to true if rockchip
OFFSET="4MiB"
P_VALUE="p2" # p1 = single partition

# boot options
BOOTCMD="false"
BOOTINI="false"
BOOTSCR="boot.cmd" # define name of boot.cmd / boot.ini (files/boot/scripts)
EXTLINUX="false" # default
PETITBOOT="false" # obsolete

# output
BOARD="raspberrypi5"
OUTPUT="output/${BOARD}"

# extlinux and bootcmd
BOOT_KERNEL="Image"
BOOT_INITRD="initrd.gz"
BOOTCMD_FDTOVERLAYS="#overlays="
EXTLINUX_FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=serial0,115200 console=tty1"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0"

# Serial
DEVUAN_SERIAL="T0:23:respawn:/sbin/getty -L serial0 115200 vt100"

# motd
DEFAULT_MOTD="Raspberry Pi 5"

# customize
MODULES_LOAD="#bcm2835-v4l2 drivetemp #i2c-dev snd_bcm2835"

# patches
LINUX_PATCHING="false"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git (https://github.com/raspberrypi/linux)
FORCE_GIT="true"
GIT_OWN="raspberrypi"
GIT_REPO="linux"
GIT_BRANCH="rpi-${VERSION}"
GIT_URL="https://github.com"
GIT_BLOB="blob"
# git patching
GIT_PATCHING="true"
GIT_PATCHING_ALL=`echo ${VERSION} | sed 's/..$//'`
GIT_PATCHDIR="patches/all/${GIT_PATCHING_ALL}"

# override userdata file
FORCE_VERSION="false"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION=""

# devicetree and platform
DEVICETREE="bcm2712*.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="true"
COMMON_PKGNAME="broadcom"
