#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="rk3588"
FAMILY="rockchip"
FAMILY_EXT="rk358x"
DTB="${SERIES}-rock-5b"

# default config
LINUX_DEFCONFIG="rockchip64_defconfig"
UBOOT_DEFCONFIG="rock5b-rk3588_defconfig"

# partition layout
BOOT_EXT4="false" # change P_VALUE to p2 if enabled
BOOT_VFAT="false" # change P_VALUE to p2 if enabled
EFI="false" # change P_VALUE to p2 and BOOT_VFAT to true if enabled
GPT="true" # set to true if rockchip
OFFSET="32768"
P_VALUE="p1" # p1 = single partition

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# arm trusted firmware
ATF_EN="false"
ATF_TAG="lts-v2.12.5"
ATF_PLAT="rk3588"
ATF_EXT="PLAT=${ATF_PLAT} bl31"
RKBIN_COMMIT="f43a462e7a1429a9d407ae52b4745033034a6cf9"
RKBIN_DIR="rkbin-${RKBIN_COMMIT}/bin/rk35"
RKBIN_ELF="rk3588_bl31_v1.48.elf"
RKBIN_RAM="rk3588_ddr_lp4_2112MHz_lp5_2400MHz_v1.18.bin"

# output
BOARD="rock5b"
OUTPUT="output/${BOARD}"

# extlinux and bootcmd
BOOT_KERNEL="Image"
BOOT_INITRD="uInitrd"
BOOTCMD_FDTOVERLAYS="#overlays="
EXTLINUX_FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=tty1 console=ttyS2,1500000n8"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0"

# Serial
DEVUAN_SERIAL="T0:23:respawn:/sbin/getty -L ttyS2 1500000 vt100"

# motd
DEFAULT_MOTD="Radxa ROCK 5B"

# customize
#MODULES_BLACKLIST=""
#MODULES_LOAD=""

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="false"

# u-boot-rockchip.bin
UBOOT_RK_BIN="true"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git
FORCE_GIT="false"
GIT_OWN=""
GIT_REPO=""
GIT_BRANCH=""
GIT_URL=""
GIT_BLOB=""
# git patching
GIT_PATCHING="false"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION="stable"
FORCE_UBOOT_VERSION="v2025.07"

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="true"
COMMON_PKGNAME="rockchip"
