#!/bin/bash

# architecture
ARCH="arm64"
ARCH_EXT="arm64"
DEBARCH=""
CROSS_COMPILE="aarch64-linux-gnu-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-aarch64-static"

# device information
SERIES="rk3588"
FAMILY="rockchip"
FAMILY_EXT="rk3588"
DTB="${SERIES}-rock-5b"

# default config
LINUX_DEFCONFIG="radxa-rock5b_defconfig"
#LINUX_DEFCONFIG="rockchip_linux_defconfig" # vendor
UBOOT_DEFCONFIG="_defconfig"

# partition scheme
GPT="true"
EFI="false"
VFAT="true"
P_VALUE="p2"
OFFSET="32768"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# arm trusted firmware
ATF_PLAT=""
ATF_EXT=""
RKBIN_ELF=""
RKBIN_RAM=""

# output
BOARD="rock5b"
OUTPUT="output/${BOARD}"

# extlinux
FDTOVERLAYS="#fdtoverlays"

# cmdline
CONSOLE="console=tty1 console=ttyS2,115200n8 console=both"
LOGLEVEL="loglevel=1"
EXTRA="net.ifnames=0"

# motd
DEFAULT_MOTD="Rock 5B"

# patches (if using git set LINUX_PATCHING="false")
LINUX_PATCHING="false"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}/${FAMILY_EXT}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="false"

# precompiled
PRECOMPILED_UBOOT="true"
PKGVERSION="2017.09"
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force git (https://gitlab.collabora.com/hardware-enablement/rockchip-3588/linux.git)
FORCE_GIT="true"
GIT_OWN="hardware-enablement/rockchip-3588"
GIT_REPO="linux"
GIT_BRANCH="rk3588-v6.8"
GIT_URL="https://gitlab.collabora.com"
GIT_BLOB="-/blob"
# git patching
GIT_PATCHING="true"
GIT_PATCHDIR="patches/git/${BOARD}/${GIT_REPO}-${GIT_BRANCH}"

# override userdata file
FORCE_VERSION="false"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION=""

# devicetree and platform
DEVICETREE="${DTB}.dtb rk3588s-rock-5a.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="false"
COMMON_PKGNAME="rk"
