#!/bin/bash

# architecture
ARCH="arm"
ARCH_EXT="armhf"
DEBARCH=""
CROSS_COMPILE="arm-linux-gnueabihf-"
ROOTFS_ARCH="rootfs-${ARCH_EXT}"
STATIC="qemu-arm-static"

# device information
SERIES="rk3288"
FAMILY="rockchip"
FAMILY_EXT="${SERIES}"
DTB="${SERIES}-tinker"

# default config
LINUX_DEFCONFIG="rockchip_defconfig"
UBOOT_DEFCONFIG="tinker-rk3288_defconfig"

# partition scheme
GPT="false"
EFI="false"
VFAT="false"
P_VALUE="p1"
OFFSET="32768"

# boot config
EXTLINUX="true"
PETITBOOT="false"
BOOTINI="false"
BOOTCMD="false"

# arm trusted firmware
ATF_PLAT=""
ATF_EXT=""
RKBIN_ELF=""
RKBIN_RAM=""

# output
BOARD="tinker"
OUTPUT="output/${BOARD}"

# cmdline
CONSOLE="console=tty1 console=ttyS2,115200n8 console=both"
EXTRA="net.ifnames=0 dwc_otg.fiq_split_enable=0"

# motd
DEFAULT_MOTD="Tinkerboard"

# patches
LINUX_PATCHING="true"
UBOOT_PATCHDIR="patches/uboot"
LINUX_PATCHDIR="patches/${FAMILY}/${FAMILY_EXT}"

# image
IMG_EXP="${DTB}-*.img*"

# uboot logo
RANDOM_LOGO="false"

# precompiled
PRECOMPILED_UBOOT="false"
PKGVERSION=""
PRECOMPILED_UBOOT_DIR="files/boot/uboot/${BOARD}"

# force github
FORCE_GITHUB="false"
GITHUB=""
GITHUB_REPO=""
GITHUB_BRANCH=""
GITHUB_BRANCH_VERSION=""

# override userdata file
FORCE_VERSION="true"
FORCE_LINUX_VERSION=""
FORCE_UBOOT_VERSION="v2023.07.02"

# devicetree and platform
DEVICETREE="${DTB}.dtb"
PLATFORM="${FAMILY}"

# kernel package name (if shared patching set to true)
COMMON_PKG="false"
COMMON_PKGNAME="rk"
