#!/bin/bash
# Radxa Zero REV. 1.5 Cap SDIO Speed

run_function2 (){
mkdir -p /etc/initramfs/post-update.d/
wget -cq https://raw.githubusercontent.com/pyavitz/debian-image-builder/feature/files/boot/99-sdio-speed -P /etc/initramfs/post-update.d/
if [ -f /etc/initramfs/post-update.d/99-sdio-speed ]; then
	echo -en "99-sdio-speed found ";
	chmod +x /etc/initramfs/post-update.d/99-sdio-speed;
	chown root:root /etc/initramfs/post-update.d/99-sdio-speed;
	echo "[executable]"
else
	echo -e "function2 of user scripts failed.";
	sleep 2s
fi
}
