#!/bin/bash
RED="\e[0;31m"
FIN="\e[0m"

user=""
passwd=""
MOTD="Debian"
HOSTNAME="computer"
DEBIAN_VERSION="buster"
VERSION="5.8.14"
UBOOT_VERSION="v2020.10"
menuconfig="0"
mainline="0"
crosscompile="1"

# open fd
exec 3>&1

# Store data to $VALUES variable
VALUES=$(dialog --ok-label "Submit" \
	  --backtitle "Debian Image Builder" \
	  --title "Config Menu" \
	  --form "Choose:" \
17 31 10 \
	"Username:"	1 1	"$user" 		1 10 18 0 \
	"Password:"	2 1	"$passwd"  		2 10 18 0 \
	"Branding:"	3 1	"$MOTD"			3 10 18 0 \
	"Hostname:"	4 1	"$HOSTNAME"		4 10 18 0 \
	"Debian:"	5 1	"$DEBIAN_VERSION"  	5 10 18 0 \
        "U-Boot:"   	6 1     "$UBOOT_VERSION"       	6 10 18 0 \
        "Branch:"   	7 1     "$VERSION"        	7 10 18 0 \
        "Mainline:"   	8 1     "$mainline"        	8 15 2 0 \
	"Menuconfig:"	9 1	"$menuconfig"  		9 15 2 0 \
	"Crosscompile:" 10 1	"$crosscompile" 	10 15 2 0 \
	""		11 1	""			11 15 0 0 \
2>&1 1>&3)

# close fd
exec 3>&-

# convert into vars
echo "$VALUES" > tmp1
echo user='"' > tmp0
echo passwd='"' >> tmp0
echo MOTD='"' >> tmp0
echo HOSTNAME='"' >> tmp0
echo DEBIAN_VERSION='"' >> tmp0
echo UBOOT_VERSION='"' >> tmp0
echo VERSION='"' >> tmp0
echo mainline= >> tmp0
echo menuconfig= >> tmp0
echo crosscompile= >> tmp0
echo emmc=0 >> tmp0
echo custom_defconfig=0 >> tmp0
echo MYCONFIG='"'nameofyour_defconfig'"' >> tmp0
echo verbose=0 >> tmp0
echo '"' > tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
echo '"' >> tmp2
paste -d '\0' tmp0 tmp1 tmp2  > userdata.txt
rm -f tmp0 tmp1 tmp2

# gcc version
echo GCC='"'$(gcc --version | grep gcc | awk '{print $4}')'"' >> userdata.txt

# clear screen
clear

# userdata
echo -e "${RED}userdata file created${FIN}."
echo
