#!/bin/bash

# variables
SRC="sources"
DEF="../defconfig"
LPATCHESALL="patches/all"
USERPATCHES="patches/userpatches"
OVERLAYPATCHES="patches/overlays"
WIRELESSPATCHES="patches/wireless"
KERNEL="linux"

# host machine
HOST_MACHINE=`cat /etc/os-release | grep -w NAME | sed 's/NAME=//g' | sed 's/"//g' | sed 's/ GNU\/Linux//g'`
HOST_CODENAME=`cat /etc/os-release | grep -w "VERSION_CODENAME" | sed 's/VERSION_CODENAME=//g'`
HOST_ARCH=`uname -m`
EXPIRED="The userdata.txt file has expired. Create a new one."

# validate
validation (){
BUILDER=`grep "BUILDER=" "userdata.txt" | sed 's/BUILDER=//g'`
if [[ -f "userdata.txt" ]]; then
	echo -e ""
else 
	echo -e ""
	echo -e "Create a userdata.txt file"
	while [ true ]; do
		read -t 10 -n 1
		if [ $? = 0 ]; then exit 0; fi
	done
fi
if [[ "$BUILDER" == "6.5" ]]; then :; else echo -e "${EXPIRED}"; exit 0; fi
}

# board dot txt
noboard (){
echo -e "board.txt was not found."
echo -e "Run again with the correct spelling and or command."
echo -e ""
read -p "Press enter to continue."
exit 0
}

# base packages
PKGS="tzdata keyboard-configuration sudo man-db dbus initramfs-tools zip unzip \
	e2fsprogs u-boot-tools fonty-rg patch wget apt-transport-https pciutils \
	dirmngr rsync psmisc parted hdparm aria2 dosfstools pv fdisk ntp tasksel \
	bluetooth rfkill gpiod git build-essential net-tools distro-info-data \
	ifplugd fuse3 wpasupplicant wireless-tools usbutils alsa-utils gettext wget \
	mc nano figlet toilet curl dialog openssh-client openssh-server ntfs-3g bc \
	bison flex libssl-dev zram-tools python3 python3-setuptools avahi-utils iw \
	libncursesw5-dev autopoint autoconf automake pkg-config libtool fake-hwclock \
	lsb-release libell0 wireless-regdb bluez bluez-tools irqbalance ethtool i2c-tools \
	python3-libgpiod python-is-python3 btrfs-progs xfsprogs ir-keytable f2fs-tools \
	kpartx mtd-utils whiptail mtools sg3-utils lsscsi"

# firmware packages
DEBIAN_FW="firmware-linux-nonfree firmware-linux bluez-firmware \
	firmware-misc-nonfree firmware-realtek firmware-ralink \
	firmware-qcom-soc firmware-iwlwifi"

UBUNTU_FW="linux-firmware-mediatek-aiot"

# user scripts (stage1 and stage2)
uscripts_pre-stage1 (){
if [[ -f "files/userscripts/uscripts" ]]; then
	source files/userscripts/uscripts
	if [[ `type run_function0` ]] &>/dev/null; then
		run_function0
	fi
fi
}

uscripts_stage1 (){
if [[ -f "files/userscripts/uscripts" ]]; then
	mkdir -p ${P_VALUE}/root/userscripts;
	cp -fr files/userscripts/* ${P_VALUE}/root/userscripts/;
	if [[ -f "${P_VALUE}/root/userscripts/README.md" ]]; then
		rm -f ${P_VALUE}/root/userscripts/README.md;
	fi
	if [[ `type run_function1` ]] &>/dev/null; then
		run_function1
	fi
fi
}

uscripts_stage2 (){
if [[ -f "/root/userscripts/uscripts" ]]; then
	source /root/userscripts/uscripts
	if [[ `type run_function2` ]] &>/dev/null; then
		echo ""
		echo -e "\033[1mRunning user scripts\e[0m ..."
		run_function2
		echo -e "\033[1mDone\e[0m."
	fi
fi
if [[ -e "/root/userscripts" ]]; then rm -fdr /root/userscripts; fi
}

uscripts_fin-stage1 (){
if [[ -f "files/userscripts/uscripts" ]]; then
	source files/userscripts/uscripts
	if [[ `type run_function3` ]] &>/dev/null; then
		run_function3
	fi
fi
}

override_board (){
if [[ ! -z "$ARCH_EXT" ]]; then
	sed -i 's/^ARCH_EXT=.*/ARCH_EXT="'"${ARCH_EXT}"'"/' board.txt
	if [[ "$ARCH_EXT" == "armel" ]]; then
		sed -i 's/^CROSS_COMPILE=.*/CROSS_COMPILE="'"arm-linux-gnueabi-"'"/' board.txt
		sed -i 's/^STATIC=.*/STATIC="'"qemu-arm-static"'"/' board.txt
	fi
	if [[ "$ARCH_EXT" == "armhf" ]]; then
		sed -i 's/^CROSS_COMPILE=.*/CROSS_COMPILE="'"arm-linux-gnueabihf-"'"/' board.txt
		sed -i 's/^STATIC=.*/STATIC="'"qemu-arm-static"'"/' board.txt
	fi
	if [[ "$ARCH_EXT" == "arm64" ]]; then
		sed -i 's/^CROSS_COMPILE=.*/CROSS_COMPILE="'"aarch64-linux-gnu-"'"/' board.txt
		sed -i 's/^STATIC=.*/STATIC="'"qemu-aarch64-static"'"/' board.txt
	fi
fi
if [[ ! -z "$FORCE_GIT" ]]; then sed -i 's/^FORCE_GIT=.*/FORCE_GIT="'"${FORCE_GIT}"'"/' board.txt; fi
if [[ ! -z "$FORCE_VERSION" ]]; then sed -i 's/^FORCE_VERSION=.*/FORCE_VERSION="'"${FORCE_VERSION}"'"/' board.txt; fi
if [[ ! -z "$LINUX_PATCHING" ]]; then sed -i 's/^LINUX_PATCHING=.*/LINUX_PATCHING="'"${LINUX_PATCHING}"'"/' board.txt; fi
if [[ ! -z "$PRECOMPILED_UBOOT" ]]; then sed -i 's/^PRECOMPILED_UBOOT=.*/PRECOMPILED_UBOOT="'"${PRECOMPILED_UBOOT}"'"/' board.txt; fi
rm -f override.txt
}
