#!/bin/bash
source lib/function/allwinner
source lib/function/release
source lib/function/echoes
source lib/source
source userdata.txt > /dev/null 2>&1
UD=userdata.txt > /dev/null 2>&1

userdata () {
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 10 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo "$UD file found." > /dev/null 2>&1
else 
    userdata
fi
if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then set -eux -o pipefail;
	else set -eu -o pipefail;
fi
echo
if ls /usr/bin/toilet > /dev/null 2>&1
	then toilet -f small --filter metal 'Debian';
	else echo -e "${RED}Debian Image Builder${FIN}";
fi
echo
RAM=0
PROXY=""
IMAGE_FOLDER="img/"
if `grep -Fx "tritium" "board.txt" >/dev/null;`
	then DEVICE_SOC="h5-libretech-all-h3-cc"
fi
if `grep -Fx "nanopi" "board.txt" >/dev/null;`
	then DEVICE_SOC="h5-nanopi-neo-plus2"
fi
if `grep -Fx "pine64" "board.txt" >/dev/null;`
	then DEVICE_SOC="a64-pine64-plus"
fi
if `grep -Fx "opir1" "board.txt" >/dev/null;`
	then DEVICE_SOC="h2-plus-orangepi-r1"
fi

IMAGE_DATE="$(date +%F)"
IMAGE_FILE_NAME="${DEVICE_SOC}-debian-${DEBIAN_VERSION}-${IMAGE_DATE}.img"
if [ $RAM -ne 0 ]; then
	IMAGE_FOLDER="ram/"
fi
mkdir -p "$IMAGE_FOLDER"
if [ $RAM -ne 0 ]; then
	mount -t tmpfs -o size=3G tmpfs $IMAGE_FOLDER
fi

if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then partition;
	else partition > /dev/null 2>&1;
fi
if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then partition_uuid;
	else partition_uuid > /dev/null 2>&1;
fi

case `grep -Fx "armv7" "board.txt" >/dev/null; echo $?` in
  0)
    if ls debian-${DEBIAN_VERSION}-rootfs-armhf.tar.xz > /dev/null 2>&1;
	then tar -xf debian-${DEBIAN_VERSION}-rootfs-armhf.tar.xz -C p1/
	else echo -e "${YLW}Missing rootfs tarball!${FIN}." && make cleanup && exit;
    fi
    ;;
  1)
    if ls debian-${DEBIAN_VERSION}-rootfs-aarch64.tar.xz > /dev/null 2>&1;
	then tar -xf debian-${DEBIAN_VERSION}-rootfs-aarch64.tar.xz -C p1/
	else echo -e "${YLW}Missing rootfs tarball!${FIN}" && make cleanup && exit;
    fi
    ;;
esac

mkdir -p p1/etc/apt/apt.conf.d p1/etc/dpkg/dpkg.cfg.d
echo "force-unsafe-io" > "p1/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io"

mkdir -p p1/usr/bin
case `grep -Fx "armv7" "board.txt" >/dev/null; echo $?` in
  0)
    cp $(which "qemu-arm-static") p1/usr/bin
    ;;
  1)
    cp $(which "qemu-aarch64-static") p1/usr/bin
    ;;
esac

if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then choose_release;
	else choose_release > /dev/null 2>&1;
fi
if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then create_fstab;
	else create_fstab > /dev/null 2>&1;
fi

if [ -n "$PROXY" ] ; then
	tee "p1/etc/apt/apt.conf.d/30proxy" <<EOF
Acquire::http::proxy "http://127.0.0.1:3142";
EOF
fi

# setup stage2
cp scripts/allwinner-stage2 p1/root
cp lib/function/allwinner p1/root/allwinner.txt
cp lib/source p1/root/source.txt
cp userdata.txt p1/root
cp root-pid.txt p1/root
cp board.txt p1/root
cp files/misc/* p1/root
cp files/scripts/* p1/root
cp files/users/* p1/root
cp firmware/{fw-0a5c_21e8.hcd,UPDATE.mem} p1/root
if `grep -Fx "tritium" "board.txt" >/dev/null;`
    then cp output/tritium/{u-boot-sunxi-with-spl.bin,*.deb} p1/root;
fi
if `grep -Fx "nanopi" "board.txt" >/dev/null;`
    then cp output/nanopi/{u-boot-sunxi-with-spl.bin,*.deb} p1/root;
fi
if `grep -Fx "pine64" "board.txt" >/dev/null;`
    then cp output/pine64/{u-boot-sunxi-with-spl.bin,*.deb} p1/root;
fi
if `grep -Fx "opir1" "board.txt" >/dev/null;`
    then cp output/opir1/{u-boot-sunxi-with-spl.bin,*.deb,mkimage} p1/root && cp files/boot/opir1-firstboot p1/root;
fi
echo -e "${WHT}Starting chroot${FIN} ..."
# mount and chroot
mount -o bind /dev p1/dev
mount -o bind /dev/pts p1/dev/pts
chroot p1 /root/allwinner-stage2
# unmount
umount p1/dev/pts
umount p1/dev
case `grep -Fx "armv7" "board.txt" >/dev/null; echo $?` in
  0)
    rm p1/usr/bin/qemu-arm-static
    ;;
  1)
    rm p1/usr/bin/qemu-aarch64-static
    ;;
esac
cp -f p1/root/kernel.txt .
rm p1/root/allwinner-stage2
rm -f p1/root/*.txt
rm -f p1/var/cache/debconf/*

if [ -n "$PROXY" ] ; then
	rm p1/etc/apt/apt.conf.d/30proxy
fi
rm p1/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io

### Finish

e4defrag -c p1
umount p1

losetup -d "${IMAGE_LOOP_DEV}"
mv "${IMAGE_FOLDER}${IMAGE_FILE_NAME}" "${IMAGE_FILE_NAME}"
if [ $RAM -ne 0 ]; then
	umount "${IMAGE_FOLDER}"
fi
rmdir "${IMAGE_FOLDER}"
rmdir p1
if `grep -Fx "auto=1" "userdata.txt" >/dev/null;`
	then echo && echo_compress && compress_image && echo_done;
	else rename_image;
fi
rm -f root-id.txt root-pid.txt board.txt kernel.txt
echo
if ls *.img > /dev/null 2>&1;
	then ls -l *.img;
fi
if ls *.img.xz > /dev/null 2>&1;
	then ls -l *.img.xz;
fi
echo
