#!/usr/bin/env bash
source /root/source.txt
source /root/userdata.txt
source /root/amlogic.txt
source /root/part-uuid.txt

set -o errexit
set -o pipefail
set -o nounset

echo 'nameserver 8.8.8.8' > /etc/resolv.conf
echo 'nameserver 8.8.4.4' >> /etc/resolv.conf

mount -t proc proc proc/
mount -t sysfs sys sys/

export DEBIAN_FRONTEND="noninteractive"

apt-get update
apt-get install -y apt-utils

### Locales
set_locales

### Timezone
set_timezone

apt upgrade -y
apt dist-upgrade -y
if `grep -Fx 'DISTRO="debian"' "/root/userdata.txt" >/dev/null;`
	then apt install -y ${PKGS1} resolvconf;
fi
if `grep -Fx 'DISTRO="ubuntu"' "/root/userdata.txt" >/dev/null;`
	then apt install -y ${PKGS1} openresolv ifupdown;
fi
if `grep -Fx 'DISTRO="kali"' "/root/userdata.txt" >/dev/null;`
	then apt install -y ${PKGS1} resolvconf;
fi
echo
echo -n "${HOSTNAME}" > /etc/hostname
sed -i "1 a 127.0.1.1	${HOSTNAME}" /etc/hosts
adduser ${user} --gecos ${NAME} --disabled-password
echo "${user}:${passwd}" | chpasswd
adduser ${user} sudo
adduser ${user} audio
adduser ${user} dialout
adduser ${user} video
adduser ${user} disk
echo Done.

#### uInitrd
cd ~
uinitrd

#### Sudoers file 
echo
echo Create sudoers file.
sleep 1s
tee /etc/sudoers.d/010_${user}-nopasswd <<EOF
${user} ALL=(ALL) NOPASSWD: ALL
EOF

#### Firstboot
echo
echo Creating firstboot.
tee /usr/local/sbin/firstboot <<EOF
#!/bin/bash
### Functions
grow_mmcblk () {
bash growpart /dev/mmcblk0 1 > /dev/null 2>&1
sleep 1s
resize2fs /dev/mmcblk0p1 > /dev/null 2>&1
}

grow_mmcblk1 () {
bash growpart /dev/mmcblk1 1 > /dev/null 2>&1
sleep 1s
resize2fs /dev/mmcblk1p1 > /dev/null 2>&1
}

grow_mmcblk2 () {
bash growpart mmcblk2 1 > /dev/null 2>&1
sleep 1s
resize2fs mmcblk2p1 > /dev/null 2>&1
}

### Grow Partition
if touch -c /dev/mmcblk0 2>/dev/null; then grow_mmcblk;
        else echo "" &>/dev/null;
fi

if touch -c /dev/mmcblk1 2>/dev/null; then grow_mmcblk1;
        else echo "" &>/dev/null;
fi

if touch -c /dev/mmcblk2 2>/dev/null; then grow_mmcblk2;
        else echo "" &>/dev/null;
fi

### Clean up
systemctl disable firstboot > /dev/null 2>&1
update-rc.d firstboot remove > /dev/null 2>&1
rm -f /var/cache/debconf/*
rm -f /usr/local/sbin/firstboot
EOF

#### LED triggers
if `grep -Fx "lepotato" "/root/board.txt" >/dev/null;`
    then lepotato_led_triggers
fi
if `grep -Fx "odroidc4" "/root/board.txt" >/dev/null;`
    then odroidc4_led_triggers
fi
if `grep -Fx "odroidhc4" "/root/board.txt" >/dev/null;`
    then odroidc4_led_triggers
fi
if `grep -Fx "odroidn2" "/root/board.txt" >/dev/null;`
    then odroidn2_led_triggers
fi
if `grep -Fx "odroidn2plus" "/root/board.txt" >/dev/null;`
    then odroidn2_led_triggers
fi
#### eMMC flash tools
echo
echo Setting up eMMC tools
sleep 1s
mkdir -p /etc/opt
mkdir -p /usr/lib/u-boot
cp board.txt /etc/opt/
mv -f write2mmc /usr/local/bin/
mv -f *.bin /usr/lib/u-boot/
chmod +x /usr/local/bin/write2mmc
chown root:root /usr/local/bin/write2mmc
echo Done.

#### Scripts
echo
echo Moving scripts.
sleep 1s
cd ~
mkdir -p /usr/local/bin
mv -f firstboot.init /etc/init.d/firstboot
mv -f run-setup /usr/local/bin/
if `grep -Fx "lepotato" "/root/board.txt" >/dev/null;`
    then mv -f sysinfo /usr/local/bin/ && rm -f sysinfo.bl
fi
if `grep -Fx "odroidc4" "/root/board.txt" >/dev/null;`
    then mv -f sysinfo /usr/local/bin/ && rm -f sysinfo.bl
fi
if `grep -Fx "odroidhc4" "/root/board.txt" >/dev/null;`
    then mv -f sysinfo /usr/local/bin/ && rm -f sysinfo.bl
fi
if `grep -Fx "odroidn2" "/root/board.txt" >/dev/null;`
    then mv -f sysinfo.bl /usr/local/bin/sysinfo && rm -f sysinfo
fi
if `grep -Fx "odroidn2plus" "/root/board.txt" >/dev/null;`
    then mv -f sysinfo.bl /usr/local/bin/sysinfo && rm -f sysinfo
fi
mv -f smon /usr/local/bin/
wget -cq --show-progress https://raw.githubusercontent.com/pyavitz/scripts/master/swh
mv -f swh /usr/local/bin/
wget -cq --show-progress https://raw.githubusercontent.com/pyavitz/scripts/master/wifidrv
mv -f wifidrv /usr/local/bin/
wget -cq --show-progress https://raw.githubusercontent.com/pyavitz/scripts/master/governor
mv -f governor /usr/local/bin/
mv -f growpart /usr/bin/
chmod +x /usr/bin/growpart
chmod +x /etc/init.d/firstboot
chown root:root /etc/init.d/firstboot
chmod +x /usr/local/bin/*
chown -R root:root /usr/local/bin/
echo Done.

#### MOTD
echo
echo Adding motd.
sleep 1s
mkdir -p /etc/update-motd.d
tee /etc/update-motd.d/15-brand <<EOF
#!/bin/bash
echo
toilet -f small --filter metal '${MOTD}'
echo 
EOF
if ls /etc/update-motd.d/10-help-text > /dev/null 2>&1
	then rm -f /etc/update-motd.d/10-help-text;
fi
if `grep -Fx "lepotato" "/root/board.txt" >/dev/null;`
    then mv -f 20-sysinfo /etc/update-motd.d/ && rm -f 20-sysinfo.bl
fi
if `grep -Fx "odroidc4" "/root/board.txt" >/dev/null;`
    then mv -f 20-sysinfo /etc/update-motd.d/ && rm -f 20-sysinfo.bl
fi
if `grep -Fx "odroidhc4" "/root/board.txt" >/dev/null;`
    then mv -f 20-sysinfo /etc/update-motd.d/ && rm -f 20-sysinfo.bl
fi
if `grep -Fx "odroidn2" "/root/board.txt" >/dev/null;`
    then mv -f 20-sysinfo.bl /etc/update-motd.d/20-sysinfo && rm -f 20-sysinfo
fi
if `grep -Fx "odroidn2plus" "/root/board.txt" >/dev/null;`
    then mv -f 20-sysinfo.bl /etc/update-motd.d/20-sysinfo && rm -f 20-sysinfo
fi
chmod +x /etc/update-motd.d/*
chown root:root /etc/update-motd.d/15-brand
chown root:root /etc/update-motd.d/20-sysinfo
echo Done.

### Move mc skins
echo
echo Adding mc skins.
sleep 1s
mkdir -p /usr/share/mc/skins
mv -f darkgreen.ini /usr/share/mc/skins/darkgreen.ini
mv -f darkred.ini /usr/share/mc/skins/darkred.ini
echo Done.
echo
echo Adding mc ini and nanorc.
sleep 1s
mkdir -p /root/.config/mc
mv -f root-ini /root/.config/mc/ini
mv -f nanorc-root /root/.nanorc
mkdir -p /home/${user}/.config/mc
mv -f user-ini /home/${user}/.config/mc/ini
mv -f nanorc-user /home/${user}/.nanorc
chown -R root:root /root
chown -R ${user}:${user} /home/${user}
echo Done.

#### Extra firmware
extra_firmware

#### Software
echo
echo Installing firmware and needed packages.
sleep 1s
apt update
if `grep -Fx 'DISTRO="debian"' "/root/userdata.txt" >/dev/null;`
	then apt install -y ${PKGS2} ${FIRMWARE};
fi
if `grep -Fx 'DISTRO="ubuntu"' "/root/userdata.txt" >/dev/null;`
	then apt install -y ${PKGS2};
fi
if `grep -Fx 'DISTRO="kali"' "/root/userdata.txt" >/dev/null;`
	then apt install -y ${PKGS2} ${FIRMWARE} dbus-user-session libical3;
fi
echo Done.

### Network Setup
network_setup

### ZSWAP
echo
echo Adjusting zramswap config.
sleep 1s
zramswap_config
echo Done.

### MOTD instructions
echo
echo Adding motd first boot.
sleep 1s
rm -f /etc/motd
mv -f motd /etc/motd
mv -f new.motd /etc/new.motd
chown root:root /etc/motd
chown root:root /etc/new.motd
echo Done.

### Regulatory db
echo
echo Adding regdb.
sleep 1s
apt install -y crda
git clone https://kernel.googlesource.com/pub/scm/linux/kernel/git/sforshee/wireless-regdb
echo
echo Moving db files.
sleep 1s
cd wireless-regdb
cp -f regulatory.db /lib/firmware/regulatory.db
cp -f regulatory.db.p7s /lib/firmware/regulatory.db.p7s
cd ~
rm -fdr wireless-regdb
echo Done.

### Certificates
echo
update-ca-certificates -f

### Adding groups
echo
echo Adding user to more groups.
sleep 1s
adduser ${user} plugdev
adduser ${user} netdev
adduser ${user} bluetooth
adduser ${user} input
adduser ${user} tty
echo Done.

#### Kernel
echo
echo Installing kernel.
apt update
apt upgrade -y
apt -y clean
apt -y autoclean
sleep 1s
cd ~
dpkg -i *.deb
rm -f *.deb
echo Done.
sleep 1s
fetch_version

#### Service
firstboot_service

if `grep -Fx 'DISTRO="kali"' "/root/userdata.txt" >/dev/null;`
	then kali_hack;
fi
####
echo
echo Creating governor service.
sleep 1s
tee /etc/systemd/system/governor.service <<EOF
[Unit]
Description=Set Governor
ConditionPathExists=/usr/local/bin/governor

[Service]
ExecStart=/usr/local/bin/governor -r &>/dev/null
Type=oneshot
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

####
echo
echo Creating led service.
sleep 1s
tee /etc/systemd/system/leds.service <<EOF
[Unit]
Description=Set LEDs
ConditionPathExists=/usr/local/sbin/led-trigger
[Service]
Type=forking
ExecStart=/usr/local/sbin/led-trigger &>/dev/null
[Install]
WantedBy=multi-user.target
EOF

####
echo
echo Creating rc-local.
sleep 1s
tee /etc/systemd/system/rc-local.service <<EOF
[Unit]
Description=/etc/rc.local
ConditionPathExists=/etc/rc.local

[Service]
Type=forking
ExecStart=/etc/rc.local start
TimeoutSec=0
StandardOutput=tty
RemainAfterExit=yes
SysVStartPriority=99

[Install]
WantedBy=multi-user.target
EOF
tee /etc/rc.local <<EOF
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

exit 0
EOF
chmod +x /etc/rc.local
echo Done.
### Enable services
enable_services > /dev/null 2>&1

#### Own it
chown -R ${user}:${user} /home/${user}
chmod +x /usr/local/bin/*
chown -R root:root /usr/local/bin/
chmod +x /usr/local/sbin/*
chown -R root:root /usr/local/sbin/

#### Finish
echo
echo Moving out of stage2 and creating image.
echo
sleep 2s

umount /proc /sys
