#!/bin/bash

source lib/function/linux

echo -e "BRANCHES: 5.15.y  6.1.y  6.6.y  stable  rc"
echo -e ""
echo -en "BRANCH: "
read VERSION

linux_prng
GIT_STABLE="https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v${VERSION}"
GIT_TORVALDS="https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tag/?h=v${VERSION}"
if [[ `wget -S --spider ${GIT_STABLE} 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then echo "CURRENT: ${VERSION}"; else
	if [[ `wget -S --spider ${GIT_TORVALDS} 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then echo "CURRENT: ${VERSION}"; else
		echo -e "The git branch ${VERSION} is not available."; exit 1; fi
fi

exit 0
