#!/bin/bash

umount p1/proc p1/sys p1/dev p1/run > /dev/null 2>&1
umount p2/proc p2/sys p2/dev p2/run > /dev/null 2>&1
umount -l p1 p2 > /dev/null 2>&1
rm -fr p1 p2 img root-id.txt root-pid.txt part-uuid.txt board.txt > /dev/null 2>&1
losetup -d /dev/loop* > /dev/null 2>&1
echo Done.
