#!/bin/bash

# create dtc list
rm -f dtclist.txt
for f in lib/boards/*; do
	. $f
	if [[ "$COMMON_PKG" == "true" ]]; then
		FIND=`cat board.txt | grep -w COMMON_PKGNAME= | sed 's/COMMON_PKGNAME=//g' | sed 's/"//g'`
		if [[ "$COMMON_PKGNAME" == "$FIND" ]]; then echo -e ${DEVICETREE} | tr ' ' '\n' | tee -a dtclist.txt > /dev/null 2>&1; fi
	else
		FIND=`cat board.txt | grep -w SERIES= | sed 's/SERIES=//g' | sed 's/"//g'`
		if [[ "$SERIES" == "$FIND" ]]; then echo -e ${DEVICETREE} | tr ' ' '\n' | tee -a dtclist.txt > /dev/null 2>&1; fi
	fi
done

exit 0
