#!/usr/bin/env bash

# source /root/source
source /root/board.txt
source /root/userdata.txt > /dev/null 2>&1
export DEBIAN_FRONTEND="noninteractive"

PKGS1="tzdata keyboard-configuration sudo man-db dbus initramfs-tools \
       e2fsprogs u-boot-tools fonty-rg patch wget apt-transport-https \
       dirmngr rsync psmisc parted hdparm aria2 dosfstools pv fdisk"


PKGS2="bluetooth rfkill gpiod git build-essential net-tools distro-info-data \
       ifplugd fuse3 wpasupplicant wireless-tools usbutils alsa-utils gettext wget \
       mc nano figlet toilet curl dialog openssh-client openssh-server ntfs-3g bc \
       bison flex libssl-dev zram-tools python3 python3-setuptools avahi-utils \
       libncursesw5-dev autopoint autoconf automake pkg-config libtool fake-hwclock \
       lsb-release libell0 crda bluez bluez-tools irqbalance ethtool i2c-tools \
       python3-libgpiod"

echo "Adding additional packages beyond basic debian to rootfs"
mount -t proc proc proc/
mount -t sysfs sys sys/

apt-get update
apt-get install -y apt-utils

# Locales
set_locales

# Timezone
set_timezone

apt upgrade -y
apt dist-upgrade -y

if [[ `grep -w 'BOARD="raspi4"' "/root/board.txt"` ]]; then
        :;
else
	apt install -y ${PKGS1} ${PKGS2}
fi

apt -y clean
apt -y autoclean

umount /proc
umount /sys
