#!/usr/bin/env bash

source /root/source.txt
source /root/board.txt
source /root/userdata.txt > /dev/null 2>&1
export DEBIAN_FRONTEND="noninteractive"

echo "Adding additional packages beyond basic debian to rootfs"
mount -t proc proc proc/
mount -t sysfs sys sys/

apt-get update
apt-get install -y apt-utils

# Locales
set_locales

# Timezone
set_timezone

apt upgrade -y
apt dist-upgrade -y

if [[ `grep -w 'BOARD="raspi4"' "/root/board.txt"` ]]; then
        :;
else
	apt install -y ${PKGS1} ${PKGS2}
fi

apt -y clean
apt -y autoclean

umount /proc
umount /sys
