#!/bin/bash
source lib/source.txt
source lib/allwinner_func.txt
source userdata.txt

echo
mkdir -p ${TMP6}
cd ${TMP6}

# ATF
armtrusted_firmware

# UBOOT
npineoplus2_uboot

# BINARY
npineoplus2_binary
