#!/bin/bash
source lib/source.txt
source lib/kernel_func.txt
source lib/allwinner_func.txt
source userdata.txt

mkdir -p ${TMP2}
cd ${TMP2}

### Download kernel
case `grep -Fx "mainline=1" "../userdata.txt" >/dev/null; echo $?` in
  0)
    mainline_download
    ;;
  1)
    stable_download
    ;;
  *)
    #
    ;;
esac


### Extract
case `grep -Fx "mainline=1" "../userdata.txt" >/dev/null; echo $?` in
  0)
    mainline_extract
    ;;
  1)
    stable_extract
    ;;
  *)
    #
    ;;
esac

### Setup
setup

### Patches
pine64_patch

### Defconfig
case `grep -Fx "custom_defconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    cconfig
    ;;
  1)
    pine64_defconfig
    ;;
  *)
    #
    ;;
esac

### Menuconfig
case `grep -Fx "menuconfig=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    menu_config
    ;;
  *)
    #
    ;;
esac

### Build deb
case `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null; echo $?` in
  0)
    ccompile
    ;;
  1)
    ncompile
    ;;
  *)
    #
    ;;
esac
echo
echo Done.
