#!/bin/bash
source lib/rockchip_func.txt
source lib/echo_func.txt
source lib/source.txt
source userdata.txt

if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then set -x && set -eux -o pipefail;
fi
echo
if ls /usr/bin/toilet > /dev/null 2>&1
	then toilet -f term --filter metal 'Debian Image Builder';
	else echo -e "${COL}Debian Image Builder${FIN}";
fi
echo
RAM=0
PROXY=""
IMAGE_FOLDER="img/"
if `grep -Fx "renegade" "board.txt" >/dev/null;`
	then DEVICE_SOC="rk3328-roc-cc";
fi
if `grep -Fx "rock64" "board.txt" >/dev/null;`
	then DEVICE_SOC="rk3328-rock64";
fi
if `grep -Fx "nanopc" "board.txt" >/dev/null;`
	then DEVICE_SOC="rk3399-nanopct4";
fi
IMAGE_FILE_SUFFIX="$(date +%F)"
IMAGE_FILE_NAME="${DEVICE_SOC}-debian-${DEBIAN_VERSION}-${IMAGE_FILE_SUFFIX}.img"
if [ $RAM -ne 0 ]; then
	IMAGE_FOLDER="ram/"
fi
mkdir -p "$IMAGE_FOLDER"
if [ $RAM -ne 0 ]; then
	mount -t tmpfs -o size=3G tmpfs $IMAGE_FOLDER
fi

if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then partition;
	else partition > /dev/null 2>&1;
fi
if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then partition_uuid;
	else partition_uuid > /dev/null 2>&1;
fi

if ls debian-${DEBIAN_VERSION}-rootfs-aarch64.tar.xz > /dev/null 2>&1;
	then tar -xf debian-${DEBIAN_VERSION}-rootfs-aarch64.tar.xz -C p1/
	else echo -e "${YLW}Missing rootfs tarball!${FIN}" && make cleanup && exit;
fi

mkdir -p p1/etc/apt/apt.conf.d p1/etc/dpkg/dpkg.cfg.d
echo "force-unsafe-io" > "p1/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io"

mkdir -p p1/usr/bin
cp $(which "qemu-aarch64-static") p1/usr/bin

if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then choose_release;
	else choose_release > /dev/null 2>&1;
fi
if `grep -Fx "verbose=1" "userdata.txt" >/dev/null;`
	then create_fstab;
	else create_fstab > /dev/null 2>&1;
fi

if [ -n "$PROXY" ] ; then
	tee "p1/etc/apt/apt.conf.d/30proxy" <<EOF
Acquire::http::proxy "http://127.0.0.1:3142";
EOF
fi

# setup stage2
cp scripts/rockchip-stage2 p1/root
cp lib/rockchip_func.txt p1/root
cp lib/source.txt p1/root
cp userdata.txt p1/root
cp part-uuid.txt p1/root
cp board.txt p1/root
cp files/misc/* p1/root
cp files/rules/* p1/root
cp files/scripts/* p1/root
cp files/users/* p1/root
cp firmware/fw-0a5c_21e8.hcd p1/root
if `grep -Fx "renegade" "board.txt" >/dev/null;`
    then cp output/renegade/{*.itb,*.bin,*.deb} p1/root && cp files/boot/boot.cmd p1/root;
fi
if `grep -Fx "rock64" "board.txt" >/dev/null;`
    then cp output/rock64/{*.itb,*.bin,*.deb} p1/root;
fi
if `grep -Fx "nanopc" "board.txt" >/dev/null;`
    then cp output/nanopc/{*.itb,*.bin,*.deb} p1/root;
fi
echo -e "${WHT}Starting chroot${FIN} ..."
# mount and chroot
mount -o bind /dev p1/dev
mount -o bind /dev/pts p1/dev/pts
chroot p1 /root/rockchip-stage2
# unmount
umount p1/dev/pts
umount p1/dev
rm p1/usr/bin/qemu-aarch64-static
rm p1/root/rockchip-stage2
rm p1/root/source.txt
rm p1/root/userdata.txt
rm p1/root/part-uuid.txt
rm p1/root/rockchip_func.txt
rm p1/root/board.txt
rm -f p1/var/cache/debconf/*

if [ -n "$PROXY" ] ; then
	rm p1/etc/apt/apt.conf.d/30proxy
fi
rm p1/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io

### Finish

e4defrag -c p1
umount p1

losetup -d "${IMAGE_LOOP_DEV}"
mv "${IMAGE_FOLDER}${IMAGE_FILE_NAME}" "${IMAGE_FILE_NAME}"
if [ $RAM -ne 0 ]; then
	umount "${IMAGE_FOLDER}"
fi
rmdir "${IMAGE_FOLDER}"
rmdir p1
rm -f part-uuid.txt board.txt
echo
ls *.img
echo
