#!/bin/bash
#AARCH64 ROOTFS
source lib/source
source lib/function/echoes
source lib/function/rootfs
source board.txt > /dev/null 2>&1
source userdata.txt > /dev/null 2>&1
UD=userdata.txt > /dev/null 2>&1

userdata(){
echo ""
echo -e "Please create a ${RED}userdata.txt${FIN} file"
while [ true ]; do
read -t 10 -n 1
if [ $? = 0 ]; then
	exit;
else
	echo -e "run make config";
fi
done
}

if [ -f "$UD" ]; then
	echo "";
else 
	userdata;
fi
validation
if [[ `grep -w "verbose=1" "userdata.txt"` ]]; then
	set -eux -o pipefail;
else
	set -eu -o pipefail;
fi
bclean
if [[ `grep -w 'DISTRO="devuan"' "userdata.txt"` ]]; then
	devuan_keyring;
fi
if [[ `grep -w 'DISTRO="kali"' "userdata.txt"` ]]; then
	kali_keyring;
fi
if [[ `grep -w "Ubuntu" "/etc/os-release"` ]]; then
	:;
else
	if [[ `grep -w 'DISTRO="ubuntu"' "userdata.txt"` ]]; then
		ubuntu_setup;
	fi
fi
ROOT="sysroot"
RELEASE=${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}.tar.xz
if [ -e $RELEASE ]; then
	ls $RELEASE
	exit;
fi
echo -e "${WHT}Starting debootstrap${FIN} ..."
# start debootstrap
mkdir -p ${ROOT}/usr/bin
cp $(command -v "${STATIC}") ${ROOT}/usr/bin;
if [[ `grep -w 'DISTRO="devuan"' "userdata.txt"` ]]; then
	run_devuan-debootstrap;
else
	run_debootstrap;
fi
if [ -e ${ROOT}/usr/bin/qemu-aarch64-static ]; then
	rm -f ${ROOT}/usr/bin/qemu-aarch64-static
fi
if [ -e ${ROOT}/usr/bin/qemu-arm-static ]; then
	rm -f ${ROOT}/usr/bin/qemu-arm-static
fi
rm -f ${ROOT}/var/cache/debconf/*

# finish
echo
echo -e "${WHT}Archiving root filesystem${FIN} ..."
cd ${ROOT}
XZ_DEFAULTS="--threads=${CORES}"; export XZ_DEFAULTS;tar cfJ - * | (pv -terb > ../$RELEASE)
cd ..

rm -fdr ${ROOT}
if [ -e /usr/share/debootstrap/scripts/chimaera ]; then
	rm -f /usr/share/debootstrap/scripts/chimaera;
fi
if [ -e /usr/share/debootstrap/scripts/daedalus ]; then
	rm -f /usr/share/debootstrap/scripts/daedalus;
fi
clear -x
