#!/bin/bash
#AARCH64 ROOTFS
source lib/source
source lib/function/echoes
source lib/function/rootfs
source board.txt > /dev/null 2>&1
source userdata.txt > /dev/null 2>&1
UD=userdata.txt > /dev/null 2>&1

userdata(){
echo ""
echo -e "Please create a ${RED}userdata.txt${FIN} file"
while [ true ]; do
read -t 10 -n 1
if [ $? = 0 ]; then
	exit;
else
	echo -e "run make config";
fi
done
}

if [ -f "$UD" ]; then
	echo "";
else 
	userdata;
fi
validation
bclean
if [[ `grep -w "verbose=1" "userdata.txt"` ]]; then
	set -eux -o pipefail;
else
	set -eu -o pipefail;
fi
if [[ `grep -w 'DISTRO="devuan"' "userdata.txt"` ]]; then
	devuan_keyring;
fi
if [[ `grep -w 'DISTRO="kali"' "userdata.txt"` ]]; then
	kali_keyring;
fi
if [[ `grep -w "Ubuntu" "/etc/os-release"` ]]; then
	:;
else
	if [[ `grep -w 'DISTRO="ubuntu"' "userdata.txt"` ]]; then
		ubuntu_setup;
	fi
fi
ROOT="sysroot"
RELEASE_TARBALL=${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}.tar.xz
if [ -e $RELEASE_TARBALL ]; then
	ls $RELEASE_TARBALL
	exit;
fi
echo -e "${WHT}Starting debootstrap${FIN} ..."
# start debootstrap
if [[ `grep -w "rootfsxl=1" "userdata.txt"` ]]; then
	source lib/function/release
	if [[ `grep -w "verbose=1" "userdata.txt"` ]]; then
		sysroot_partition;
	else
		sysroot_partition > /dev/null 2>&1;
	fi
fi
mkdir -p ${ROOT}/usr/bin
cp $(command -v "${STATIC}") ${ROOT}/usr/bin;
if [[ `grep -w 'DISTRO="devuan"' "userdata.txt"` ]]; then
	run_devuan-debootstrap;
else
	run_debootstrap;
fi

# creating developer tarball
if [[ `grep -w "rootfsxl=1" "userdata.txt"` ]]; then
	sysroot_setup;
	mount -o bind /dev ${ROOT}/dev;
	mount -o bind /dev/pts ${ROOT}/dev/pts;
	cp -f lib/source ${ROOT}/root/source.txt;
	cp -f {scripts/rootfs-extra,userdata.txt,board.txt} ${ROOT}/root/;
	chroot ${ROOT} /root/rootfs-extra;
	umount ${ROOT}/dev/pts;
	umount ${ROOT}/dev;
	rm -f ${ROOT}/root/rootfs-extra;
	rm -f ${ROOT}/root/*.txt;
	rm -f ${ROOT}/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io;
	rm -f ${ROOT}/etc/apt/sources.list
fi
# clean up
if [ -e ${ROOT}/usr/bin/qemu-aarch64-static ]; then
	rm -f ${ROOT}/usr/bin/qemu-aarch64-static
fi
if [ -e ${ROOT}/usr/bin/qemu-arm-static ]; then
	rm -f ${ROOT}/usr/bin/qemu-arm-static
fi
rm -f ${ROOT}/var/cache/debconf/*

# finish
echo
echo -e "${WHT}Archiving root filesystem${FIN} ..."
cd ${ROOT}
XZ_DEFAULTS="--threads=${CORES}"; export XZ_DEFAULTS;tar cfJ - * | (pv -terb > ../$RELEASE_TARBALL)
cd ..

if [[ `grep -w "rootfsxl=1" "userdata.txt"` ]]; then
	losetup -d "${IMAGE_LOOP_DEV}";
	rm -f "${ROOTFS_FOLDER}${RELEASE_NAME}";
	if [ $RAM -ne 0 ]; then
		umount "${ROOTFSFOLDER}";
	fi
	rmdir "${ROOTFS_FOLDER}";
	# Missing something? Hit with the cleaner for the time being.
	make cleanup > /dev/null 2>&1;
fi

if [ -e ${ROOT} ]; then
	rm -fdr ${ROOT}
fi

if [ -e /usr/share/debootstrap/scripts/chimaera ]; then
	rm -f /usr/share/debootstrap/scripts/chimaera;
fi
if [ -e /usr/share/debootstrap/scripts/daedalus ]; then
	rm -f /usr/share/debootstrap/scripts/daedalus;
fi
clear -x
