#!/usr/bin/env bash
source /root/userdata.txt
if [ $VERBOSE -eq 1 ]; then set -x; fi
source /root/source.txt
source /root/board.txt
source /root/services.txt
source /root/${FAMILY}.txt
source /root/networking.txt
SCRIPTS_URL="https://raw.githubusercontent.com/pyavitz/scripts/master/"

set -o errexit
set -o pipefail
set -o nounset

mount -t proc proc proc/
mount -t sysfs sys sys/

export DEBIAN_FRONTEND="noninteractive"

if [[ "$DISTRO" == "ubuntu" ]]; then rm -f /etc/resolv.conf; fi
echo "nameserver ${NAMESERVER1}" > /etc/resolv.conf
echo "nameserver ${NAMESERVER2}" >> /etc/resolv.conf

if [ $NETWORKMANAGER -eq 0 ] && [[ "$DISTRO_VERSION" == "jammy" ]]; then
	# systemd-resolved breaks static ip when using ifupdown, disable on jammy jellyfish
	unlink /etc/resolv.conf
	rm -f /etc/resolv.conf
	systemctl disable systemd-resolved
	echo "nameserver ${NAMESERVER1}" > /etc/resolv.conf
	echo "nameserver ${NAMESERVER2}" >> /etc/resolv.conf
fi

# do not accept new config files in an unattended install
mkdir -p /etc/apt/apt.conf.d
echo 'Dpkg::Options {"--force-confold";};' > /etc/apt/apt.conf.d/71debconf

# dpkg: error: failed to open package info file '/var/lib/dpkg/available' for reading: No such file or directory
if [[ "$DISTRO_VERSION" == "focal" ]]; then dpkg --clear-avail; fi

apt-get update
apt-get install -y apt-utils

# locales
apt install -y locales
export LANGUAGE=${LOCALE}
export LANG=${LOCALE}
export LC_ALL=${LOCALE_LC_ALL}
locale-gen ${LOCALE}

# timezone
ln -snf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
echo -n "${TIMEZONE}" > /etc/timezone

apt upgrade -y
apt dist-upgrade -y
if [[ "$DISTRO_VERSION" =~ ^(ceres|sid|testing|unstable)$ ]]; then :; else apt autoremove -y; fi
# network variables
if [ $NETWORKMANAGER -eq 1 ]; then NETWORKING="network-manager"; else NETWORKING="ifupdown"; fi
# install base and extra packages
if [[ "$DISTRO" =~ ^(debian|raspbian)$ ]]; then
	apt install -y ${PKGS} ${USER_PKGS} ${DEBIAN_FW} resolvconf haveged ${NETWORKING}
fi
if [[ "$DISTRO" == "devuan" ]]; then
	apt install -y openssh-client openssh-server --no-install-recommends
	apt install -y ${PKGS} ${USER_PKGS} ${DEBIAN_FW} openresolv haveged ${NETWORKING}
fi
if [[ "$DISTRO" == "kali" ]]; then
	apt install -y ${PKGS} ${USER_PKGS} ${DEBIAN_FW} dbus-user-session libical3 resolvconf haveged ntpdate ${NETWORKING}
fi
if [[ "$DISTRO" == "ubuntu" ]]; then
	if [[ "$DISTRO_VERSION" == "focal" || "$ARCH" == "arm" ]] || [[ "$ARCH" == "riscv" ]]; then UBUNTU_FW=""; fi
	if [[ "$DISTRO_VERSION" =~ ^(focal|jammy)$ ]]; then RESOLVE="openresolv"; else RESOLVE="systemd-resolved"; fi
	apt install -y ${PKGS} ${USER_PKGS} ${RESOLVE} rng-tools5 ${UBUNTU_FW} ${NETWORKING}
	if [ $NETWORKMANAGER -eq 0 ] && [[ "$DISTRO_VERSION" == "jammy" ]]; then
		# disable systemd-networkd and mask systemd-networkd-wait-online
		systemctl disable systemd-networkd
		systemctl mask systemd-networkd-wait-online
	fi
fi
# apt clean
if [[ "$DISTRO" == "ubuntu" ]]; then
	if [[ -f "/etc/update-motd.d/88-esm-announce" ]]; then
		rm -f /etc/update-motd.d/88-esm-announce
		echo '#!/bin/sh' > /etc/update-motd.d/88-esm-announce
		chmod +x /etc/update-motd.d/88-esm-announce
	fi
	if [[ -f "/etc/update-motd.d/91-contract-ua-esm-status" ]]; then
		rm -f /etc/update-motd.d/91-contract-ua-esm-status
		echo '#!/bin/sh' > /etc/update-motd.d/91-contract-ua-esm-status
		chmod +x /etc/update-motd.d/91-contract-ua-esm-status
	fi
	if [[ -f "/etc/apt/apt.conf.d/20apt-esm-hook.conf" ]]; then
		rm -f /etc/apt/apt.conf.d/20apt-esm-hook.conf
		touch /etc/apt/apt.conf.d/20apt-esm-hook.conf
	fi
	# remove ubuntu pro adverts apt hook
	echo 'DPkg::Post-Invoke {"/usr/local/sbin/remove-ubuntu-advert";};' > /etc/apt/apt.conf.d/80remove-ubuntu-advert
	cat <<EOF > "/usr/local/sbin/remove-ubuntu-advert"
#!/bin/bash

if [[ -f "/etc/update-motd.d/88-esm-announce" ]]; then
	rm -f /etc/update-motd.d/88-esm-announce
	echo '#!/bin/sh' > /etc/update-motd.d/88-esm-announce
	chmod +x /etc/update-motd.d/88-esm-announce
fi
if [[ -f "/etc/update-motd.d/91-contract-ua-esm-status" ]]; then
	rm -f /etc/update-motd.d/91-contract-ua-esm-status
	echo '#!/bin/sh' > /etc/update-motd.d/91-contract-ua-esm-status
	chmod +x /etc/update-motd.d/91-contract-ua-esm-status
fi
if [[ -f "/etc/apt/apt.conf.d/20apt-esm-hook.conf" ]]; then
	rm -f /etc/apt/apt.conf.d/20apt-esm-hook.conf
	touch /etc/apt/apt.conf.d/20apt-esm-hook.conf
fi
EOF
	chmod +x /usr/local/sbin/remove-ubuntu-advert
fi
apt -y clean
apt -y autoclean

# hostname / username / password
if [[ "$HOSTNAME" == "default" ]]; then
	# default hostname
	echo -n "${BOARD}" > /etc/hostname
	sed -i "1 a 127.0.1.1	${BOARD}" /etc/hosts
else
	# custom hostname
	echo -n "${HOSTNAME}" > /etc/hostname
	sed -i "1 a 127.0.1.1	${HOSTNAME}" /etc/hosts
fi
if [ $USERACCT -eq 0 ]; then
	# prevent build fail because of white spaces
	NAME_FIXUP=`echo ${NAME} | sed "s/ //g"`
	echo "";
	adduser ${USERNAME} --gecos ${NAME_FIXUP} --disabled-password
	echo "${USERNAME}:${PASSWORD}" | chpasswd
	adduser ${USERNAME} sudo
	adduser ${USERNAME} audio
	adduser ${USERNAME} dialout
	adduser ${USERNAME} video
	adduser ${USERNAME} disk
	adduser ${USERNAME} plugdev
	adduser ${USERNAME} netdev
	adduser ${USERNAME} bluetooth
	adduser ${USERNAME} input
	adduser ${USERNAME} tty
	adduser ${USERNAME} i2c
	groupadd gpio
	groupadd spi
	adduser ${USERNAME} gpio
	adduser ${USERNAME} spi
fi
if [ $USERACCT -eq 1 ]; then
	mkdir -p /boot;
	mkdir -p /usr/local/sbin;
	mv -f /root/useracct/useraccount /usr/local/sbin/;
	chmod +x /usr/local/sbin/useraccount;
	mv -f /root/{nanorc-user,user-ini} /etc/opt/;
	mv -f /root/useracct/useraccount.txt /boot/useraccount.txt;
	if [[ "$DISTRO" == "devuan" ]]; then
		mkdir -p /etc/init.d;
		mv -f /root/useracct/useraccount.init /etc/init.d/useraccount;
		chmod +x /etc/init.d/useraccount;
		update-rc.d useraccount defaults 5;
		rm -fdr /root/useracct;
	else
		mkdir -p /etc/systemd/system/;
		mv -f /root/useracct/useraccount.service /etc/systemd/system/;
		systemctl enable useraccount > /dev/null 2>&1;
		rm -fdr /root/useracct;
	fi
fi
# set root:toor password
if [ $ROOTPASSWD -eq 1 ]; then echo "root:toor" | chpasswd; fi

# user scripts stage2
if [ $USCRIPTS -eq 1 ]; then uscripts_stage2; fi

# initrd / uinitrd
cd ~
if [[ "$EFI" == "true" ]]; then
	# uefi kernel, initrd, dtb and grub cfg script
	mkdir -p /etc/initramfs/post-update.d/
	mv -f /root/99-uefi /etc/initramfs/post-update.d/
	chmod +x /etc/initramfs/post-update.d/99-uefi
	chown root:root /etc/initramfs/post-update.d/99-uefi
else
	rm -f /root/99-uefi
fi

# alsa asound.state file
if [[ -f "/root/asound.state" ]]; then
	mkdir -p /var/lib/alsa
	mv -f /root/asound.state /var/lib/alsa/asound.state
fi
if [[ -f "/root/asound.conf" ]]; then mv -f /root/asound.conf /etc/asound.conf; fi

# led triggers
if [[ -f "/root/led-trigger" ]]; then
	mv -f /root/led-trigger /usr/local/sbin/led-trigger
	chmod +x /usr/local/sbin/led-trigger
	chown -R root:root /usr/local/sbin/
fi

# bluetooth helper
if [[ "$BOARD" == "pinea64plus" ]]; then
	pine64_bthelper
	if [[ "$DISTRO" =~ ^(debian|ubuntu|kali)$ ]]; then pine64_bt_service > /dev/null 2>&1; fi
fi
# brcm patchram
if [[ "$BOARD" == "nanopineoplus2" ]]; then
	echo ""
	echo "Installing brcm patchram plus ..."
	cd ~
	git clone https://github.com/pyavitz/brcm_patchram_plus.git patchram
	cd patchram
	make
	cp -f brcm_patchram_plus /usr/bin
	cd ~
	rm -fdr patchram
fi

# linux modules
if [[ -v "MODULES_LOAD" ]] && [[ ! -z "$MODULES_LOAD" ]]; then
	mkdir -p /etc/modules-load.d
	echo "# LOAD MODULES" > /etc/modules-load.d/${BOARD}.conf
	echo "$MODULES_LOAD" | tr ' ' '\n' | tee -a /etc/modules-load.d/${BOARD}.conf > /dev/null 2>&1
fi
if [[ -v "MODULES_BLACKLIST" ]] && [[ ! -z "$MODULES_BLACKLIST" ]]; then
	mkdir -p /etc/modprobe.d
	echo "# BLACKLIST MODULES" > /etc/modprobe.d/blacklist-$BOARD.conf
	echo "$MODULES_BLACKLIST" | tr ' ' '\n' | sed 's/^/blacklist /' | tee -a /etc/modprobe.d/blacklist-${BOARD}.conf > /dev/null 2>&1
fi

# board information
if [[ -f "/etc/opt/board.txt" ]]; then :; else mkdir -p /etc/opt; cp /root/board.txt /etc/opt/; fi

# write2mmc script
cd ~
mv -f write2mmc /usr/local/bin/
echo 'DISCLAIMER="true"' | tee /etc/default/write2mmc > /dev/null 2>&1
echo 'VERBOSITY="0"' | tee -a /etc/default/write2mmc > /dev/null 2>&1
chmod +x /usr/local/bin/write2mmc
chown root:root /usr/local/bin/write2mmc

# scripts
echo ""
echo "Moving scripts ..."
sleep 1s
mkdir -p /usr/local/bin
mkdir -p /usr/local/sbin
mv -f {add-overlay,bootcmd,menu-config,menu-config-update,setup,smon,sysinfo} /usr/local/bin/
if [[ "$SERIES" =~ ^(meson-g12a|meson-g12b|meson-sm1)$ ]] && [[ -f "/root/amlmixer" ]]; then
	mv -f amlmixer /usr/local/bin/
fi
# tweaks
if [[ -f "/usr/bin/tweaks" ]]; then tweaks_service > /dev/null 2>&1; fi
# tvbox flash recovery script
if [[ "$BOARD" == "x96air" ]]; then
	mv -f flash-recovery /usr/local/sbin/
	chmod +x /usr/local/sbin/flash-recovery
fi
if [ $NETWORKMANAGER -eq 0 ]; then wget -cq --show-progress ${SCRIPTS_URL}swh -P /usr/local/bin/; fi
wget -cq --show-progress ${SCRIPTS_URL}governor -P /usr/local/bin/
mv -f growpart /usr/bin/
mv -f firstboot /usr/local/sbin/
chmod +x /usr/local/sbin/firstboot
chmod +x /usr/bin/growpart
chmod +x /usr/local/bin/*
chown -R root:root /usr/local/bin/
chown -R root:root /usr/local/sbin/
if [[ "$BOARD" == "nanopineoplus2" ]]; then
	mv -f nanopi-bthelper /usr/local/sbin/bthelper
	chmod +x /usr/local/sbin/bthelper
fi
if [[ "$BOARD" == "tinker" ]]; then
	mv -f rtc-ds1307 /usr/local/sbin/
	chmod +x /usr/local/sbin/rtc-ds1307
fi
if [[ "$DISTRO" == "devuan" ]]; then
	mkdir -p /etc/init.d;
	mv -f firstboot.init /etc/init.d/firstboot
	mv -f leds.init /etc/init.d/leds
	mv -f credentials.init /etc/init.d/credentials
	mv -f governor.init /etc/init.d/governor
	mv -f zramswap.init /etc/init.d/zramswap
	if [[ "$BOARD" == "pinea64plus" ]]; then
		mv -f bthelper.init /etc/init.d/bthelper
		rm -f /etc/init.d/leds
	fi
	if [[ "$BOARD" == "nanopineoplus2" ]]; then mv -f bthelper.init /etc/init.d/bthelper; fi
fi

# motd
mkdir -p /etc/update-motd.d
rm -f /etc/update-motd.d/{00-header,10-uname}
if [[ -f "/etc/update-motd.d/10-help-text" ]]; then
	rm -f /etc/update-motd.d/10-help-text
	echo '#!/bin/sh' > /etc/update-motd.d/10-help-text
	chmod +x /etc/update-motd.d/10-help-text
fi
mv -f {00-header,15-brand,20-sysinfo,90-dynamic-motd} /etc/update-motd.d/
chmod +x /etc/update-motd.d/*
cat <<EOF > "/etc/default/dynamic-motd"
# DYNAMIC MOTD VARIABLES

# header
H_POS="-c"

# banner
B_POS="-r"
B_FONT="term"
B_FONT_STYLE="\033[1m"

# alternative banner
BRANDING="false"
T_FONT="small"
T_FILTER="metal"

# helper
MENUCONFIG="true"
EOF
chown -R root:root /etc/update-motd.d/{00-header,15-brand,20-sysinfo,90-dynamic-motd}
rm -f /etc/motd
echo "" > /etc/motd
chown root:root /etc/motd

# kali services
if [[ "$DISTRO" == "kali" ]]; then 
	if [ $VERBOSE -eq 1 ]; then kali_services; else kali_services > /dev/null 2>&1; fi
fi

# debian bookworm fixups
if [[ "$DISTRO_VERSION" == "bookworm" ]]; then
	apt install -y binfmt-support
	mv -f /root/systemd-binfmt-fixups /usr/local/sbin/systemd-binfmt-fixups
	chmod +x /usr/local/sbin/systemd-binfmt-fixups
	binfmt_fixups_service > /dev/null 2>&1
fi

# clean
rm -f {amlmixer,asound.conf,asound.state,bpi-fanctrl,*-tweaks,*-bthelper,sysinfo,20-sysinfo,write2mmc,*.init,99-uefi,bootcmd,add-overlay,smon,flash-recovery,rtc-ds1307,systemd-binfmt-fixups}

# move mc skins
mkdir -p /usr/share/mc/skins
mv -f darkgreen.ini /usr/share/mc/skins/darkgreen.ini
mv -f darkred.ini /usr/share/mc/skins/darkred.ini
mkdir -p /root/.config/mc
mv -f root-ini /root/.config/mc/ini
mv -f nanorc-root /root/.nanorc
chown -R root:root /root
if [ $USERACCT -eq 0 ]; then
	mkdir -p /home/${USERNAME}/.config/mc
	mv -f user-ini /home/${USERNAME}/.config/mc/ini
	mv -f nanorc-user /home/${USERNAME}/.nanorc
	chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}
fi

# firmware
install_firmware

# network setup
if [ $VERBOSE -eq 1 ]; then
	realtek_conf
	if [ $NETWORKMANAGER -eq 1 ]; then
		networkmanager-setup
		networkmanager-credentials
	else
		ifupdown-setup
		ifupdown-credentials
		router_ifupdown
	fi
	if [[ "$DISTRO" =~ ^(debian|kali|raspbian|ubuntu)$ ]]; then
		credentials_service
	fi
else
	realtek_conf > /dev/null 2>&1
	if [ $NETWORKMANAGER -eq 1 ]; then
		networkmanager-setup > /dev/null 2>&1
		networkmanager-credentials > /dev/null 2>&1
	else
		ifupdown-setup > /dev/null 2>&1
		ifupdown-credentials > /dev/null 2>&1
		router_ifupdown > /dev/null 2>&1
	fi
	if [[ "$DISTRO" =~ ^(debian|kali|raspbian|ubuntu)$ ]]; then
		credentials_service > /dev/null 2>&1
	fi
fi

# allocate zramswap
if [[ -f "/etc/default/zramswap" ]]; then
	sed -i 's/#ALLOCATION=256/ALLOCATION=1024/g' /etc/default/zramswap
	sed -i 's/#SIZE=256/SIZE=1024/g' /etc/default/zramswap
	sed -i 's/#PRIORITY=100/PRIORITY=100/g' /etc/default/zramswap
fi

# wireless regulatory db
wireless_regdb

# sudoers file
if [ $USERACCT -eq 0 ]; then
	echo ""
	tee /etc/sudoers.d/010_${USERNAME}-nopasswd <<EOF
${USERNAME} ALL=(ALL) NOPASSWD: ALL
EOF
fi

# remove zstd compression (not supported by vednor kernels)
if [[ `grep -w "COMPRESS=zstd" "/etc/initramfs-tools/initramfs.conf"` ]]; then
	sed -i 's/COMPRESS=zstd/COMPRESS=xz/g' /etc/initramfs-tools/initramfs.conf
fi

# uimage
if [[ "$BOARD" == "odroidc1" ]]; then make_uimage; fi

# u-boot and kernel packages
echo ""
echo "Installing linux and u-boot package ..."
apt update
apt upgrade -y
if [[ "$EFI" == "true" ]]; then apt install -y grub-efi; fi
apt -y clean
apt -y autoclean
sleep 1s
cd ~
dpkg -i *.deb
rm -f *.deb
sleep 1s
# take note of linux kernel release
if [ -f /usr/src/linux-headers-*/include/config/kernel.release ]; then
	KERNEL_RELEASE=`cat /usr/src/linux-headers-*/include/config/kernel.release`
else
	KERNEL_RELEASE=`ls /boot/config-* | sed 's/\/boot\/config-//g'`
fi
echo -e INSTALLED_KERNEL='"'$KERNEL_RELEASE'"' > /root/kernel.release
if [[ "$EFI" == "true" ]]; then
	# 99-uefi uses /etc/opt/board.txt, this script does not.
	# re-source /root/board.txt to ensure no confusion.
	. /root/board.txt
fi

# system.journal corrupted or uncleanly shut down, renaming and replacing
if [[ -f "/etc/systemd/journald.conf" ]]; then
	sed -i 's/#Storage=auto/Storage=volatile/g' /etc/systemd/journald.conf
	sed -i 's/#SystemMaxFileSize=/SystemMaxFileSize=50M/g' /etc/systemd/journald.conf
	sed -i 's/#SystemMaxFiles=100/SystemMaxFiles=5/g' /etc/systemd/journald.conf
	sed -i 's/#SystemMaxUse=/SystemMaxUse=500M/g' /etc/systemd/journald.conf
fi

# whiptail color palette
if [[ "$DISTRO" == "ubuntu" ]]; then
	mkdir -p /etc/newt
	cat <<EOF > "/etc/newt/palette.dark"
root=,black
checkbox=,black
entry=,black
label=black,
actlistbox=,black
helpline=,black
roottext=lightgray,black
emptyscale=black
disabledentry=black,
EOF
	ln -sf /etc/newt/palette.dark  /etc/alternatives/newt-palette
fi

# udev rules
if [[ "$FAMILY_EXT" =~ ^(odroid|ac2xx|rk3288)$ ]]; then ${FAMILY_EXT}_udev_rules > /dev/null 2>&1; fi
if [[ "$FAMILY" == "amlogic" ]]; then aml_gpiomem_rules > /dev/null 2>&1; fi
if [[ "$BOARD" =~ ^(nanopir4s|nanopir4se|nanopir5c|nanopir5s)$ ]]; then router_udev_rules; fi

# services
if [[ "$FAMILY" == "rockchip" ]] && [[ -f "/etc/default/haveged" ]]; then
	sed -i 's/#DAEMON_ARGS=""/DAEMON_ARGS="-w 1024"/g' /etc/default/haveged
fi

echo ""
echo "Enabling Services ..."
if [[ "$BOARD" == "nanopineoplus2" ]]; then
	if [[ "$DISTRO" == "devuan" ]]; then :; else nanopi_bt_service > /dev/null 2>&1; fi
fi
if [[ "$DISTRO" == "devuan" ]]; then
	echo "== Sysvinit"
	enable_sysvinit > /dev/null 2>&1
else
	firstboot_service > /dev/null 2>&1
	governor_service > /dev/null 2>&1
	led_service > /dev/null 2>&1
	if [[ -f "/usr/local/sbin/led-trigger" ]]; then :; else systemctl disable leds > /dev/null 2>&1; fi
	rc-local_service > /dev/null 2>&1
	echo "== Systemd"
	enable_systemd > /dev/null 2>&1
fi

# own it
if [ $USERACCT -eq 0 ]; then chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}; fi
chmod +x /usr/local/bin/*
chown -R root:root /usr/local/bin/
chmod +x /usr/local/sbin/*
chown -R root:root /usr/local/sbin/

# finish
rm -f /etc/apt/apt.conf.d/71debconf
rm -fdr /*usr-is-merged*
if [[ "$DISTRO" == "ubuntu" ]]; then rm -f /etc/resolv.conf; fi
echo ""
echo "Finalizing ..."
echo ""
sleep .75

umount /proc /sys
