#!/bin/bash
source lib/function/echoes
source lib/function/uboot
source lib/source
source lib/function/compiler
source userdata.txt > /dev/null 2>&1
UD=userdata.txt > /dev/null 2>&1

userdata () {
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 10 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo "$UD file found." > /dev/null 2>&1
else 
    userdata
fi
validation
### Boards
case `grep -Fx "ccache=1" "userdata.txt" >/dev/null; echo $?` in
  0)
	if ls /usr/bin/ccache > /dev/null 2>&1; then :; else sudo apt update && sudo apt install -y ccache && sleep 2s; fi
	rm -f ccache.txt gcc.txt
	ccache_version
    ;;
  1)
	rm -f ccache.txt gcc.txt
	gcc_version
    ;;
esac
if [[ `grep -w "amlogic" "board.txt"` ]]; then
	amlogic-uboot-string;
fi
if [[ `grep -w "allwinner" "board.txt"` ]]; then
	allwinner-uboot-string;
fi
if [[ `grep -Fx "rockchip" "board.txt"` ]]; then
	rockchip-uboot-string;
fi
if [[ `grep -Fx "broadcom" "board.txt"` ]]; then
	bcm2711-uboot-string;
fi
