#!/bin/bash
source lib/source
validation
if [[ -f "board.txt" ]]; then . board.txt; else noboard; fi
source userdata.txt
source lib/function/${FAMILY}
P_BOOT="p1"
if [[ -d "sysroot" ]] || [[ -d "${P_BOOT}" ]]; then make clean; clear -x; fi
if [[ ! "$PLATFORM" =~ ^(allwinner|amlogic|spacemit)$ ]]; then
	echo "${PLATFORM} is not supported."
	exit 1
fi
if [[ ! -d "output/${BOARD}" ]] && [[ `ls output/${BOARD}/u-boot-*.deb` ]]; then
	echo -e "Missing u-boot package"
	exit 1
fi
IMAGE_FOLDER="img/"
if [[ "$FAMILY" == "spacemit" ]]; then
	USB_BOOT_IMAGE="${DTB}-usb-spi-update.img"
	BOOT_LABEL="UPDATE"
else
	USB_BOOT_IMAGE="${DTB}-usb-boot.img"
	BOOT_LABEL="USB_BOOT"
fi

BOOTFS="mkfs -t vfat -n"
BOOT_SCRIPT="files/boot/scripts/usbboot.cmd"
if [[ -f "output/${BOARD}/image/${USB_BOOT_IMAGE}" ]]; then rm -f output/${BOARD}/image/${USB_BOOT_IMAGE}; fi
echo -en "${FAMILY}: " | sed -e 's/\(.*\)/\U\1/'
echo -e "${DEFAULT_MOTD}" | sed -e 's/\(.*\)/\U\1/'
mkdir -p "$IMAGE_FOLDER"

partition (){
truncate -s 32MB "${IMAGE_FOLDER}${USB_BOOT_IMAGE}"
parted --script "${IMAGE_FOLDER}${USB_BOOT_IMAGE}" \
mklabel msdos \
mkpart primary fat32 ${OFFSET} 100%
parted --script "${IMAGE_FOLDER}${USB_BOOT_IMAGE}" set 1 boot on
IMAGE_LOOP_DEV="$(losetup --show -P -f ${IMAGE_FOLDER}${USB_BOOT_IMAGE})"
IMAGE_LOOP_DEV_BOOT="${IMAGE_LOOP_DEV}${P_BOOT}"
MAKE_BOOTFS="${BOOTFS} ${BOOT_LABEL} ${IMAGE_LOOP_DEV_BOOT}"
partprobe "${IMAGE_LOOP_DEV}"
mkdir -p ${P_BOOT}
$MAKE_BOOTFS
mount "${IMAGE_LOOP_DEV_BOOT}" ${P_BOOT}
flash_uboot
sync
if [[ -f "${BOOT_SCRIPT}" ]] && [[ "$PLATFORM" =~ ^(allwinner|amlogic)$ ]]; then
	cp -f ${BOOT_SCRIPT} ${P_BOOT}/boot.cmd
	echo "# mkimage -C none -A ${ARCH} -T script -d boot.cmd boot.scr" >> ${P_BOOT}/boot.cmd
	mkimage -C none -A ${ARCH} -T script -d ${P_BOOT}/boot.cmd ${P_BOOT}/boot.scr
	sleep .50
	umount ${P_BOOT}
	losetup -d "${IMAGE_LOOP_DEV}"
	mkdir -p "output/${BOARD}/image"
	mv "${IMAGE_FOLDER}${USB_BOOT_IMAGE}" "output/${BOARD}/image/${USB_BOOT_IMAGE}"
	rmdir "${IMAGE_FOLDER}"
	rmdir ${P_BOOT}
	echo ""
elif [[ -f "${BOOT_SCRIPT}" ]] && [[ "$PLATFORM" =~ ^(spacemit)$ ]]; then
	cp -f files/boot/scripts/${SERIES}-spi.cmd ${P_BOOT}/boot.cmd
	echo "# mkimage -C none -A ${ARCH} -T script -d boot.cmd boot.scr" >> ${P_BOOT}/boot.cmd
	mkimage -C none -A ${ARCH} -T script -d ${P_BOOT}/boot.cmd ${P_BOOT}/boot.scr
	sleep .50
	if [[ "$SERIES" == "k1" ]]; then cp -f output/${BOARD}/partition_2M.json ${P_BOOT}/; fi
	if [[ "$SERIES" == "k3" ]]; then cp -f output/${BOARD}/partition_4M.json ${P_BOOT}/; fi
	cp -f output/${BOARD}/bootinfo_spinor.bin ${P_BOOT}/
	cp -f output/${BOARD}/FSBL.bin ${P_BOOT}/
	cp -f output/${BOARD}/u-boot-env-default.bin ${P_BOOT}/
	if [[ "$SERIES" == "k3" ]]; then cp -f output/${BOARD}/esos.bin ${P_BOOT}/; fi
	cp -f output/${BOARD}/fw_dynamic.bin ${P_BOOT}/
	cp -f output/${BOARD}/u-boot.bin ${P_BOOT}/
	sync
	umount ${P_BOOT}
	losetup -d "${IMAGE_LOOP_DEV}"
	mkdir -p "output/${BOARD}/image"
	mv "${IMAGE_FOLDER}${USB_BOOT_IMAGE}" "output/${BOARD}/image/${USB_BOOT_IMAGE}"
	rmdir "${IMAGE_FOLDER}"
	rmdir ${P_BOOT}
	echo ""
else
	echo -e "${BOOT_SCRIPT}"
	sleep .50
	umount ${P_BOOT}
	losetup -d "${IMAGE_LOOP_DEV}"
	mkdir -p "output/${BOARD}/image"
	mv "${IMAGE_FOLDER}${USB_BOOT_IMAGE}" "output/${BOARD}/image/${USB_BOOT_IMAGE}"
	rmdir "${IMAGE_FOLDER}"
	rmdir ${P_BOOT}
	echo ""
	rm -f $USB_BOOT_IMAGE
	exit 0
fi
}

if [ $VERBOSE -eq 1 ]; then partition; else partition > /dev/null 2>&1; fi
if [[ -f "output/${BOARD}/image/${USB_BOOT_IMAGE}" ]]; then ls -ls output/${BOARD}/image/${USB_BOOT_IMAGE}; fi

exit 0
