#!/bin/bash

# variables
COMPRESSION="xz"

# functions
linux_packaging(){ # lib/boards/$board
echo "# packaging variables" > "scripts/package/pkgvars"
echo device_tree='"'$DEVICETREE'"' >> "scripts/package/pkgvars"
echo device_tree_2='"'$DEVICETREE2'"' >> "scripts/package/pkgvars"
echo platform='"'$PLATFORM'"' >> "scripts/package/pkgvars"
if [ $standard_packaging -eq 1 ]; then
	echo series_name='"'$SERIES'"' >> "scripts/package/pkgvars"
	echo linux_name='"'$LINUX_IMAGE'"' >> "scripts/package/pkgvars"
	echo headers_name='"'$LINUX_HEADERS'"' >> "scripts/package/pkgvars"
	echo linux_path='"'$LINUX_PATH'"' >> "scripts/package/pkgvars"
	echo dtb_path='"'$LINUX_DTREE'"' >> "scripts/package/pkgvars"
	echo overlays_path='"'$LINUX_OLYS'"' >> "scripts/package/pkgvars"
else
	echo series_name='"'$LEGACY_SERIES'"' >> "scripts/package/pkgvars"
	echo linux_name='"'$LEGACY_IMAGE'"' >> "scripts/package/pkgvars"
	echo headers_name='"'$LEGACY_HEADERS'"' >> "scripts/package/pkgvars"
	echo linux_path='"'$LEGACY_PATH'"' >> "scripts/package/pkgvars"
	echo dtb_path='"'$LEGACY_DTREE'"' >> "scripts/package/pkgvars"
	echo overlays_path='"'$LEGACY_OLYS'"' >> "scripts/package/pkgvars"
fi
echo boot_path='"'$INSTALL_OLYS'"' >> "scripts/package/pkgvars"
echo install_devicetree='"'$INSTALL_DTB'"' >> "scripts/package/pkgvars"
echo install_overlays='"'$INSTALL_OLYS'"' >> "scripts/package/pkgvars"
echo "# packaging compression" >> "scripts/package/pkgvars"
echo compression='"'$COMPRESSION'"' >> "scripts/package/pkgvars"
}
