# skw_extra_symbols := $(src)/drivers/net/wireless/vs6621s40/seekwaveplatform_lite/Module.symvers
# skw_extra_flags := -I$(src)/include/linux/platform_data

# skw_extra_flags += -DCONFIG_SEEKWAVE_BSP_DRIVERS
# skw_extra_flags += -DCONFIG_SWT6621S_LOG_DEBUG

# export skw_extra_flags
# export skw_extra_symbols

obj-$(CONFIG_SEEKWAVE_BSP_DRIVERS) += seekwaveplatform_lite/
obj-$(CONFIG_WLAN_VENDOR_SWT6621S) += swt6621s_wifi/
obj-$(CONFIG_SKW_BT) += swtbt4l/
