#!/bin/bash
# Radxa Zero Rev. 1.5 LED Support Script

FDTDIR="/boot/amlogic"

if [[ `command -v dtc` ]]; then
	:;
else
	echo -e "Missing depends: device-tree-compiler";
	exit 0;
fi

if [ -e $FDTDIR/meson-g12a-radxa-zero.dtb ]; then
	mv -f $FDTDIR/meson-g12a-radxa-zero.dtb $FDTDIR/meson-g12a-radxa-zero.dtb.orig;
	dtc -I dtb -O dts $FDTDIR/meson-g12a-radxa-zero.dtb.orig -o $FDTDIR/meson-g12a-radxa-zero.dts > /dev/null 2>&1;
	sleep 1s
	if [[ `grep -w "leds" "$FDTDIR/meson-g12a-radxa-zero.dts"` ]]; then
		if [[ `grep -w "gpios = <0x4f 0x08 0x00>" "$FDTDIR/meson-g12a-radxa-zero.dts"` ]]; then
			echo -en "LED Support";
			sed -i 's/gpios = <0x4f 0x08 0x00>/gpios = <0x4f 0x0a 0x00>/g' $FDTDIR/meson-g12a-radxa-zero.dts;
			echo -e " [done]";
		fi
		if [[ `grep -w "gpios = <0x4f 0x08 0x00 0x4f 0x0a 0x00>" "$FDTDIR/meson-g12a-radxa-zero.dts"` ]]; then
			echo -en "LED Support";
			sed -i 's/gpios = <0x4f 0x08 0x00 0x4f 0x0a 0x00>/gpios = <0x4f 0x0a 0x00 0x4f 0x0a 0x00>/g' $FDTDIR/meson-g12a-radxa-zero.dts;
			echo -e " [done]";
		fi
	fi
	dtc -I dts -O dtb $FDTDIR/meson-g12a-radxa-zero.dts -o $FDTDIR/meson-g12a-radxa-zero.dtb > /dev/null 2>&1;
	if [ -f $FDTDIR/meson-g12a-radxa-zero.dtb ]; then
		chmod +x $FDTDIR/meson-g12a-radxa-zero.dtb;
		rm -f $FDTDIR/{meson-g12a-radxa-zero.dtb.orig,meson-g12a-radxa-zero.dts};
	else
		mv -f $FDTDIR/meson-g12a-radxa-zero.dtb.orig $FDTDIR/meson-g12a-radxa-zero.dtb;
		rm -f $FDTDIR/meson-g12a-radxa-zero.dts;
		echo -e "LED Support [failed]";
	fi
fi
exit 0
