#!/bin/bash
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr

if [[ `command -v mkimage` ]]; then
	:;
else
	echo -e "Missing depends: u-boot-tools";
	exit 0;
fi

if [ -f /boot/boot.cmd ]; then
	if [ -f /boot/boot.scr ]; then
		rm -f /boot/boot.scr;
		mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr;
	fi
fi

exit 0
