#!/bin/bash
# Radxa Zero Rev. 1.5 Cap SDIO Speed Script

FDTDIR="/boot/amlogic"

if [[ `command -v dtc` ]]; then
	:;
else
	echo -e "Missing depends: device-tree-compiler";
	exit 0;
fi

if [ -e $FDTDIR/meson-g12a-radxa-zero.dtb ]; then
	mv -f $FDTDIR/meson-g12a-radxa-zero.dtb $FDTDIR/meson-g12a-radxa-zero.dtb.orig;
	dtc -I dtb -O dts $FDTDIR/meson-g12a-radxa-zero.dtb.orig -o $FDTDIR/meson-g12a-radxa-zero.dts > /dev/null 2>&1;
	sleep 1s
	if [[ `grep -w "sd-uhs-sdr50" "$FDTDIR/meson-g12a-radxa-zero.dts"` ]]; then
		echo -en "Cap SDIO Speed";
		sed -i 's/sd-uhs-sdr50/cap-mmc-highspeed/g' $FDTDIR/meson-g12a-radxa-zero.dts;
		echo -e " [done]";
	fi
	dtc -I dts -O dtb $FDTDIR/meson-g12a-radxa-zero.dts -o $FDTDIR/meson-g12a-radxa-zero.dtb > /dev/null 2>&1;
	if [ -e $FDTDIR/meson-g12a-radxa-zero.dtb ]; then
		chmod +x $FDTDIR/meson-g12a-radxa-zero.dtb
		rm -f $FDTDIR/{meson-g12a-radxa-zero.dtb.orig,meson-g12a-radxa-zero.dts};
	else
		mv -f $FDTDIR/meson-g12a-radxa-zero.dtb.orig $FDTDIR/meson-g12a-radxa-zero.dtb;
		rm -f $FDTDIR/meson-g12a-radxa-zero.dts;
		echo -e "Cap SDIO Speed [failed]";
	fi
fi

exit 0
