#!/bin/bash
# Radxa Zero Rev. 1.5 LED Support Script

FDTDIR="/boot/amlogic"

if [[ `command -v dtc` ]]; then
	:;
else
	sudo apt update;
	sudo apt install device-tree-compiler -y;
fi

if [ -e $FDTDIR/meson-g12a-radxa-zero.dtb ]; then
	echo -en "LED support";
	mv -f $FDTDIR/meson-g12a-radxa-zero.dtb $FDTDIR/meson-g12a-radxa-zero.dtb.orig;
	dtc -I dtb -O dts $FDTDIR/meson-g12a-radxa-zero.dtb.orig -o $FDTDIR/meson-g12a-radxa-zero.dts > /dev/null 2>&1;
	sed -i 's/gpios = <0x4f 0x08 0x00>/gpios = <0x4f 0x0a 0x00>/g' $FDTDIR/meson-g12a-radxa-zero.dts;
	dtc -I dts -O dtb $FDTDIR/meson-g12a-radxa-zero.dts -o $FDTDIR/meson-g12a-radxa-zero.dtb > /dev/null 2>&1;
	if [ -e $FDTDIR/meson-g12a-radxa-zero.dtb ]; then
		chmod +x $FDTDIR/meson-g12a-radxa-zero.dtb
		rm -f $FDTDIR/{meson-g12a-radxa-zero.dtb.orig,meson-g12a-radxa-zero.dts};
		echo -e " [done]";
	else
		mv -f $FDTDIR/meson-g12a-radxa-zero.dtb.orig $FDTDIR/meson-g12a-radxa-zero.dtb;
		rm -f $FDTDIR/meson-g12a-radxa-zero.dts;
		echo -e " [fail]";
	fi
fi

exit 0
